package com.finndev.master.system.inspector.core

/** Generated MSI string table (Spanish) — 728 keys. */
object LocDataEs {
    val data: Map<String, String> = mapOf(
        "abort" to "Abortar",
        "about" to "Acerca de",
        "about_modules_count" to "{0} módulos — todos completamente funcionales",
        "actions" to "Acciones",
        "app_tagline" to "Ana Sistem Denetçisi — Master System Inspector",
        "apply" to "Aplicar",
        "cancel" to "Cancelar",
        "cat_all" to "Todos",
        "cat_network" to "Red, Seguridad y Diagnóstico",
        "cat_root" to "Root y Kernel",
        "cat_storage" to "Almacenamiento, ISO y Archivos",
        "cat_system" to "Perfilado del Sistema y Utilidades",
        "cat_terminal" to "Terminal, RootFS y Scripts",
        "check_updates" to "Buscar actualizaciones",
        "clear" to "Limpiar",
        "confirm" to "Confirmar",
        "copy" to "Copiar",
        "current_language" to "Idioma actual",
        "dash_all_modules" to "Todos los módulos (1–78)",
        "dash_android" to "Android",
        "dash_categories" to "Categorías",
        "dash_quick" to "Acciones rápidas",
        "dash_ram" to "RAM libre",
        "dash_ram_sub" to "de {0} en total",
        "dash_root" to "Root",
        "dash_root_no" to "Sin root",
        "dash_root_unknown" to "comprobando…",
        "dash_root_yes" to "Con root",
        "dash_storage" to "Almacenamiento libre",
        "dash_storage_free" to "libre",
        "dash_storage_sub" to "de {0}",
        "delete" to "Eliminar",
        "download" to "Descargar",
        "downloading" to "Descargando…",
        "empty_list" to "Aún no hay nada aquí",
        "error" to "Error",
        "export" to "Exportar",
        "filter" to "Filtrar",
        "input" to "Entrada",
        "m01_desc" to "Detección root profunda: gestores Magisk, KernelSU, APatch, binarios su y registro de evidencias.",
        "m01_evidence" to "Evidencias de detección",
        "m01_manager" to "Gestor root",
        "m01_name" to "Auditor Root Avanzado",
        "m01_no_evidence" to "No se encontraron evidencias de root",
        "m01_su_path" to "Ruta del binario su",
        "m02_desc" to "Lee y cambia SELinux entre Enforcing y Permissive con root.",
        "m02_name" to "Conmutador de Modo SELinux",
        "m02_set_enforcing" to "Activar Enforcing",
        "m02_set_permissive" to "Activar Permissive",
        "m02_warn" to "El modo Permissive reduce la seguridad. Úselo solo para depurar.",
        "m03_desc" to "Lee, busca y añade propiedades del sistema con soporte de escritura root.",
        "m03_edit" to "Añadir nueva propiedad",
        "m03_hint" to "Las propiedades se añaden a /system/build.prop (el sistema se remonta rw).",
        "m03_loaded" to "Propiedades cargadas",
        "m03_name" to "Editor de Build.prop en Vivo",
        "m04_desc" to "Lista, ejecuta e instala scripts de /system/etc/init.d con root.",
        "m04_found" to "Scripts instalados",
        "m04_hint" to "El script se codifica en base64 para sobrevivir al quoting; se ejecuta en el próximo arranque.",
        "m04_install" to "Instalar",
        "m04_name" to "Ejecutor de Scripts Init.d",
        "m04_new" to "Instalar nuevo script",
        "m04_none" to "No hay scripts init.d (puede faltar soporte init.d)",
        "m04_script" to "Cuerpo del script",
        "m05_current" to "Flags de montaje actuales",
        "m05_desc" to "Remonta /system y /vendor como lectura-escritura o solo lectura con root.",
        "m05_hint" to "En dispositivos system-as-root se remonta el punto / en su lugar.",
        "m05_name" to "Remontador de Particiones del Sistema",
        "m05_none" to "No se encontraron entradas system/vendor",
        "m05_remount_ro" to "Remontar RO",
        "m05_remount_rw" to "Remontar RW",
        "m06_available" to "Gobernadores disponibles",
        "m06_current" to "Estado por núcleo",
        "m06_desc" to "Perfil de frecuencia por núcleo y gobernador; cambia gobernadores al vuelo.",
        "m06_name" to "Perfilador de Gobernador CPU",
        "m06_no_governors" to "El kernel no expone la lista de gobernadores",
        "m07_cores" to "Núcleos",
        "m07_cpu0_note" to "CPU0 es el núcleo de arranque y no puede desactivarse.",
        "m07_desc" to "Activa/desactiva núcleos CPU y acota las frecuencias mín/máx.",
        "m07_freq_limit" to "Límites de frecuencia",
        "m07_limit_hint" to "Los límites se aplican a todas las políticas cpufreq como porcentaje del máximo de hardware.",
        "m07_max" to "Frecuencia máxima",
        "m07_min" to "Frecuencia mínima",
        "m07_name" to "Hotplug de Núcleos y Limitador de Frecuencia",
        "m07_offline" to "Desactivar",
        "m07_online" to "Activar",
        "m08_current" to "Estado LMK actual",
        "m08_desc" to "Lee y ajusta los umbrales minfree del lowmemorykiller.",
        "m08_edit" to "Ajustar minfree",
        "m08_hint" to "Valores en kB por nivel de prioridad, separados por comas (6 niveles).",
        "m08_lmk_missing" to "LMK no expuesto (los kernels modernos usan PSI/lmkd)",
        "m08_name" to "Ajustador del Low Memory Killer",
        "m09_cycles" to "Ciclos",
        "m09_cycles_na" to "solo Android 14+",
        "m09_desc" to "Salud de batería, temperatura, ciclos y control del umbral de carga.",
        "m09_health" to "Salud",
        "m09_level" to "Nivel",
        "m09_name" to "Gestor de Batería y Carga",
        "m09_now" to "Batería actual",
        "m09_tech" to "Tecnología",
        "m09_temp" to "Temperatura",
        "m09_threshold" to "Umbral de carga",
        "m09_threshold_current" to "Umbral actual",
        "m09_threshold_hint" to "ej. 80 mantiene la batería entre 20-80% para alargar su vida (dispositivos compatibles).",
        "m09_threshold_na" to "no soportado por el kernel",
        "m09_threshold_new" to "Nuevo umbral (%)",
        "m09_voltage" to "Voltaje",
        "m10_current" to "Overrides de pantalla actuales",
        "m10_density" to "Densidad (DPI)",
        "m10_desc" to "Sobrescribe resolución y densidad de pantalla con wm size / wm density.",
        "m10_name" to "Manipulador de Resolución y DPI",
        "m10_size" to "Resolución",
        "m10_warn" to "Valores agresivos pueden volver ilegible la UI — Restablecer devuelve los valores por defecto.",
        "m11_apps" to "Apps instaladas",
        "m11_desc" to "Congela, oculta, desinstala (user 0) y restaura paquetes del sistema vía pm.",
        "m11_enable" to "Habilitar",
        "m11_freeze" to "Congelar",
        "m11_hint" to "La desinstalación usa 'pm uninstall --user 0' — reversible con Habilitar; el APK permanece en disco.",
        "m11_name" to "Congelador de Apps del Sistema",
        "m11_restore" to "Restaurar paquete",
        "m11_restore_pkg" to "nombre del paquete",
        "m11_unhide" to "Mostrar",
        "m11_uninstall" to "Desinstalar",
        "m12_count" to "Sensores en este dispositivo",
        "m12_desc" to "Transmisión en vivo de giroscopio, acelerómetro, magnetómetro y más.",
        "m12_name" to "Transmisor de Sensores en Vivo",
        "m12_power" to "Consumo",
        "m12_range" to "Rango máximo",
        "m12_resolution" to "Resolución",
        "m13_buffer" to "Instantánea del buffer",
        "m13_desc" to "Lee el ring buffer del kernel y síguelo en vivo con dmesg -w.",
        "m13_empty" to "El buffer está vacío o ilegible",
        "m13_follow" to "Iniciar seguimiento",
        "m13_live" to "Seguimiento en vivo",
        "m13_name" to "Lector de Registro del Kernel (dmesg)",
        "m13_read" to "Leer buffer (root)",
        "m14_awake" to "Tiempo despierto",
        "m14_boot_id" to "ID de arranque",
        "m14_deep" to "Suspensión profunda",
        "m14_desc" to "Tiempo activo, proporción de suspensión profunda y línea de tiempo de arranque.",
        "m14_name" to "Analizador de Arranque e Inicio",
        "m14_no_log" to "No hay eventos de arranque disponibles",
        "m14_stages" to "Eventos de arranque",
        "m14_stats" to "Estadísticas de arranque",
        "m14_uptime" to "Tiempo desde el arranque",
        "m15_cores" to "Hilos",
        "m15_desc" to "Benchmark de estrés SHA-256 (mono/multi núcleo) más test de ancho de banda de memoria.",
        "m15_hint" to "Ejecuta 2 s mono núcleo, 2 s todos los núcleos en SHA-256 y una pasada de 96 MB de memoria.",
        "m15_mem" to "Memoria",
        "m15_multi" to "Multi núcleo",
        "m15_name" to "Prueba de Rendimiento CPU y RAM",
        "m15_running" to "Probando…",
        "m15_scores" to "Puntuaciones",
        "m15_single" to "Mono núcleo",
        "m16_apk_update" to "apk update && upgrade",
        "m16_bootstrapping" to "preparando",
        "m16_desc" to "Rootfs genuino de Alpine Linux vía PRoot en el almacenamiento de la app — con gestión completa de apk.",
        "m16_exited" to "finalizada",
        "m16_hint" to "Pruebe: apk update • apk add python3 • cat /etc/alpine-release",
        "m16_idle" to "inactiva",
        "m16_input_hint" to "escriba un comando y pulse Enviar",
        "m16_name" to "Terminal PRoot Alpine Linux Real",
        "m16_restart" to "Reiniciar sesión",
        "m16_running" to "en marcha",
        "m16_share_log" to "Compartir transcripción",
        "m16_state" to "Sesión",
        "m16_stop" to "Detener sesión",
        "m17_clone" to "Clonar repositorio (depth 1)",
        "m17_desc" to "Detecta com.termux, lo lanza y clona repositorios Git mediante git de Alpine.",
        "m17_git" to "Clonador Git",
        "m17_git_hint" to "Los repositorios se clonan en /sdcard/MSI/GitRepos usando el git de Alpine incluido.",
        "m17_installed" to "instalado",
        "m17_launch" to "Abrir Termux",
        "m17_name" to "Integración Termux y Clonador Git",
        "m17_not_installed" to "no instalado",
        "m18_arch" to "Arquitectura",
        "m18_config" to "Configuración de la máquina",
        "m18_create_disk" to "Crear disco qcow2",
        "m18_desc" to "Instala y lanza máquinas QEMU (x86_64 / i386 / aarch64) dentro del rootfs Alpine.",
        "m18_disk" to "Tamaño de disco (GB)",
        "m18_hint" to "QEMU corre sin GUI con consola serie; la ruta ISO apunta a un archivo en /sdcard.",
        "m18_install" to "Instalar QEMU (apk)",
        "m18_launch" to "Lanzar en terminal",
        "m18_name" to "Emulador Multi-Arquitectura QEMU",
        "m18_ram" to "Memoria",
        "m19_bash_note" to "bash se instala bajo demanda dentro del rootfs Alpine (apk add bash).",
        "m19_desc" to "Ejecute scripts .sh con salida en vivo vía Alpine /bin/sh, bash de Alpine o sh de Android.",
        "m19_engine" to "Motor de scripts",
        "m19_name" to "Ejecutor de Scripts Bash y Shell",
        "m19_running" to "Ejecutando…",
        "m19_script" to "Script",
        "m20_args" to "Argumentos",
        "m20_compat" to "Compatibilidad del dispositivo",
        "m20_compat_no" to "ABI incompatible",
        "m20_compat_yes" to "compatible",
        "m20_desc" to "Inspeccione y ejecute directamente binarios ARM/x86 con root.",
        "m20_hint" to "chmod +x se aplica automáticamente; los binarios se ejecutan vía su.",
        "m20_inspect" to "Inspeccionar ELF",
        "m20_name" to "Ejecutor de Binarios ELF Nativos",
        "m20_not_elf" to "No es un archivo ELF",
        "m20_path" to "Ruta del binario",
        "m20_pick" to "Binario",
        "m21_code" to "Código",
        "m21_desc" to "Ejecute scripts Python 3 y Lua 5.4 dentro del rootfs Alpine — intérpretes reales.",
        "m21_in_terminal" to "Abrir interactivo en terminal",
        "m21_install" to "Instalar vía apk",
        "m21_installed" to "listo",
        "m21_lang" to "Lenguaje",
        "m21_name" to "Intérprete Python y Lua",
        "m21_not_installed" to "aún no instalado",
        "m21_running" to "Ejecutando…",
        "m21_runtime" to "Runtime",
        "m22_analyze" to "Analizar",
        "m22_desc" to "Inspección completa de cabeceras ELF: clase, endian, máquina, entry point, PT_INTERP.",
        "m22_invalid" to "ELF inválido",
        "m22_list" to "Listar directorio",
        "m22_listing" to "Listado del directorio",
        "m22_machine" to "Máquina",
        "m22_name" to "Analizador Profundo de Binarios ELF",
        "m22_no_dir" to "Directorio ilegible",
        "m22_pick" to "Un archivo ELF",
        "m22_type" to "Tipo",
        "m23_desc" to "chmod / chown de cualquier archivo vía root con stat en vivo.",
        "m23_mode" to "Modo (octal)",
        "m23_name" to "Gestor de Permisos de Archivos",
        "m23_stat" to "Estado actual",
        "m24_custom" to "Entradas PATH personalizadas",
        "m24_desc" to "Inspeccione el PATH del shell MSI y añada directorios personalizados.",
        "m24_extra" to "Directorios extra (separados por dos puntos)",
        "m24_hint" to "Se aplica a cada sesión de shell MSI y al entorno PRoot.",
        "m24_name" to "Gestor de Variables PATH",
        "m25_applets" to "Applets",
        "m25_desc" to "Detecta busybox, lista sus applets e instala busybox-static vía Alpine.",
        "m25_detect" to "Detección",
        "m25_install" to "Instalar busybox-static",
        "m25_install_btn" to "Instalar",
        "m25_install_hint" to "El binario estático se exporta a /sdcard/MSI/busybox mediante el gestor de paquetes Alpine.",
        "m25_name" to "Integración y Validador Busybox",
        "m25_not_found" to "no encontrado",
        "m26_actions" to "Acciones de emergencia",
        "m26_confirm" to "¿Ejecutar este comando?",
        "m26_custom" to "Comando personalizado (su)",
        "m26_desc" to "Comandos de emergencia: reparar permisos, recortar cachés, remontar, reiniciar.",
        "m26_name" to "Consola de Recuperación de Emergencia",
        "m27_builder" to "Constructor de macros",
        "m27_desc" to "Encadena comandos shell con retardos en macros guardados de un solo toque.",
        "m27_format" to "Un paso por línea: comando|retardo_ms — prefijo '#root ' para forzar su",
        "m27_name" to "Nombre de la macro",
        "m27_none" to "Aún no hay macros",
        "m27_saved" to "Macros guardadas",
        "m27_steps" to "Pasos",
        "m28_current" to "Transcripción de la sesión actual",
        "m28_desc" to "Guarda la transcripción del terminal y registros de sesión como .txt / .log.",
        "m28_hint" to "Los archivos se guardan en registros privados de la app y pueden compartirse.",
        "m28_lines" to "Líneas",
        "m28_name" to "Exportador de Registros de Terminal",
        "m28_none" to "Aún no hay registros",
        "m28_saved" to "Registros guardados",
        "m29_desc" to "Escriba notas con vista previa markdown instantánea, guardadas en el almacenamiento interno.",
        "m29_edit" to "Editar",
        "m29_hint" to "Soporta # encabezados, **negrita**, `código`, listas y bloques de código.",
        "m29_name" to "Editor de Notas Markdown Offline",
        "m29_new" to "Nueva nota",
        "m29_none" to "Aún no hay notas",
        "m29_notes" to "Notas",
        "m29_preview" to "Vista previa",
        "m30_desc" to "Escanee cualquier formato de código de barras y genere códigos QR exportables.",
        "m30_generate" to "Generador",
        "m30_generate_btn" to "Generar QR",
        "m30_name" to "Escáner de QR y Códigos de Barras",
        "m30_result" to "Resultado",
        "m30_save" to "Guardar en Descargas",
        "m30_scan" to "Escáner",
        "m30_scan_btn" to "Escanear código",
        "m30_scan_cancel" to "Escaneo cancelado",
        "m31_bytes" to "Bytes",
        "m31_desc" to "Convierta texto entre Base64, hexadecimal y binario — más hashing de archivos.",
        "m31_file" to "Modo archivo (≤ 8 MB)",
        "m31_file_b64" to "Codificar archivo a Base64",
        "m31_file_limit" to "Archivo demasiado grande o inexistente (límite 8 MB)",
        "m31_invalid_b64" to "Entrada Base64 inválida",
        "m31_invalid_bin" to "Entrada binaria inválida",
        "m31_invalid_hex" to "Entrada hex inválida",
        "m31_mode" to "Modo de conversión",
        "m31_name" to "Codificador Base64, Hex y Binario",
        "m32_desc" to "Embellece, valida y formatea documentos JSON y XML.",
        "m32_format" to "Formatear y validar",
        "m32_invalid" to "Inválido",
        "m32_invalid_json" to "JSON inválido",
        "m32_invalid_xml" to "XML inválido",
        "m32_mode" to "Formato",
        "m32_name" to "Formateador JSON y XML",
        "m32_valid" to "Documento válido",
        "m33_add" to "Añadir entrada",
        "m33_desc" to "Bóveda AES-256-GCM con derivación PBKDF2 — totalmente offline.",
        "m33_empty" to "La bóveda está vacía",
        "m33_entries" to "Entradas",
        "m33_gen" to "Generar",
        "m33_hint" to "La bóveda se cifra con AES-GCM; la clave nunca sale del dispositivo.",
        "m33_lock" to "Bloquear bóveda",
        "m33_master" to "Contraseña maestra",
        "m33_name" to "Gestor de Contraseñas Cifrado Offline",
        "m33_pass" to "Contraseña",
        "m33_short_pwd" to "La contraseña maestra debe tener al menos 4 caracteres",
        "m33_title" to "Título",
        "m33_unlock" to "Bóveda",
        "m33_unlock_btn" to "Abrir / crear bóveda",
        "m33_user" to "Usuario / correo",
        "m33_wrong_pwd" to "Contraseña maestra incorrecta",
        "m34_desc" to "Barrido de la subred /24 en busca de hosts activos y resolución de MAC.",
        "m34_found" to "Dispositivos descubiertos",
        "m34_hint" to "Se sondean 254 hosts en paralelo; la MAC proviene de la tabla ARP.",
        "m34_name" to "Escáner de Dispositivos LAN IP y MAC",
        "m34_none" to "No se encontraron dispositivos",
        "m34_scan" to "Escanear subred",
        "m34_scanning" to "Escaneando…",
        "m34_subnet" to "Subred (x.x.x.)",
        "m35_closed" to "cerrado",
        "m35_desc" to "Compruebe puertos TCP y UDP en cualquier host con sockets en paralelo.",
        "m35_filtered" to "sin respuesta",
        "m35_host" to "Host",
        "m35_name" to "Escáner de Puertos (TCP/UDP)",
        "m35_none" to "Escanee primero un objetivo",
        "m35_open" to "ABIERTO",
        "m35_ports" to "Puertos",
        "m35_target" to "Objetivo",
        "m35_udp_hint" to "UDP 'sin respuesta' suele significar abierto-o-filtrado (sin error ICMP).",
        "m36_count" to "Cantidad",
        "m36_desc" to "Ping continuo con gráfico de latencia por respuesta y estadísticas mín/med/máx.",
        "m36_name" to "Monitor Avanzado de Ping y Latencia",
        "m36_start" to "Iniciar ping",
        "m36_target" to "Objetivo del ping",
        "m37_adguard" to "AdGuard (bloqueo de anuncios)",
        "m37_auto" to "Automático (oportunista)",
        "m37_cloudflare" to "Cloudflare (1.1.1.1)",
        "m37_current" to "DNS privado actual",
        "m37_custom" to "Hostname personalizado",
        "m37_desc" to "Imponga DNS privado (DoT): Cloudflare, Google, AdGuard, Quad9.",
        "m37_google" to "Google (8.8.8.8)",
        "m37_hint" to "Aplica el DNS privado de Android sobre TLS mediante el proveedor de ajustes (root).",
        "m37_name" to "Imposición de DNS Personalizado (Root)",
        "m37_off" to "Desactivar DNS privado",
        "m37_presets" to "Preajustes",
        "m37_quad9" to "Quad9 (seguridad)",
        "m38_add_rule" to "Añadir regla",
        "m38_allow" to "Permitir (eliminar)",
        "m38_block" to "Bloquear puerto",
        "m38_desc" to "Inspeccione cadenas iptables y añada/elimine reglas de bloqueo de puertos con root.",
        "m38_hint" to "Las reglas usan REJECT en la cadena seleccionada; se muestra el ruleset de nftables si existe.",
        "m38_ipt_unavailable" to "iptables no disponible o bloqueado",
        "m38_name" to "Gestor de Reglas del Cortafuegos",
        "m38_nft" to "nftables",
        "m38_nft_available" to "disponible",
        "m38_nft_missing" to "no disponible",
        "m39_desc" to "Tabla en vivo estilo netstat de extremos TCP/UDP mapeados a apps.",
        "m39_hint" to "Lee /proc/net/tcp, tcp6, udp y udp6; los UID se resuelven a paquetes de apps.",
        "m39_name" to "Inspector de Sockets de Red Activos",
        "m39_none" to "No hay sockets legibles",
        "m39_sockets" to "Sockets",
        "m39_table" to "Tabla de extremos",
        "m40_desc" to "Medición de latencia, descarga y subida contra Cloudflare.",
        "m40_down" to "Descarga",
        "m40_hint" to "Descarga 25 MB y sube 10 MB — vigile su plan de datos.",
        "m40_latency" to "Latencia",
        "m40_name" to "Test de Velocidad de Internet",
        "m40_results" to "Resultados",
        "m40_running" to "Midiendo…",
        "m40_start" to "Iniciar test",
        "m40_up" to "Subida",
        "m41_desc" to "Cambie la dirección MAC de cualquier interfaz con valores aleatorios o propios.",
        "m41_hint" to "El Wi-Fi debe reconectarse tras cambiar wlan0; algunos drivers rechazan MACs personalizadas.",
        "m41_iface" to "Interfaz",
        "m41_interfaces" to "Interfaces",
        "m41_invalid_mac" to "Formato MAC inválido",
        "m41_name" to "Falsificación de Dirección MAC (Root)",
        "m41_new_mac" to "Nueva MAC",
        "m41_random" to "Aleatoria",
        "m41_spoof" to "Falsificar",
        "m42_channel" to "Canal",
        "m42_congestion" to "Congestión de canales",
        "m42_current" to "Conexión actual",
        "m42_desc" to "Potencia de señal, datos del enlace, congestión de canales y redes cercanas.",
        "m42_freq" to "Frecuencia",
        "m42_grant" to "Conceder ubicación",
        "m42_level" to "Nivel",
        "m42_location" to "Permiso de ubicación",
        "m42_location_hint" to "Android exige permiso de ubicación para exponer los resultados del escaneo.",
        "m42_name" to "Analizador de Señal y Canales Wi-Fi",
        "m42_networks" to "Redes cercanas",
        "m42_rssi" to "Señal (RSSI)",
        "m43_cert" to "Certificado",
        "m43_chain" to "Cadena",
        "m43_cipher" to "Suite de cifrado",
        "m43_desc" to "Realice un handshake TLS e inspeccione la cadena de certificados completa.",
        "m43_expired" to "CADUCADO",
        "m43_inspect" to "Inspeccionar",
        "m43_name" to "Inspección de Certificados SSL y TLS",
        "m43_status" to "Validez",
        "m43_target" to "Host (puerto 443)",
        "m43_tls_version" to "Versión TLS",
        "m43_valid" to "válido",
        "m43_valid_from" to "Válido desde",
        "m43_valid_to" to "Válido hasta",
        "m44_connections" to "Conexiones rastreadas",
        "m44_desc" to "Seguimiento de aperturas/cierres de conexiones con contabilidad de tráfico por app.",
        "m44_hint" to "Sondea las tablas de sockets del kernel y calcula diferencias; los deltas RX/TX vienen de TrafficStats.",
        "m44_log" to "Registro de eventos",
        "m44_name" to "Sniffer de Paquetes y Registro de Tráfico",
        "m44_start" to "Iniciar seguimiento",
        "m44_status" to "Estado",
        "m45_ap" to "Estado del tethering",
        "m45_ap_off" to "El hotspot parece inactivo",
        "m45_clients" to "Clientes conectados",
        "m45_desc" to "Muestra el estado del tethering y los clientes del hotspot (vía ARP).",
        "m45_hint" to "Los clientes se derivan de la tabla ARP mientras el hotspot está activo.",
        "m45_name" to "Inspector de Hotspot y Tethering",
        "m45_no_clients" to "Sin clientes conectados",
        "m46_answer" to "Su respuesta",
        "m46_bench" to "Banco de pruebas",
        "m46_challenge" to "Desafío",
        "m46_desc" to "Genere captchas locales distorsionados y mida tasas de acierto/fallo.",
        "m46_fail" to "FALLIDO",
        "m46_log" to "Registro de intentos",
        "m46_name" to "Banco de Pruebas Captcha y Anti-Bots",
        "m46_new" to "Nuevo desafío",
        "m46_pass" to "CORRECTO",
        "m46_stats" to "Resueltos / fallidos",
        "m46_verify" to "Verificar",
        "m47_desc" to "Contraseñas SecureRandom, tokens hex, UUIDs y frases de paso.",
        "m47_hint" to "Toda la entropía proviene del generador SecureRandom de la plataforma.",
        "m47_length" to "Longitud",
        "m47_mode" to "Modo",
        "m47_name" to "Generador Seguro de Contraseñas y Tokens",
        "m47_passphrase" to "Frase de paso",
        "m47_password" to "Contraseña",
        "m47_regenerate" to "Regenerar",
        "m47_results" to "Generado",
        "m48_confirm" to "Esto destruye los datos de forma permanente. ¿Continuar?",
        "m48_desc" to "Sobrescribe archivos con múltiples pasadas aleatorias antes de borrarlos.",
        "m48_exists" to "Existe",
        "m48_hint" to "1-7 pasadas aleatorias + pasada final de ceros; los directorios se trituran recursivamente.",
        "m48_name" to "Triturador de Archivos Sensibles",
        "m48_passes" to "Pasadas",
        "m48_running" to "Triturando…",
        "m48_shred" to "Triturar permanentemente",
        "m48_target" to "Objetivo",
        "m49_desc" to "Pruebe expresiones regulares con vista previa de coincidencias y sustitución.",
        "m49_input" to "Texto de prueba",
        "m49_matches" to "Coincidencias",
        "m49_name" to "Banco de Pruebas de Regex",
        "m49_pattern" to "Patrón",
        "m49_replace" to "Vista previa de sustitución",
        "m49_with" to "Sustituir por",
        "m50_add_palette" to "Añadir a la paleta",
        "m50_clear" to "Vaciar paleta",
        "m50_current" to "Color actual",
        "m50_desc" to "Selector HSL interactivo con códigos HEX / RGB y paleta guardada.",
        "m50_dials" to "Controles",
        "m50_hex_input" to "Desde HEX",
        "m50_hue" to "Tono",
        "m50_lum" to "Luminosidad",
        "m50_name" to "Paleta de Colores y Selector HEX/RGB",
        "m50_palette" to "Paleta",
        "m50_sat" to "Saturación",
        "m51_arch" to "Arquitectura",
        "m51_config" to "Descarga",
        "m51_desc" to "Descargador de ISO con selector de arquitectura, reanudación, progreso y SHA-256.",
        "m51_dest" to "Destino",
        "m51_name" to "Descargador de ISO ValiantCore",
        "m51_sha256" to "Calcular SHA-256",
        "m51_verify" to "Verificación hash",
        "m51_verify_hint" to "Compare el digest calculado con la fuente en la que confía.",
        "m52_config" to "Configuración del servidor",
        "m52_desc" to "Comparta cualquier carpeta por HTTP en la LAN con un índice estilizado.",
        "m52_dir" to "Directorio compartido",
        "m52_hint" to "Corre como servicio en primer plano de sincronización de datos; soporta peticiones Range para medios.",
        "m52_log" to "Registro de peticiones",
        "m52_log_empty" to "Aún no hay peticiones",
        "m52_name" to "Servidor Local de Compartición HTTP",
        "m52_port" to "Puerto",
        "m52_running" to "en marcha",
        "m52_served" to "Peticiones atendidas",
        "m52_start" to "Iniciar servidor",
        "m52_status" to "Estado",
        "m52_stopped" to "detenido",
        "m53_all" to "Copia masiva",
        "m53_apps" to "Paquetes instalados",
        "m53_backup_user_apps" to "Respaldar todas las apps de usuario",
        "m53_desc" to "Copie APKs instaladas al almacenamiento — apps individuales o todas las de usuario.",
        "m53_hint" to "Las copias se escriben en /sdcard/MSI/APKBackups.",
        "m53_name" to "Copia de Seguridad y Extractor de APKs",
        "m54_clean_own" to "Limpiar cachés propias",
        "m54_cleaning" to "Limpiando…",
        "m54_deep_clean" to "Limpieza profunda de cachés",
        "m54_desc" to "Limpie sus cachés, recorte las del sistema y limpie a fondo las cachés de apps (root).",
        "m54_freed" to "Liberado",
        "m54_name" to "Limpiador Profundo de Almacenaje y Caché",
        "m54_own" to "Cachés de MSI",
        "m54_own_cache" to "Tamaño de la caché propia",
        "m54_system" to "Sistema (root)",
        "m54_system_hint" to "pm trim-caches libera caché de todas las apps; la limpieza profunda borra /data/data/*/cache.",
        "m54_trim_caches" to "Recortar cachés (pm)",
        "m55_desc" to "Digests MD5 / SHA-1 / SHA-256 con comparación contra el hash esperado.",
        "m55_expected" to "Digest esperado",
        "m55_file" to "Archivo",
        "m55_hash" to "Calcular hash",
        "m55_match" to "EL HASH COINCIDE",
        "m55_mismatch" to "EL HASH NO COINCIDE",
        "m55_name" to "Verificador de Hash ISO y Binarios",
        "m55_quick" to "Selección rápida",
        "m55_verify" to "Verificar",
        "m56_desc" to "Localice los archivos más grandes que consumen su almacenamiento.",
        "m56_files" to "archivos",
        "m56_min_size" to "Tamaño mín. (MB)",
        "m56_name" to "Cazador de Devoradores de Almacenaje",
        "m56_none" to "No hay archivos por encima del umbral",
        "m56_results" to "Archivos más grandes",
        "m56_root" to "Raíz del escaneo",
        "m56_scan" to "Cazar",
        "m56_total" to "Total",
        "m57_archive_path" to "Ruta del archivo",
        "m57_create" to "Crear archivo",
        "m57_desc" to "Cree y extraiga archivos .zip y .tar.gz con registro de progreso.",
        "m57_extract" to "Extraer",
        "m57_name" to "Nombre del archivo",
        "m57_pack" to "Empaquetar",
        "m57_source_dir" to "Directorio de origen",
        "m57_unpack" to "Desempaquetar",
        "m57_working" to "Trabajando…",
        "m58_active" to "Transferencias activas y recientes",
        "m58_add" to "Añadir transferencia",
        "m58_desc" to "Encole descargas con progreso en vivo por transferencia (2 simultáneas).",
        "m58_enqueue" to "Encolar",
        "m58_hint" to "Los archivos van a /sdcard/MSI/Downloads.",
        "m58_name" to "Cola de Descargas y Rastreador de Transferencias",
        "m58_none" to "Aún no hay transferencias",
        "m59_clear" to "Vaciar historial",
        "m59_desc" to "Vigile el portapapeles, guarde el historial y cree snippets reutilizables.",
        "m59_history" to "Historial del portapapeles",
        "m59_name" to "Historial de Portapapeles y Snippets",
        "m59_none" to "Nada copiado todavía",
        "m59_paused" to "En pausa",
        "m59_save_snippet" to "Guardar snippet",
        "m59_snippets" to "Snippets",
        "m59_watching" to "Vigilando el portapapeles",
        "m60_desc" to "Informe diagnóstico completo: hardware, memoria, almacenamiento, logcat y dmesg.",
        "m60_generate" to "Generar informe",
        "m60_name" to "Exportador de Registros y Diagnóstico del Sistema",
        "m60_preview" to "Vista previa",
        "m60_report" to "Informe",
        "m60_save" to "Guardar en Descargas",
        "m61_confirm" to "La partición system se remonta rw y se respalda Roboto-Regular. ¿Continuar?",
        "m61_current" to "Fuentes actuales (muestra)",
        "m61_desc" to "Instale una TTF personalizada en /system/fonts con copia y restauración.",
        "m61_font_path" to "Ruta TTF",
        "m61_hint" to "La fuente se copia como /system/fonts/MSICustom-Regular.ttf (644).",
        "m61_install" to "Instalar fuente",
        "m61_install_btn" to "Instalar como MSICustom",
        "m61_name" to "Personalizador de Fuentes del Sistema (Root)",
        "m61_not_ttf" to "El archivo seleccionado no es .ttf",
        "m61_restore" to "Restaurar",
        "m61_restore_btn" to "Quitar fuente personalizada",
        "m62_confirm" to "La bootanimation actual se respalda en /sdcard/MSI. ¿Continuar?",
        "m62_current" to "Medios actuales",
        "m62_desc" to "Valide e instale bootanimation.zip en /system/media.",
        "m62_hint" to "Un bootanimation.zip debe contener desc.txt y carpetas part.",
        "m62_install" to "Instalar",
        "m62_install_btn" to "Instalar bootanimation",
        "m62_invalid_zip" to "Inválido: falta desc.txt",
        "m62_name" to "Personalizador de Bootanimation (Root)",
        "m62_no_file" to "Archivo no encontrado",
        "m62_restore" to "Restaurar",
        "m62_restore_btn" to "Restaurar copia",
        "m62_valid_zip" to "Estructura válida (desc.txt presente)",
        "m62_validate" to "Validar zip",
        "m62_zip_path" to "Ruta de bootanimation.zip",
        "m63_action" to "Acción del mosaico",
        "m63_action_desc" to "Abre la sesión del terminal Alpine",
        "m63_added" to "añadido al panel",
        "m63_desc" to "Mosaico QS que abre el terminal MSI al instante desde el panel.",
        "m63_howto" to "Despliegue el panel, edite los mosaicos y arrastre 'MSI Terminal' a su sitio.",
        "m63_name" to "Integración de Mosaico de Ajustes Rápidos",
        "m63_not_added" to "aún no añadido",
        "m63_notification" to "Notificaciones",
        "m63_open_terminal" to "Simular toque del mosaico",
        "m63_state" to "Estado del mosaico",
        "m63_test_notification" to "Enviar notificación de prueba",
        "m63_tile" to "Mosaico",
        "m64_clear" to "Borrar crashes",
        "m64_crashes" to "Crashes registrados",
        "m64_desc" to "Recoja crashes, logcat y diagnósticos en un zip compartible.",
        "m64_hint" to "El zip contiene registros de crashes, logcat, dmesg y el informe diagnóstico.",
        "m64_name" to "Soporte de Depuración y Empaquetador de Crashes",
        "m64_none" to "Sin crashes registrados",
        "m64_package" to "Paquete de soporte",
        "m64_view" to "Ver el último",
        "m64_zip" to "Crear zip de depuración",
        "m65_caches" to "Topología de caché",
        "m65_cores" to "Núcleos",
        "m65_desc" to "SoC, topología CPU, cachés, GPU, memoria y almacenamiento en un panel.",
        "m65_device" to "Dispositivo",
        "m65_freqs" to "Frecuencias en vivo",
        "m65_name" to "Perfilador Avanzado de Hardware",
        "m65_no_caches" to "sysfs de caché no expuesto",
        "m65_soc" to "SoC",
        "m66_available" to "Disponible",
        "m66_desc" to "Memoria, swap y zram en vivo con gráfico de historial.",
        "m66_details" to "Detalles",
        "m66_name" to "Monitor en Tiempo Real de RAM y Swap",
        "m66_ram" to "RAM",
        "m66_total" to "Total",
        "m66_used" to "Usada",
        "m67_all" to "Todas",
        "m67_apps" to "Paquetes",
        "m67_desc" to "Cada paquete instalado con copia del nombre en un solo toque.",
        "m67_installed_at" to "Instalado",
        "m67_name" to "Inspector de Paquetes Instalados",
        "m67_search" to "Buscar apps",
        "m67_system" to "Solo sistema",
        "m68_desc" to "Tabla de procesos en vivo con memoria RSS y eliminación con root.",
        "m68_kill" to "Matar",
        "m68_name" to "Gestor de Procesos en Segundo Plano",
        "m68_processes" to "Procesos",
        "m69_desc" to "Logcat en vivo con filtros de nivel y texto (root para todas las apps).",
        "m69_empty" to "Sin transmisión",
        "m69_filter" to "Filtro",
        "m69_hint" to "el modo root lee el buffer global; el modo usuario solo muestra los logs de MSI.",
        "m69_name" to "Flujo en Vivo del Logcat del Sistema",
        "m69_start" to "Iniciar flujo",
        "m70_desc" to "Tabla de montajes completa con tipos, flags RO y barras de uso.",
        "m70_mounts" to "Montajes",
        "m70_name" to "Puntos de Montaje y Uso de Disco",
        "m70_none" to "df no disponible",
        "m71_battery" to "Batería",
        "m71_desc" to "Zonas térmicas, temperatura de batería y tendencia de throttling.",
        "m71_hint" to "Los nombres de zona los da el kernel; ≥ 60 °C indica territorio de throttling severo.",
        "m71_name" to "Inspector Térmico de CPU",
        "m71_zones" to "Zonas térmicas",
        "m72_desc" to "Cronómetro de precisión con vueltas y temporizador con alarma.",
        "m72_lap" to "Vuelta",
        "m72_name" to "Temporizador, Cronómetro y Cuentakilómetros",
        "m72_stopwatch" to "Cronómetro",
        "m72_timer" to "Temporizador",
        "m73_desc" to "Cambie toda la interfaz entre TR, EN, ES, FR e IT al instante.",
        "m73_hint" to "El cambio es instantáneo — sin reinicios ni recargas.",
        "m73_name" to "Motor Multi-Idioma",
        "m73_status" to "Estado del motor",
        "m74_active" to "activo",
        "m74_classic" to "Utilidad Clásica",
        "m74_desc" to "Tres temas en vivo: Material 3, Hacker/Ciberpunk y Utilidad Clásica.",
        "m74_name" to "Motor Dinámico de Temas UI",
        "m74_preview" to "Vista previa en vivo",
        "m74_select" to "Tema",
        "m75_desc" to "Instale, actualice, verifique o elimine el rootfs Alpine y vigile el motor.",
        "m75_hint" to "El minirootfs viene incluido para instalación offline; la actualización trae la 3.21.x más reciente.",
        "m75_install" to "Instalar rootfs",
        "m75_log" to "Registro del motor",
        "m75_name" to "Estado del Bootstrap del Rootfs Alpine",
        "m75_not_ready" to "NO INSTALADO",
        "m75_path" to "Ubicación",
        "m75_ready" to "LISTO",
        "m75_remove" to "Eliminar rootfs",
        "m75_status" to "Estado del rootfs",
        "m75_update" to "Redescargar y actualizar",
        "m75_verified" to "SHA-256 verificado",
        "m76_check" to "Comprobar binario",
        "m76_desc" to "Compare el tipo de máquina ELF de un binario con las ABIs de este dispositivo.",
        "m76_device" to "ABIs del dispositivo",
        "m76_hint" to "Útil antes de ejecutar binarios descargados en dispositivos y emuladores exóticos.",
        "m76_match" to "Comparar",
        "m76_name" to "Comparador de Arquitectura ELF Nativa",
        "m76_will_run" to "Este binario funcionará en este dispositivo",
        "m76_wont_run" to "Arquitectura incompatible — NO funcionará",
        "m77_app" to "App",
        "m77_available" to "actualización disponible",
        "m77_check" to "Chequeo de actualizaciones",
        "m77_checking" to "Comprobando…",
        "m77_desc" to "Info de versión MSI, estado del motor y chequeo de manifiesto remoto.",
        "m77_hint" to "Manifiesto remoto: github.com/finndev/msi-manifest (version.json).",
        "m77_module_versions" to "Módulos del motor",
        "m77_modules" to "Módulos",
        "m77_name" to "Comprobador de Actualizaciones y Versiones",
        "m77_offline" to "Sin red o manifiesto no disponible",
        "m77_parse_error" to "Error de formato del manifiesto",
        "m77_up_to_date" to "Actualizado",
        "m78_desc" to "El centro de control MSI v4.0.0: visión general del sistema y puerta a los 78 módulos.",
        "m78_name" to "Panel de Control del Sistema Maestro",
        "nav_home" to "Inicio",
        "nav_modules" to "Módulos",
        "nav_settings" to "Ajustes",
        "nav_terminal" to "Terminal",
        "no" to "No",
        "ob_continue" to "Continuar",
        "ob_lang_desc" to "Toda la interfaz — los 78 módulos, menús y botones — cambiará al instante.",
        "ob_lang_note" to "Puede cambiar el idioma más tarde en el módulo 73.",
        "ob_lang_title" to "Por favor, seleccione su idioma",
        "ob_perm_allfiles" to "Acceso a todos los archivos (Android 11+)",
        "ob_perm_desc" to "MSI necesita acceso al almacenamiento para gestionar archivos, ISO, copias y registros. Los permisos se solicitan ahora, antes que nada.",
        "ob_perm_grant" to "Conceder permisos",
        "ob_perm_granted" to "concedido",
        "ob_perm_missing" to "falta",
        "ob_perm_read" to "Leer almacenamiento externo",
        "ob_perm_skip_warn" to "Algunos módulos estarán limitados sin acceso al almacenamiento",
        "ob_perm_write" to "Escribir almacenamiento externo",
        "ob_skip" to "Omitir",
        "ob_start" to "Iniciar MSI",
        "ob_welcome" to "Bienvenido a MSI",
        "open" to "Abrir",
        "open_module" to "Abrir módulo",
        "output" to "Salida",
        "refresh" to "Actualizar",
        "reset" to "Restablecer",
        "root_hint" to "concede acceso root (Magisk / KernelSU / APatch) para habilitar este módulo",
        "root_required" to "Se requiere root",
        "run" to "Ejecutar",
        "save" to "Guardar",
        "scan" to "Escanear",
        "scanning" to "Escaneando…",
        "search_modules" to "Buscar en 78 módulos…",
        "share" to "Compartir",
        "size" to "Tamaño",
        "start" to "Iniciar",
        "stop" to "Detener",
        "version" to "Versión",
        "yes" to "Sí",
    )
}
