package com.finndev.master.system.inspector.core

/** Generated MSI string table (Turkish) — 728 keys. */
object LocDataTr {
    val data: Map<String, String> = mapOf(
        "abort" to "İptal et",
        "about" to "Hakkında",
        "about_modules_count" to "{0} modül — tümü tam işlevsel",
        "actions" to "Eylemler",
        "app_tagline" to "Ana Sistem Denetçisi — Master System Inspector",
        "apply" to "Uygula",
        "cancel" to "Vazgeç",
        "cat_all" to "Tümü",
        "cat_network" to "Ağ, Güvenlik ve Teşhis",
        "cat_root" to "Root ve Çekirdek Ayarları",
        "cat_storage" to "Depolama, ISO ve Dosyalar",
        "cat_system" to "Sistem Profilleme ve Araçlar",
        "cat_terminal" to "Terminal, RootFS ve Betikler",
        "check_updates" to "Güncellemeleri denetle",
        "clear" to "Temizle",
        "confirm" to "Onayla",
        "copy" to "Kopyala",
        "current_language" to "Geçerli dil",
        "dash_all_modules" to "Tüm modüller (1–78)",
        "dash_android" to "Android",
        "dash_categories" to "Kategoriler",
        "dash_quick" to "Hızlı erişim",
        "dash_ram" to "Boş RAM",
        "dash_ram_sub" to "toplam {0}",
        "dash_root" to "Root",
        "dash_root_no" to "Root yok",
        "dash_root_unknown" to "denetleniyor…",
        "dash_root_yes" to "Rootlu",
        "dash_storage" to "Boş depolama",
        "dash_storage_free" to "boş",
        "dash_storage_sub" to "{0} içinde",
        "delete" to "Sil",
        "download" to "İndir",
        "downloading" to "İndiriliyor…",
        "empty_list" to "Burada henüz bir şey yok",
        "error" to "Hata",
        "export" to "Dışa aktar",
        "filter" to "Filtrele",
        "input" to "Girdi",
        "m01_desc" to "Derin root algılama: Magisk, KernelSU, APatch yöneticileri, su ikilileri ve kanıt günlüğü.",
        "m01_evidence" to "Algılama kanıtları",
        "m01_manager" to "Root yöneticisi",
        "m01_name" to "Gelişmiş Root Denetçisi",
        "m01_no_evidence" to "Root kanıtı bulunamadı",
        "m01_su_path" to "su ikili yolu",
        "m02_desc" to "SELinux'u root ile Enforcing/Permissive arasında okuyun ve değiştirin.",
        "m02_name" to "SELinux Kip Değiştirici",
        "m02_set_enforcing" to "Enforcing yap",
        "m02_set_permissive" to "Permissive yap",
        "m02_warn" to "Permissive kipi güvenliği düşürür. Yalnızca hata ayıklama için kullanın.",
        "m03_desc" to "Sistem özelliklerini root yazma desteğiyle okuyun, arayın ve ekleyin.",
        "m03_edit" to "Yeni özellik ekle",
        "m03_hint" to "Özellikler /system/build.prop'a eklenir (sistem rw bağlanır).",
        "m03_loaded" to "Yüklenen özellikler",
        "m03_name" to "Build.prop Canlı Düzenleyici",
        "m04_desc" to "/system/etc/init.d başlangıç betiklerini root ile listeyin, çalıştırın, kurun.",
        "m04_found" to "Kurulu betikler",
        "m04_hint" to "Betik kabuk tırnaklamasından kurtulmak için base64 ile kodlanır; sonraki açılışta çalışır.",
        "m04_install" to "Kur",
        "m04_name" to "Init.d Betik Çalıştırıcı",
        "m04_new" to "Yeni betik kur",
        "m04_none" to "init.d betiği yok (init.d desteği eksik olabilir)",
        "m04_script" to "Betik içeriği",
        "m05_current" to "Geçerli bağlama bayrakları",
        "m05_desc" to "/system ve /vendor bölümlerini root ile oku-yaz veya salt-okunur bağlayın.",
        "m05_hint" to "System-as-root cihazlarda bunun yerine / bağlama noktası kullanılır.",
        "m05_name" to "Sistem Bölümü Yeniden Bağlayıcı",
        "m05_none" to "system/vendor girdisi bulunamadı",
        "m05_remount_ro" to "RO bağla",
        "m05_remount_rw" to "RW bağla",
        "m06_available" to "Kullanılabilir valiler",
        "m06_current" to "Çekirdek durumu",
        "m06_desc" to "Çekirdek başına frekans ve vali profili; valileri anında değiştirin.",
        "m06_name" to "CPU Vali Profilcisi",
        "m06_no_governors" to "Bu çekirdek vali listesini açmıyor",
        "m07_cores" to "Çekirdekler",
        "m07_cpu0_note" to "CPU0 açılış çekirdeğidir ve kapatılamaz.",
        "m07_desc" to "CPU çekirdeklerini açın/kapatın ve min/maks frekansları sıkıştırın.",
        "m07_freq_limit" to "Frekans sınırları",
        "m07_limit_hint" to "Sınırlar donanım maksimumunun yüzdesi olarak tüm cpufreq ilkelerine uygulanır.",
        "m07_max" to "En yüksek frekans",
        "m07_min" to "En düşük frekans",
        "m07_name" to "CPU Çekirdek Hotplug ve Frekans Sınırlayıcı",
        "m07_offline" to "Kapat",
        "m07_online" to "Aç",
        "m08_current" to "Geçerli LMK durumu",
        "m08_desc" to "lowmemorykiller minfree eşiklerini okuyun ve ayarlayın.",
        "m08_edit" to "minfree ayarla",
        "m08_hint" to "Değerler öncelik başına kB cinsindendir, virgülle ayrılır (6 seviye).",
        "m08_lmk_missing" to "LMK açık değil (modern çekirdekler PSI/lmkd kullanır)",
        "m08_name" to "Düşük Bellek Katili (LMK) Ayarlayıcı",
        "m09_cycles" to "Döngü sayısı",
        "m09_cycles_na" to "yalnızca Android 14+",
        "m09_desc" to "Batarya sağlığı, sıcaklığı, döngüleri ve şarj eşiği denetimi.",
        "m09_health" to "Sağlık",
        "m09_level" to "Seviye",
        "m09_name" to "Batarya Sağlığı ve Şarj Yöneticisi",
        "m09_now" to "Geçerli batarya",
        "m09_tech" to "Teknoloji",
        "m09_temp" to "Sıcaklık",
        "m09_threshold" to "Şarj eşiği",
        "m09_threshold_current" to "Geçerli eşik",
        "m09_threshold_hint" to "örn. 80, bataryayı ömür için %20-80 aralığında tutar (destekleyen cihazlar).",
        "m09_threshold_na" to "çekirdek desteklemiyor",
        "m09_threshold_new" to "Yeni eşik (%)",
        "m09_voltage" to "Gerilim",
        "m10_current" to "Geçerli ekran geçersiz kılmaları",
        "m10_density" to "Yoğunluk (DPI)",
        "m10_desc" to "wm size / wm density ile ekran çözünürlüğünü ve yoğunluğu geçersiz kılın.",
        "m10_name" to "Ekran Çözünürlüğü ve DPI Değiştirici",
        "m10_size" to "Çözünürlük",
        "m10_warn" to "Aşırı değerler arayüzü okunmaz hale getirebilir — Sıfırla varsayılana döner.",
        "m11_apps" to "Kurulu uygulamalar",
        "m11_desc" to "Sistem paketlerini pm ile dondurun, gizleyin, kaldırın (user 0) ve geri yükleyin.",
        "m11_enable" to "Etkinleştir",
        "m11_freeze" to "Dondur",
        "m11_hint" to "Kaldırma 'pm uninstall --user 0' kullanır — Etkinleştir ile geri alınabilir; APK diskte kalır.",
        "m11_name" to "Gereksiz Sistem Uygulaması Dondurucu",
        "m11_restore" to "Paket geri yükle",
        "m11_restore_pkg" to "paket adı",
        "m11_unhide" to "Göster",
        "m11_uninstall" to "Kaldır",
        "m12_count" to "Bu cihazdaki sensörler",
        "m12_desc" to "Jiroskop, ivmeölçer, manyetometre ve daha fazlasının canlı akışı.",
        "m12_name" to "Canlı Donanım Sensörü Akışı",
        "m12_power" to "Güç tüketimi",
        "m12_range" to "En yüksek aralık",
        "m12_resolution" to "Çözünürlük",
        "m13_buffer" to "Tampon anlık görüntüsü",
        "m13_desc" to "Çekirdek ring tamponunu okuyun ve dmesg -w ile canlı izleyin.",
        "m13_empty" to "Tampon boş veya okunamıyor",
        "m13_follow" to "Takibe başla",
        "m13_live" to "Canlı takip",
        "m13_name" to "Çekirdek Günlüğü (dmesg) Okuyucu",
        "m13_read" to "Tamponu oku (root)",
        "m14_awake" to "Uyanık süre",
        "m14_boot_id" to "Açılış kimliği",
        "m14_deep" to "Derin uyku",
        "m14_desc" to "Çalışma süresi, derin uyku payı ve açılış olay zaman çizelgesi.",
        "m14_name" to "Açılış Aşaması ve Başlangıç Analizcisi",
        "m14_no_log" to "Açılış olayı yok",
        "m14_stages" to "Açılış olayları",
        "m14_stats" to "Açılış istatistikleri",
        "m14_uptime" to "Açılıştan bu yana",
        "m15_cores" to "İş parçacığı",
        "m15_desc" to "SHA-256 CPU stres kıyaslaması (tek/çok çekirdek) ve bellek bant genişliği testi.",
        "m15_hint" to "2 sn tek çekirdek, 2 sn tüm çekirdekler SHA-256 yükü ve 96 MB bellek geçişi çalıştırır.",
        "m15_mem" to "Bellek",
        "m15_multi" to "Çok çekirdek",
        "m15_name" to "CPU ve RAM Kıyaslama Testi",
        "m15_running" to "Kıyaslanıyor…",
        "m15_scores" to "Kıyaslama puanları",
        "m15_single" to "Tek çekirdek",
        "m16_apk_update" to "apk update && upgrade",
        "m16_bootstrapping" to "hazırlanıyor",
        "m16_desc" to "Uygulama deposunda gerçek Alpine Linux rootfs — tam apk paket yönetimiyle.",
        "m16_exited" to "sonlandı",
        "m16_hint" to "Deneyin: apk update • apk add python3 • cat /etc/alpine-release",
        "m16_idle" to "boşta",
        "m16_input_hint" to "komut yazıp Gönder'e basın",
        "m16_name" to "Gerçek Alpine Linux PRoot Terminali",
        "m16_restart" to "Oturumu yeniden başlat",
        "m16_running" to "çalışıyor",
        "m16_share_log" to "Dökümü paylaş",
        "m16_state" to "Oturum",
        "m16_stop" to "Oturumu durdur",
        "m17_clone" to "Depoyu klonla (depth 1)",
        "m17_desc" to "com.termux'u algılar, başlatır ve Alpine git ile Git depolarını klonlar.",
        "m17_git" to "Git klonlayıcı",
        "m17_git_hint" to "Depolar, gelen Alpine git ile /sdcard/MSI/GitRepos içine klonlanır.",
        "m17_installed" to "kurulu",
        "m17_launch" to "Termux'u başlat",
        "m17_name" to "Termux Entegrasyonu ve Git Klonlayıcı",
        "m17_not_installed" to "kurulu değil",
        "m18_arch" to "Mimari",
        "m18_config" to "Makine yapılandırması",
        "m18_create_disk" to "qcow2 disk oluştur",
        "m18_desc" to "Alpine rootfs içinde QEMU (x86_64 / i386 / aarch64) makineleri kurun ve çalıştırın.",
        "m18_disk" to "Disk boyutu (GB)",
        "m18_hint" to "QEMU seri konsolla başsız çalışır; ISO yolu /sdcard altındaki bir dosyayı gösterir.",
        "m18_install" to "QEMU kur (apk)",
        "m18_launch" to "Terminalde başlat",
        "m18_name" to "QEMU Çok Mimari Emülatörü",
        "m18_ram" to "Bellek",
        "m19_bash_note" to "bash, Alpine rootfs içine gerektiğinde kurulur (apk add bash).",
        "m19_desc" to ".sh betiklerini Alpine /bin/sh, Alpine bash veya Android sh ile canlı çıktıyla çalıştırın.",
        "m19_engine" to "Betik motoru",
        "m19_name" to "Bash ve Kabuk Betiği Çalıştırıcı",
        "m19_running" to "Çalışıyor…",
        "m19_script" to "Betik",
        "m20_args" to "Argümanlar",
        "m20_compat" to "Cihaz uyumluluğu",
        "m20_compat_no" to "uyumsuz ABI",
        "m20_compat_yes" to "uyumlu",
        "m20_desc" to "ARM/x86 ikililerini root ile inceleyin ve doğrudan çalıştırın.",
        "m20_hint" to "chmod +x otomatik uygulanır; ikililer su ile yürütülür.",
        "m20_inspect" to "ELF incele",
        "m20_name" to "Yerel ELF İkili Çalıştırıcı",
        "m20_not_elf" to "ELF dosyası değil",
        "m20_path" to "İkili yolu",
        "m20_pick" to "İkili dosya",
        "m21_code" to "Kod",
        "m21_desc" to "Python 3 ve Lua 5.4 betiklerini Alpine rootfs içinde çalıştırın — gerçek yorumlayıcılar.",
        "m21_in_terminal" to "Terminalde etkileşimli aç",
        "m21_install" to "apk ile kur",
        "m21_installed" to "hazır",
        "m21_lang" to "Dil",
        "m21_name" to "Python ve Lua Yorumlayıcı",
        "m21_not_installed" to "henüz kurulu değil",
        "m21_running" to "Yürütülüyor…",
        "m21_runtime" to "Çalışma zamanı",
        "m22_analyze" to "Analiz et",
        "m22_desc" to "Tam ELF başlık incelemesi: sınıf, endian, makine, giriş noktası, PT_INTERP.",
        "m22_invalid" to "Geçersiz ELF",
        "m22_list" to "Dizini listele",
        "m22_listing" to "Dizin listesi",
        "m22_machine" to "Makine",
        "m22_name" to "ELF İkili Derin Analizcisi",
        "m22_no_dir" to "Dizin okunamıyor",
        "m22_pick" to "Bir ELF dosyası",
        "m22_type" to "Tür",
        "m23_desc" to "root ile herhangi bir dosyayı chmod / chown yapın, canlı stat görünümüyle.",
        "m23_mode" to "Kip (sekizlik)",
        "m23_name" to "Dosya İzin Yöneticisi",
        "m23_stat" to "Geçerli durum",
        "m24_custom" to "Özel PATH girdileri",
        "m24_desc" to "MSI kabuk PATH'ini inceleyin ve özel dizinler ekleyin.",
        "m24_extra" to "Ek dizinler (iki nokta ayrıklı)",
        "m24_hint" to "Her MSI kabuk oturumuna ve PRoot ortamına uygulanır.",
        "m24_name" to "Ortam PATH Yöneticisi",
        "m25_applets" to "Uygulamacıklar",
        "m25_desc" to "busybox algıla, uygulamacıklarını listele ve Alpine ile busybox-static kur.",
        "m25_detect" to "Algılama",
        "m25_install" to "busybox-static kur",
        "m25_install_btn" to "Kur",
        "m25_install_hint" to "Statik ikili, Alpine paket yöneticisi ile /sdcard/MSI/busybox'a aktarılır.",
        "m25_name" to "Busybox Entegrasyon ve Doğrulayıcı",
        "m25_not_found" to "bulunamadı",
        "m26_actions" to "Acil eylemler",
        "m26_confirm" to "Bu komut çalıştırılsın mı?",
        "m26_custom" to "Özel komut (su)",
        "m26_desc" to "Seçilmiş acil komutlar: izin düzelt, önbellek kırp, yeniden bağla, yeniden başlat.",
        "m26_name" to "Acil Kurtarma Konsolu",
        "m27_builder" to "Makro oluşturucu",
        "m27_desc" to "Kabuk komutlarını gecikmelerle zincirleyip tek dokunuşluk makrolar haline getirin.",
        "m27_format" to "Satır başına bir adım: komut|gecikme_ms — su için '#root ' öneki kullanın",
        "m27_name" to "Makro adı",
        "m27_none" to "Henüz makro yok",
        "m27_saved" to "Kayıtlı makrolar",
        "m27_steps" to "Adımlar",
        "m28_current" to "Geçerli oturum dökümü",
        "m28_desc" to "Terminal dökümünü ve oturum günlüklerini .txt / .log olarak kaydedin.",
        "m28_hint" to "Dosyalar uygulama içi günlüklerde tutulur ve her yere paylaşılabilir.",
        "m28_lines" to "Satır",
        "m28_name" to "Terminal Çıktı Günlük Aktarıcı",
        "m28_none" to "Henüz günlük yok",
        "m28_saved" to "Kayıtlı günlükler",
        "m29_desc" to "Anında markdown önizlemeli notlar; dahili depoda saklanır.",
        "m29_edit" to "Düzenle",
        "m29_hint" to "# başlıklar, **kalın**, `kod`, listeler ve kod blokları desteklenir.",
        "m29_name" to "Çevrimdışı Markdown Not Defteri",
        "m29_new" to "Yeni not",
        "m29_none" to "Henüz not yok",
        "m29_notes" to "Notlar",
        "m29_preview" to "Önizleme",
        "m30_desc" to "Herhangi bir barkod biçimini tarayın ve dışa aktarılabilir QR kodlar üretin.",
        "m30_generate" to "Üretici",
        "m30_generate_btn" to "QR üret",
        "m30_name" to "QR Kod ve Barkod Tarayıcı",
        "m30_result" to "Sonuç",
        "m30_save" to "İndirilenlere kaydet",
        "m30_scan" to "Tarayıcı",
        "m30_scan_btn" to "Barkod tara",
        "m30_scan_cancel" to "Tarama iptal edildi",
        "m31_bytes" to "Bayt",
        "m31_desc" to "Metni Base64, onaltılık ve ikili arasında dönüştürün — artı dosya karması.",
        "m31_file" to "Dosya kipi (≤ 8 MB)",
        "m31_file_b64" to "Dosyayı Base64'e çevir",
        "m31_file_limit" to "Dosya çok büyük veya yok (sınır 8 MB)",
        "m31_invalid_b64" to "Geçersiz Base64 girdisi",
        "m31_invalid_bin" to "Geçersiz ikili girdisi",
        "m31_invalid_hex" to "Geçersiz hex girdisi",
        "m31_mode" to "Dönüştürme kipi",
        "m31_name" to "Base64, Hex ve İkili Kodlayıcı",
        "m32_desc" to "JSON ve XML belgelerini doğrulayın ve güzelleştirin.",
        "m32_format" to "Biçimlendir ve doğrula",
        "m32_invalid" to "Geçersiz",
        "m32_invalid_json" to "Geçersiz JSON",
        "m32_invalid_xml" to "Geçersiz XML",
        "m32_mode" to "Biçim",
        "m32_name" to "JSON ve XML Biçemleyici",
        "m32_valid" to "Geçerli belge",
        "m33_add" to "Kayıt ekle",
        "m33_desc" to "PBKDF2 anahtar türetmeli AES-256-GCM kasa — tamamen çevrimdışı.",
        "m33_empty" to "Kasa boş",
        "m33_entries" to "Kayıtlar",
        "m33_gen" to "Üret",
        "m33_hint" to "Kasa AES-GCM ile şifrelenir; anahtar cihazdan asla çıkmaz.",
        "m33_lock" to "Kasayı kilitle",
        "m33_master" to "Ana parola",
        "m33_name" to "Çevrimdışı Şifreli Parola Yöneticisi",
        "m33_pass" to "Parola",
        "m33_short_pwd" to "Ana parola en az 4 karakter olmalı",
        "m33_title" to "Başlık",
        "m33_unlock" to "Kasa",
        "m33_unlock_btn" to "Kasayı aç / oluştur",
        "m33_user" to "Kullanıcı adı / e-posta",
        "m33_wrong_pwd" to "Ana parola hatalı",
        "m34_desc" to "/24 alt ağını canlı istemciler için tarayın ve MAC adreslerini çözün.",
        "m34_found" to "Bulunan cihazlar",
        "m34_hint" to "254 istemci paralel yoklanır; MAC ARP tablosundan gelir.",
        "m34_name" to "LAN IP ve MAC Cihaz Tarayıcı",
        "m34_none" to "Cihaz bulunamadı",
        "m34_scan" to "Alt ağı tara",
        "m34_scanning" to "Taranıyor…",
        "m34_subnet" to "Alt ağ (x.x.x.)",
        "m35_closed" to "kapalı",
        "m35_desc" to "Paralel soketlerle herhangi bir sunucunun TCP ve UDP portlarını denetleyin.",
        "m35_filtered" to "yanıt yok",
        "m35_host" to "Sunucu",
        "m35_name" to "Port Tarayıcı (TCP/UDP)",
        "m35_none" to "Önce bir hedef tarayın",
        "m35_open" to "AÇIK",
        "m35_ports" to "Portlar",
        "m35_target" to "Hedef",
        "m35_udp_hint" to "UDP 'yanıt yok' genellikle açık-veya-filtreli demektir (ICMP hatası yok).",
        "m36_count" to "Adet",
        "m36_desc" to "Yanıt başına gecikme grafiği ve min/ort/maks istatistikli sürekli ping.",
        "m36_name" to "Gelişmiş Ping ve Gecikme İzleyici",
        "m36_start" to "Ping başlat",
        "m36_target" to "Ping hedefi",
        "m37_adguard" to "AdGuard (reklam engelleme)",
        "m37_auto" to "Otomatik (fırsatçı)",
        "m37_cloudflare" to "Cloudflare (1.1.1.1)",
        "m37_current" to "Geçerli Özel DNS",
        "m37_custom" to "Özel ana makine adı",
        "m37_desc" to "Özel DNS (DoT) ön ayarlarını dayatın: Cloudflare, Google, AdGuard, Quad9.",
        "m37_google" to "Google (8.8.8.8)",
        "m37_hint" to "Android Özel DNS (TLS üzerinden), ayarlar sağlayıcısı aracılığıyla uygulanır (root).",
        "m37_name" to "Özel DNS Zorlayıcı (Root)",
        "m37_off" to "Özel DNS'i kapat",
        "m37_presets" to "Ön ayarlar",
        "m37_quad9" to "Quad9 (güvenlik)",
        "m38_add_rule" to "Kural ekle",
        "m38_allow" to "İzin ver (kaldır)",
        "m38_block" to "Portu engelle",
        "m38_desc" to "iptables zincirlerini inceleyin ve root ile port engelleme kuralları ekleyin/kaldırın.",
        "m38_hint" to "Kurallar seçilen zincirde REJECT kullanır; varsa nftables kuralları gösterilir.",
        "m38_ipt_unavailable" to "iptables kullanılamıyor veya engelli",
        "m38_name" to "Güvenlik Duvarı Kural Yöneticisi",
        "m38_nft" to "nftables",
        "m38_nft_available" to "kullanılabilir",
        "m38_nft_missing" to "kullanılamıyor",
        "m39_desc" to "Uygulamalara eşlenmiş TCP/UDP uç noktalarının canlı netstat tablosu.",
        "m39_hint" to "/proc/net/tcp, tcp6, udp ve udp6 okunur; UID'ler uygulama paketlerine çözülür.",
        "m39_name" to "Etkin Ağ Soketi Denetçisi",
        "m39_none" to "Okunabilir soket yok",
        "m39_sockets" to "Soketler",
        "m39_table" to "Uç nokta tablosu",
        "m40_desc" to "Cloudflare'e karşı gecikme, indirme ve yükleme ölçümü.",
        "m40_down" to "İndirme",
        "m40_hint" to "25 MB indirir ve 10 MB yükler — veri kotanızı gözetin.",
        "m40_latency" to "Gecikme",
        "m40_name" to "İnternet Bant Genişliği Hız Testi",
        "m40_results" to "Sonuçlar",
        "m40_running" to "Öçülüyor…",
        "m40_start" to "Hız testini başlat",
        "m40_up" to "Yükleme",
        "m41_desc" to "Herhangi bir arayüzün MAC adresini rastgele veya özel değerlerle değiştirin.",
        "m41_hint" to "wlan0 değişince Wi-Fi yeniden bağlanmalıdır; bazı sürücüler özel MAC kabul etmez.",
        "m41_iface" to "Arayüz",
        "m41_interfaces" to "Arayüzler",
        "m41_invalid_mac" to "Geçersiz MAC biçimi",
        "m41_name" to "MAC Adresi Sahteciliği (Root)",
        "m41_new_mac" to "Yeni MAC",
        "m41_random" to "Rastgele",
        "m41_spoof" to "Sahte MAC",
        "m42_channel" to "Kanal",
        "m42_congestion" to "Kanal yoğunluğu",
        "m42_current" to "Geçerli bağlantı",
        "m42_desc" to "Sinyal gücü, bağlantı verisi, kanal yoğunluğu ve yakın ağlar.",
        "m42_freq" to "Frekans",
        "m42_grant" to "Konum izni ver",
        "m42_level" to "Seviye",
        "m42_location" to "Konum izni",
        "m42_location_hint" to "Android, tarama sonuçlarını göstermek için konum izni ister.",
        "m42_name" to "Wi-Fi Sinyal ve Kanal Analizcisi",
        "m42_networks" to "Yakın ağlar",
        "m42_rssi" to "Sinyal (RSSI)",
        "m43_cert" to "Sertifika",
        "m43_chain" to "Zincir",
        "m43_cipher" to "Şifre paketi",
        "m43_desc" to "TLS bağlantısı kurun ve sertifika zincirinin tamamını inceleyin.",
        "m43_expired" to "SÜRESİ DOLMUŞ",
        "m43_inspect" to "İncele",
        "m43_name" to "SSL Sertifika ve TLS İncelemesi",
        "m43_status" to "Geçerlilik",
        "m43_target" to "Sunucu (port 443)",
        "m43_tls_version" to "TLS sürümü",
        "m43_valid" to "geçerli",
        "m43_valid_from" to "Geçerlilik başlangıcı",
        "m43_valid_to" to "Geçerlilik sonu",
        "m44_connections" to "İzlenen bağlantılar",
        "m44_desc" to "Bağlantı açılma/kapanma takibi ve uygulama başına trafik sayımı.",
        "m44_hint" to "Çekirdek soket tabloları yoklanır ve farkları çıkarılır; RX/TX deltaları TrafficStats'tan gelir.",
        "m44_log" to "Olay günlüğü",
        "m44_name" to "Paket Koklayıcı ve Trafik Günlükçüsü",
        "m44_start" to "Takide başla",
        "m44_status" to "Durum",
        "m45_ap" to "Tethering durumu",
        "m45_ap_off" to "Hotspot etkin görünmüyor",
        "m45_clients" to "Bağlı istemciler",
        "m45_desc" to "Tethering durumunu ve bağlı hotspot istemcilerini gösterir (ARP temelli).",
        "m45_hint" to "İstemciler, hotspot açıkken ARP tablosundan türetilir.",
        "m45_name" to "Hotspot ve Tethering Denetçisi",
        "m45_no_clients" to "Bağlı istemci yok",
        "m46_answer" to "Cevabınız",
        "m46_bench" to "Test bankı",
        "m46_challenge" to "Sınama",
        "m46_desc" to "Bozuk yerel captcha'lar üretin ve geçiş/kalma oranlarını ölçün.",
        "m46_fail" to "KALDI",
        "m46_log" to "Deneme günlüğü",
        "m46_name" to "Captcha ve Bot Filtre Bankı",
        "m46_new" to "Yeni sınama",
        "m46_pass" to "GEÇTİ",
        "m46_stats" to "Çözülen / kalan",
        "m46_verify" to "Doğrula",
        "m47_desc" to "SecureRandom parolalar, hex belirteçler, UUID'ler ve geçiş cümleleri.",
        "m47_hint" to "Tüm entropi platform SecureRandom üretecinden gelir.",
        "m47_length" to "Uzunluk",
        "m47_mode" to "Kip",
        "m47_name" to "Güvenli Parola ve Belirteç Üreteci",
        "m47_passphrase" to "Geçiş cümlesi",
        "m47_password" to "Parola",
        "m47_regenerate" to "Yeniden üret",
        "m47_results" to "Üretilen",
        "m48_confirm" to "Bu işlem verileri kalıcı olarak yok eder. Devam edilsin mi?",
        "m48_desc" to "Dosyaları silmeden önce çoklu rastgele geçişlerle üzerine yazın.",
        "m48_exists" to "Var",
        "m48_hint" to "1-7 rastgele geçiş + son sıfır geçişi; dizinler özyinelemeli parçalanır.",
        "m48_name" to "Hassas Dosya Parçalayıcı",
        "m48_passes" to "Geçiş",
        "m48_running" to "Parçalanıyor…",
        "m48_shred" to "Kalıcı olarak parçala",
        "m48_target" to "Hedef",
        "m49_desc" to "Canlı eşleşme ve değiştirme önizlemesiyle regex test edin.",
        "m49_input" to "Test metni",
        "m49_matches" to "Eşleşmeler",
        "m49_name" to "Regex Desen Atölyesi",
        "m49_pattern" to "Desen",
        "m49_replace" to "Değiştirme önizlemesi",
        "m49_with" to "Şununla değiştir",
        "m50_add_palette" to "Palete ekle",
        "m50_clear" to "Paleti temizle",
        "m50_current" to "Geçerli renk",
        "m50_desc" to "HEX / RGB kodlu etkileşimli HSL renk seçici ve palet deposu.",
        "m50_dials" to "Kontroller",
        "m50_hex_input" to "HEX'ten",
        "m50_hue" to "Ton",
        "m50_lum" to "Açıklık",
        "m50_name" to "Renk Paleti ve HEX/RGB Seçici",
        "m50_palette" to "Palet",
        "m50_sat" to "Doygunluk",
        "m51_arch" to "Mimari",
        "m51_config" to "İndirme",
        "m51_desc" to "Mimari seçilebilir ISO indirici; sürdürme, ilerleme ve SHA-256 ile.",
        "m51_dest" to "Hedef",
        "m51_name" to "ValiantCore ISO İndirici",
        "m51_sha256" to "SHA-256 hesapla",
        "m51_verify" to " Karma denetimi",
        "m51_verify_hint" to "Hesaplanan özeti güvendiğiniz kaynakla karşılaştırın.",
        "m52_config" to "Sunucu yapılandırması",
        "m52_desc" to "Herhangi bir klasörü, şık dizin listesiyle LAN üzerinden HTTP ile sunun.",
        "m52_dir" to "Paylaşılan dizin",
        "m52_hint" to "Veri senkron ön plan servisi olarak çalışır; medya için Range isteklerini destekler.",
        "m52_log" to "İstek günlüğü",
        "m52_log_empty" to "Henüz istek yok",
        "m52_name" to "Yerel HTTP Dosya Paylaşım Sunucusu",
        "m52_port" to "Port",
        "m52_running" to "çalışıyor",
        "m52_served" to "Sunulan istek",
        "m52_start" to "Sunucuyu başlat",
        "m52_status" to "Durum",
        "m52_stopped" to "durdu",
        "m53_all" to "Toplu yedek",
        "m53_apps" to "Kurulu paketler",
        "m53_backup_user_apps" to "Tüm kullanıcı uygulamalarını yedekle",
        "m53_desc" to "Kurulu APK'ları depoya kopyalayın — tek tek veya tüm kullanıcı uygulamaları.",
        "m53_hint" to "Yedekler /sdcard/MSI/APKBackups içine yazılır.",
        "m53_name" to "APK Yedek ve Paket Çıkarıcı",
        "m54_clean_own" to "Kendi önbelleklerini temizle",
        "m54_cleaning" to "Temizleniyor…",
        "m54_deep_clean" to "Uygulama önbelleklerini derin temizle",
        "m54_desc" to "Kendi önbelleklerini temizle, sistem önbelleklerini kırp, uygulama önbelleklerini derin temizle (root).",
        "m54_freed" to "Boşaltılan",
        "m54_name" to "Derin Depolama ve Önbellek Temizleyici",
        "m54_own" to "MSI önbellekleri",
        "m54_own_cache" to "Kendi önbellek boyutu",
        "m54_system" to "Sistem (root)",
        "m54_system_hint" to "pm trim-caches tüm uygulamaların önbelleğini boşaltır; derin temizlik /data/data/*/cache'i siler.",
        "m54_trim_caches" to "Önbellekleri kırp (pm)",
        "m55_desc" to "Beklenen karma karşılaştırmalı MD5 / SHA-1 / SHA-256 özetleri.",
        "m55_expected" to "Beklenen özet",
        "m55_file" to "Dosya",
        "m55_hash" to "Karma hesapla",
        "m55_match" to "KARMA EŞLEŞİYOR",
        "m55_mismatch" to "KARMA UYUŞMUYOR",
        "m55_name" to "ISO ve İkili Karma Doğrulayıcı",
        "m55_quick" to "Hızlı seçim",
        "m55_verify" to "Doğrula",
        "m56_desc" to "Depolamanızı işgal eden en büyük dosyaları bulun.",
        "m56_files" to "dosya",
        "m56_min_size" to "En az boyut (MB)",
        "m56_name" to "Depolama Yiyen Avcısı",
        "m56_none" to "Eşiği aşan dosya yok",
        "m56_results" to "En büyük dosyalar",
        "m56_root" to "Tarama kökü",
        "m56_scan" to "Avla",
        "m56_total" to "Toplam",
        "m57_archive_path" to "Arşiv yolu",
        "m57_create" to "Arşiv oluştur",
        "m57_desc" to "İlerleme günlüğüyle .zip ve .tar.gz arşivleri oluşturun ve açın.",
        "m57_extract" to "Çıkart",
        "m57_name" to "Arşiv adı",
        "m57_pack" to "Paketle",
        "m57_source_dir" to "Kaynak dizin",
        "m57_unpack" to "Aç",
        "m57_working" to "Çalışılıyor…",
        "m58_active" to "Etkin ve son aktarımlar",
        "m58_add" to "Aktarım ekle",
        "m58_desc" to "Aktarım başına canlı ilerlemeli indirme kuyruğu (2 eşzamanlı).",
        "m58_enqueue" to "Kuyruğa al",
        "m58_hint" to "Dosyalar /sdcard/MSI/Downloads'a iner.",
        "m58_name" to "İndirme Kuyruğu ve Aktarım İzleyici",
        "m58_none" to "Henüz aktarım yok",
        "m59_clear" to "Geçmişi temizle",
        "m59_desc" to "Panoyu izleyin, geçmiş tutun ve yeniden kullanılabilir parçacıklar kaydedin.",
        "m59_history" to "Pano geçmişi",
        "m59_name" to "Pano Geçmişi ve Parçacıklar",
        "m59_none" to "Henüz bir şey kopyalanmadı",
        "m59_paused" to "Duraklatıldı",
        "m59_save_snippet" to "Parçacık kaydet",
        "m59_snippets" to "Parçacıklar",
        "m59_watching" to "Pano izleniyor",
        "m60_desc" to "Tam tanı raporu: donanım, bellek, depolama, logcat ve dmesg.",
        "m60_generate" to "Rapor oluştur",
        "m60_name" to "Sistem Günlüğü ve Tanı Raporu Aktarıcı",
        "m60_preview" to "Önizleme",
        "m60_report" to "Rapor",
        "m60_save" to "İndirilenlere kaydet",
        "m61_confirm" to "Sistem bölümü rw bağlanır ve Roboto-Regular yedeklenir. Devam edilsin mi?",
        "m61_current" to "Geçerli yazı tipleri (örnek)",
        "m61_desc" to "Yedekleme ve geri yüklemeyle /system/fonts içine özel TTF kurun.",
        "m61_font_path" to "TTF yolu",
        "m61_hint" to "Yazı tipi /system/fonts/MSICustom-Regular.ttf olarak kopyalanır (644).",
        "m61_install" to "Yazı tipi kur",
        "m61_install_btn" to "MSICustom olarak kur",
        "m61_name" to "Sistem Yazı Tipi Özelleştirici (Root)",
        "m61_not_ttf" to "Seçilen dosya .ttf değil",
        "m61_restore" to "Geri yükle",
        "m61_restore_btn" to "Özel yazı tipini kaldır",
        "m62_confirm" to "Mevcut açılış animasyonu /sdcard/MSI'ya yedeklenir. Devam edilsin mi?",
        "m62_current" to "Geçerli medya",
        "m62_desc" to "bootanimation.zip'i doğrulayın ve /system/media içine kurun.",
        "m62_hint" to "Bir bootanimation.zip, desc.txt ve part klasörleri içermelidir.",
        "m62_install" to "Kur",
        "m62_install_btn" to "Açılış animasyonunu kur",
        "m62_invalid_zip" to "Geçersiz: desc.txt eksik",
        "m62_name" to "Açılış Animasyonu Özelleştirici (Root)",
        "m62_no_file" to "Dosya bulunamadı",
        "m62_restore" to "Geri yükle",
        "m62_restore_btn" to "Yedeği geri yükle",
        "m62_valid_zip" to "Geçerli açılış animasyonu yapısı (desc.txt var)",
        "m62_validate" to "Zip'i doğrula",
        "m62_zip_path" to "bootanimation.zip yolu",
        "m63_action" to "Döşeme eylemi",
        "m63_action_desc" to "Alpine terminal oturumunu açar",
        "m63_added" to "gölgeye eklendi",
        "m63_desc" to "Gölgeden MSI terminalini anında açan QS döşemesi.",
        "m63_howto" to "Gölgeyi aşağı çekin, döşemeleri düzenleyin ve 'MSI Terminal'i yerine sürükleyin.",
        "m63_name" to "Hızlı Ayarlar Döşemesi Entegrasyonu",
        "m63_not_added" to "henüz eklenmedi",
        "m63_notification" to "Bildirimler",
        "m63_open_terminal" to "Döşeme dokunuşunu taklit et",
        "m63_state" to "Döşeme durumu",
        "m63_test_notification" to "Test bildirimi gönder",
        "m63_tile" to "Döşeme",
        "m64_clear" to "Çöküşleri temizle",
        "m64_crashes" to "Kaydedilen çöküşler",
        "m64_desc" to "Çöküş günlüklerini, logcat'i ve tanıları paylaşılabilir bir zip'te toplayın.",
        "m64_hint" to "Zip; çöküş günlükleri, logcat, dmesg ve tanı raporunu içerir.",
        "m64_name" to "Hata Ayıklama Desteği ve Çöküş Günlüğü Paketleyici",
        "m64_none" to "Çöküş kaydedilmedi",
        "m64_package" to "Destek paketi",
        "m64_view" to "Sonuncuyu görüntüle",
        "m64_zip" to "Hata ayıklama zip'i oluştur",
        "m65_caches" to "Önbellek topolojisi",
        "m65_cores" to "Çekirdek",
        "m65_desc" to "SoC, CPU topolojisi, önbellekler, GPU, bellek ve depolama tek panelde.",
        "m65_device" to "Cihaz",
        "m65_freqs" to "Canlı frekanslar",
        "m65_name" to "Gelişmiş Donanım Profilcisi",
        "m65_no_caches" to "Önbellek sysfs'si açık değil",
        "m65_soc" to "SoC",
        "m66_available" to "Kullanılabilir",
        "m66_desc" to "Geçmiş grafikli canlı bellek, swap ve zram kullanımı.",
        "m66_details" to "Ayrıntılar",
        "m66_name" to "Gerçek Zamanlı RAM ve Swap İzleyici",
        "m66_ram" to "RAM",
        "m66_total" to "Toplam",
        "m66_used" to "Kullanılan",
        "m67_all" to "Tümü",
        "m67_apps" to "Paketler",
        "m67_desc" to "Tek dokunuşla paket adı kopyalama ile tüm kurulu paketler.",
        "m67_installed_at" to "Kurulum",
        "m67_name" to "Kurulu Paket Denetçisi",
        "m67_search" to "Uygulama ara",
        "m67_system" to "Yalnızca sistem",
        "m68_desc" to "RSS bellekli canlı süreç tablosu ve root sonlandırma desteği.",
        "m68_kill" to "Sonlandır",
        "m68_name" to "Arka Plan Süreç Yöneticisi",
        "m68_processes" to "Süreçler",
        "m69_desc" to "Seviye ve metin filtreli canlı logcat akışı (tüm uygulamalar için root).",
        "m69_empty" to "Akış yok",
        "m69_filter" to "Filtre",
        "m69_hint" to "root kipi global tamponu okur; kullanıcı kipi yalnızca MSI'nın günlüklerini gösterir.",
        "m69_name" to "Sistem Logcat Canlı Akışı",
        "m69_start" to "Akışı başlat",
        "m70_desc" to "Dosya sistemi türleri, RO bayrakları ve kullanım çubuklarıyla tam bağlama tablosu.",
        "m70_mounts" to "Bağlamalar",
        "m70_name" to "Bağlama Noktaları ve Disk Kullanımı",
        "m70_none" to "df kullanılamıyor",
        "m71_battery" to "Batarya",
        "m71_desc" to "Termal bölgeler, batarya sıcaklığı ve kısıtlama eğilimi.",
        "m71_hint" to "Bölge adları çekirdekten gelir; ≥ 60 °C ağır kısıtlama bölgesidir.",
        "m71_name" to "CPU Termal Denetçisi",
        "m71_zones" to "Termal bölgeler",
        "m72_desc" to "Tur alabilen hassas kronometre ve alarmlı geri sayım sayacı.",
        "m72_lap" to "Tur",
        "m72_name" to "Zamanlayıcı, Kronometre ve Sayaç",
        "m72_stopwatch" to "Kronometre",
        "m72_timer" to "Zamanlayıcı",
        "m73_desc" to "Tüm arayüzü TR, EN, ES, FR ve IT arasında anında değiştirin.",
        "m73_hint" to "Değiştirme anındır — yeniden başlatma yok, yeniden yükleme yok.",
        "m73_name" to "Çok Dilli Motor",
        "m73_status" to "Motor durumu",
        "m74_active" to "etkin",
        "m74_classic" to "Klasik Araç",
        "m74_desc" to "Üç canlı tema: Material 3, Hacker/Siberpunk ve Klasik Araç.",
        "m74_name" to "Dinamik Arayüz Tema Motoru",
        "m74_preview" to "Canlı önizleme",
        "m74_select" to "Tema",
        "m75_desc" to "Alpine rootfs'i kurun, güncelleyin, doğrulayın veya kaldırın; motoru izleyin.",
        "m75_hint" to "Minirootfs çevrimdışı kurulum için pakette gelir; güncelleme en yeni 3.21.x'i indirir.",
        "m75_install" to "Rootfs'i kur",
        "m75_log" to "Motor günlüğü",
        "m75_name" to "Alpine Rootfs Kurulum Durumu",
        "m75_not_ready" to "KURULU DEĞİL",
        "m75_path" to "Konum",
        "m75_ready" to "HAZIR",
        "m75_remove" to "Rootfs'i kaldır",
        "m75_status" to "Rootfs durumu",
        "m75_update" to "Yeniden indir ve güncelle",
        "m75_verified" to "SHA-256 doğrulandı",
        "m76_check" to "İkili denetle",
        "m76_desc" to "Bir ikilinin ELF makine türünü bu cihazın desteklenen ABI'leriyle eşleştirin.",
        "m76_device" to "Cihaz ABI'leri",
        "m76_hint" to "İndirilen ikilileri sıra dışı cihazlarda ve emülatörlerde çalıştırmadan önce kullanışlıdır.",
        "m76_match" to "Eşleştir",
        "m76_name" to "Yerel ELF Mimari Eşleştirici",
        "m76_will_run" to "Bu ikili bu cihazda çalışır",
        "m76_wont_run" to "Mimari uyumsuz — ÇALIŞMAZ",
        "m77_app" to "Uygulama",
        "m77_available" to "güncelleme var",
        "m77_check" to "Güncelleme denetimi",
        "m77_checking" to "Denetleniyor…",
        "m77_desc" to "MSI sürüm bilgisi, motor durumu ve uzak güncelleme bildirimi denetimi.",
        "m77_hint" to "Uzak bildirim: github.com/finndev/msi-manifest (version.json).",
        "m77_module_versions" to "Motor modülleri",
        "m77_modules" to "Modüller",
        "m77_name" to "Uygulama Güncelleme ve Sürüm Denetçisi",
        "m77_offline" to "Ağ yok veya bildirim kullanılamıyor",
        "m77_parse_error" to "Bildirim biçim hatası",
        "m77_up_to_date" to "Güncel",
        "m78_desc" to "MSI v4.0.0 kontrol merkezi: sistem genel bakışı ve 78 modülün tamamına geçit.",
        "m78_name" to "Ana Sistem Panosu",
        "nav_home" to "Ana panel",
        "nav_modules" to "Modüller",
        "nav_settings" to "Ayarlar",
        "nav_terminal" to "Terminal",
        "no" to "Hayır",
        "ob_continue" to "Devam",
        "ob_lang_desc" to "Tüm arayüz — 78 modülün tamamı, menüler ve düğmeler — anında değişecek.",
        "ob_lang_note" to "Dili daha sonra 73. modülden değiştirebilirsiniz.",
        "ob_lang_title" to "Lütfen dilinizi seçin",
        "ob_perm_allfiles" to "Tüm dosyalara erişim (Android 11+)",
        "ob_perm_desc" to "MSI; dosyaları, ISO'ları, yedekleri ve günlükleri yönetmek için depolama erişimine ihtiyaç duyar. Depolama izinleri her şeyden önce, şimdi isteniyor.",
        "ob_perm_grant" to "İzinleri ver",
        "ob_perm_granted" to "verildi",
        "ob_perm_missing" to "eksik",
        "ob_perm_read" to "Depolamayı oku",
        "ob_perm_skip_warn" to "Depolama erişimi olmadan bazı modüller sınırlı olacak",
        "ob_perm_write" to "Depolamaya yaz",
        "ob_skip" to "Atla",
        "ob_start" to "MSI'yı başlat",
        "ob_welcome" to "MSI'ya hoş geldiniz",
        "open" to "Aç",
        "open_module" to "Modülü aç",
        "output" to "Çıktı",
        "refresh" to "Yenile",
        "reset" to "Sıfırla",
        "root_hint" to "bu modülü etkinleştirmek için root erişimi verin (Magisk / KernelSU / APatch)",
        "root_required" to "Root gerekli",
        "run" to "Çalıştır",
        "save" to "Kaydet",
        "scan" to "Tara",
        "scanning" to "Taranıyor…",
        "search_modules" to "78 modülde ara…",
        "share" to "Paylaş",
        "size" to "Boyut",
        "start" to "Başlat",
        "stop" to "Durdur",
        "version" to "Sürüm",
        "yes" to "Evet",
    )
}
