package com.finndev.master.system.inspector.core

/** Generated MSI string table (Italian) — 728 keys. */
object LocDataIt {
    val data: Map<String, String> = mapOf(
        "abort" to "Interrompi",
        "about" to "Informazioni",
        "about_modules_count" to "{0} moduli — tutti completamente funzionanti",
        "actions" to "Azioni",
        "app_tagline" to "Ana Sistem Denetçisi — Master System Inspector",
        "apply" to "Applica",
        "cancel" to "Annulla",
        "cat_all" to "Tutti",
        "cat_network" to "Rete, Sicurezza e Diagnostica",
        "cat_root" to "Root e Kernel",
        "cat_storage" to "Archiviazione, ISO e File",
        "cat_system" to "Profilazione Sistema e Utilità",
        "cat_terminal" to "Terminale, RootFS e Script",
        "check_updates" to "Cerca aggiornamenti",
        "clear" to "Pulisci",
        "confirm" to "Conferma",
        "copy" to "Copia",
        "current_language" to "Lingua corrente",
        "dash_all_modules" to "Tutti i moduli (1–78)",
        "dash_android" to "Android",
        "dash_categories" to "Categorie",
        "dash_quick" to "Azioni rapide",
        "dash_ram" to "RAM libera",
        "dash_ram_sub" to "su {0} totali",
        "dash_root" to "Root",
        "dash_root_no" to "Senza root",
        "dash_root_unknown" to "verifica…",
        "dash_root_yes" to "Con root",
        "dash_storage" to "Spazio libero",
        "dash_storage_free" to "libero",
        "dash_storage_sub" to "su {0}",
        "delete" to "Elimina",
        "download" to "Scarica",
        "downloading" to "Download in corso…",
        "empty_list" to "Ancora niente qui",
        "error" to "Errore",
        "export" to "Esporta",
        "filter" to "Filtra",
        "input" to "Input",
        "m01_desc" to "Rilevamento root profondo: gestori Magisk, KernelSU, APatch, binari su e registro prove.",
        "m01_evidence" to "Prove di rilevamento",
        "m01_manager" to "Gestore root",
        "m01_name" to "Auditor Root Avanzato",
        "m01_no_evidence" to "Nessuna prova di root trovata",
        "m01_su_path" to "Percorso del binario su",
        "m02_desc" to "Leggi e commuta SELinux tra Enforcing e Permissive tramite root.",
        "m02_name" to "Commutatore Modalità SELinux",
        "m02_set_enforcing" to "Imposta Enforcing",
        "m02_set_permissive" to "Imposta Permissive",
        "m02_warn" to "La modalità Permissive riduce la sicurezza. Usala solo per il debug.",
        "m03_desc" to "Leggi, cerca e aggiungi proprietà di sistema con scrittura root.",
        "m03_edit" to "Aggiungi nuova proprietà",
        "m03_hint" to "Le proprietà sono aggiunte a /system/build.prop (il sistema viene rimontato rw).",
        "m03_loaded" to "Proprietà caricate",
        "m03_name" to "Editor Build.prop in Diretta",
        "m04_desc" to "Elenca, esegui e installa script /system/etc/init.d con root.",
        "m04_found" to "Script installati",
        "m04_hint" to "Lo script è codificato in base64 per sopravvivere al quoting; verrà eseguito al prossimo avvio.",
        "m04_install" to "Installa",
        "m04_name" to "Esecutore Script Init.d",
        "m04_new" to "Installa nuovo script",
        "m04_none" to "Nessuno script init.d trovato (il supporto init.d potrebbe mancare)",
        "m04_script" to "Corpo dello script",
        "m05_current" to "Flag di mount correnti",
        "m05_desc" to "Rimonta /system e /vendor in lettura-scrittura o sola lettura con root.",
        "m05_hint" to "Sui dispositivi system-as-root viene rimontato il punto /.",
        "m05_name" to "Rimontatore Partizioni di Sistema",
        "m05_none" to "Nessuna voce system/vendor trovata",
        "m05_remount_ro" to "Rimonta RO",
        "m05_remount_rw" to "Rimonta RW",
        "m06_available" to "Governor disponibili",
        "m06_current" to "Stato per core",
        "m06_desc" to "Profilo di frequenza per core e governor; cambia governor al volo.",
        "m06_name" to "Profilatore Governor CPU",
        "m06_no_governors" to "Il kernel non espone l'elenco dei governor",
        "m07_cores" to "Core",
        "m07_cpu0_note" to "CPU0 è il core di avvio e non può essere disattivato.",
        "m07_desc" to "Attiva/disattiva core CPU e limita le frequenze min/max.",
        "m07_freq_limit" to "Limiti di frequenza",
        "m07_limit_hint" to "I limiti si applicano a tutte le policy cpufreq come percentuale del massimo hardware.",
        "m07_max" to "Frequenza massima",
        "m07_min" to "Frequenza minima",
        "m07_name" to "Hotplug Core e Limitatore Frequenza",
        "m07_offline" to "Disattiva",
        "m07_online" to "Attiva",
        "m08_current" to "Stato LMK corrente",
        "m08_desc" to "Leggi e regola le soglie minfree del lowmemorykiller.",
        "m08_edit" to "Regola minfree",
        "m08_hint" to "Valori in kB per livello di priorità, separati da virgole (6 livelli).",
        "m08_lmk_missing" to "LMK non esposto (i kernel moderni usano PSI/lmkd)",
        "m08_name" to "Regolatore Low Memory Killer",
        "m09_cycles" to "Contatore cicli",
        "m09_cycles_na" to "solo Android 14+",
        "m09_desc" to "Salute batteria, temperatura, cicli e controllo soglia di ricarica.",
        "m09_health" to "Salute",
        "m09_level" to "Livello",
        "m09_name" to "Gestore Batteria e Ricarica",
        "m09_now" to "Batteria attuale",
        "m09_tech" to "Tecnologia",
        "m09_temp" to "Temperatura",
        "m09_threshold" to "Soglia di ricarica",
        "m09_threshold_current" to "Soglia attuale",
        "m09_threshold_hint" to "es. 80 mantiene la batteria tra 20-80% per la longevità (dispositivi compatibili).",
        "m09_threshold_na" to "non supportata dal kernel",
        "m09_threshold_new" to "Nuova soglia (%)",
        "m09_voltage" to "Tensione",
        "m10_current" to "Override schermo correnti",
        "m10_density" to "Densità (DPI)",
        "m10_desc" to "Sovrascrivi risoluzione e densità schermo con wm size / wm density.",
        "m10_name" to "Manipolatore Risoluzione e DPI",
        "m10_size" to "Risoluzione",
        "m10_warn" to "Valori aggressivi possono rendere l'UI illeggibile — Ripristina riporta ai valori predefiniti.",
        "m11_apps" to "App installate",
        "m11_desc" to "Congela, nascondi, disinstalla (user 0) e ripristina pacchetti di sistema via pm.",
        "m11_enable" to "Abilita",
        "m11_freeze" to "Congela",
        "m11_hint" to "La disinstallazione usa 'pm uninstall --user 0' — reversibile con Abilita; l'APK resta su disco.",
        "m11_name" to "Congelatore App di Sistema",
        "m11_restore" to "Ripristina pacchetto",
        "m11_restore_pkg" to "nome pacchetto",
        "m11_unhide" to "Mostra",
        "m11_uninstall" to "Disinstalla",
        "m12_count" to "Sensori su questo dispositivo",
        "m12_desc" to "Streaming in diretta di giroscopio, accelerometro, magnetometro e altro.",
        "m12_name" to "Streamer Sensori Hardware in Diretta",
        "m12_power" to "Consumo",
        "m12_range" to "Portata massima",
        "m12_resolution" to "Risoluzione",
        "m13_buffer" to "Istantanea del buffer",
        "m13_desc" to "Leggi il ring buffer del kernel e seguilo in diretta con dmesg -w.",
        "m13_empty" to "Buffer vuoto o illeggibile",
        "m13_follow" to "Avvia seguito",
        "m13_live" to "Seguito in diretta",
        "m13_name" to "Lettore Log Kernel (dmesg)",
        "m13_read" to "Leggi buffer (root)",
        "m14_awake" to "Tempo attivo",
        "m14_boot_id" to "ID di avvio",
        "m14_deep" to "Deep sleep",
        "m14_desc" to "Uptime, quota deep-sleep e sequenza temporale degli eventi di boot.",
        "m14_name" to "Analizzatore Avvio e Startup",
        "m14_no_log" to "Nessun evento di avvio disponibile",
        "m14_stages" to "Eventi di avvio",
        "m14_stats" to "Statistiche di avvio",
        "m14_uptime" to "Tempo dall'avvio",
        "m15_cores" to "Thread",
        "m15_desc" to "Benchmark di stress SHA-256 (mono/multi core) più test di banda della memoria.",
        "m15_hint" to "Esegue 2 s mono-core, 2 s tutti i core in SHA-256 e un passaggio di memoria da 96 MB.",
        "m15_mem" to "Memoria",
        "m15_multi" to "Multi-core",
        "m15_name" to "Test Benchmark CPU e RAM",
        "m15_running" to "Benchmark in corso…",
        "m15_scores" to "Punteggi",
        "m15_single" to "Mono-core",
        "m16_apk_update" to "apk update && upgrade",
        "m16_bootstrapping" to "preparazione",
        "m16_desc" to "Rootfs Alpine Linux autentico via PRoot nello storage dell'app — con gestione completa di apk.",
        "m16_exited" to "terminata",
        "m16_hint" to "Prova: apk update • apk add python3 • cat /etc/alpine-release",
        "m16_idle" to "inattiva",
        "m16_input_hint" to "digita un comando e premi Invio",
        "m16_name" to "Vero Terminale Alpine Linux PRoot",
        "m16_restart" to "Riavvia sessione",
        "m16_running" to "in corso",
        "m16_share_log" to "Condividi trascrizione",
        "m16_state" to "Sessione",
        "m16_stop" to "Ferma sessione",
        "m17_clone" to "Clona repository (depth 1)",
        "m17_desc" to "Rileva com.termux, lo avvia e clona repository Git tramite il git Alpine.",
        "m17_git" to "Cloner Git",
        "m17_git_hint" to "Le repository sono clonate in /sdcard/MSI/GitRepos con il git Alpine integrato.",
        "m17_installed" to "installato",
        "m17_launch" to "Avvia Termux",
        "m17_name" to "Integrazione Termux e Cloner Git",
        "m17_not_installed" to "non installato",
        "m18_arch" to "Architettura",
        "m18_config" to "Configurazione macchina",
        "m18_create_disk" to "Crea disco qcow2",
        "m18_desc" to "Installa e avvia macchine QEMU (x86_64 / i386 / aarch64) dentro il rootfs Alpine.",
        "m18_disk" to "Dimensione disco (GB)",
        "m18_hint" to "QEMU gira headless con console seriale; il percorso ISO punta a un file in /sdcard.",
        "m18_install" to "Installa QEMU (apk)",
        "m18_launch" to "Avvia nel terminale",
        "m18_name" to "Emulatore QEMU Multi-Architettura",
        "m18_ram" to "Memoria",
        "m19_bash_note" to "bash viene installato on-demand nel rootfs Alpine (apk add bash).",
        "m19_desc" to "Esegui script .sh con output in diretta via Alpine /bin/sh, bash Alpine o sh Android.",
        "m19_engine" to "Motore script",
        "m19_name" to "Esecutore Script Bash e Shell",
        "m19_running" to "Esecuzione…",
        "m19_script" to "Script",
        "m20_args" to "Argomenti",
        "m20_compat" to "Compatibilità dispositivo",
        "m20_compat_no" to "ABI incompatibile",
        "m20_compat_yes" to "compatibile",
        "m20_desc" to "Ispeziona ed esegui direttamente binari ARM/x86 con root.",
        "m20_hint" to "chmod +x è applicato automaticamente; i binari vengono eseguiti via su.",
        "m20_inspect" to "Ispeziona ELF",
        "m20_name" to "Esecutore Binari ELF Nativi",
        "m20_not_elf" to "Non è un file ELF",
        "m20_path" to "Percorso binario",
        "m20_pick" to "Binario",
        "m21_code" to "Codice",
        "m21_desc" to "Esegui script Python 3 e Lua 5.4 dentro il rootfs Alpine — interpreti veri.",
        "m21_in_terminal" to "Apri interattivo nel terminale",
        "m21_install" to "Installa via apk",
        "m21_installed" to "pronto",
        "m21_lang" to "Linguaggio",
        "m21_name" to "Interprete Python e Lua",
        "m21_not_installed" to "non ancora installato",
        "m21_running" to "Esecuzione…",
        "m21_runtime" to "Runtime",
        "m22_analyze" to "Analizza",
        "m22_desc" to "Ispezione completa delle intestazioni ELF: classe, endian, macchina, entry point, PT_INTERP.",
        "m22_invalid" to "ELF non valido",
        "m22_list" to "Elenca cartella",
        "m22_listing" to "Contenuto della cartella",
        "m22_machine" to "Macchina",
        "m22_name" to "Analizzatore Profondo Binari ELF",
        "m22_no_dir" to "Cartella illeggibile",
        "m22_pick" to "Un file ELF",
        "m22_type" to "Tipo",
        "m23_desc" to "chmod / chown su qualsiasi file via root con stat in diretta.",
        "m23_mode" to "Modo (ottale)",
        "m23_name" to "Gestore Permessi File",
        "m23_stat" to "Stato corrente",
        "m24_custom" to "Voci PATH personalizzate",
        "m24_desc" to "Ispeziona il PATH della shell MSI e aggiungi cartelle personalizzate.",
        "m24_extra" to "Cartelle extra (separate da due punti)",
        "m24_hint" to "Applicato a ogni sessione shell MSI e all'ambiente PRoot.",
        "m24_name" to "Gestore PATH d'Ambiente",
        "m25_applets" to "Applet",
        "m25_desc" to "Rileva busybox, elenca i suoi applet e installa busybox-static via Alpine.",
        "m25_detect" to "Rilevamento",
        "m25_install" to "Installa busybox-static",
        "m25_install_btn" to "Installa",
        "m25_install_hint" to "Il binario statico viene esportato in /sdcard/MSI/busybox tramite il gestore pacchetti Alpine.",
        "m25_name" to "Integrazione e Validatore Busybox",
        "m25_not_found" to "non trovato",
        "m26_actions" to "Azioni di emergenza",
        "m26_confirm" to "Eseguire questo comando?",
        "m26_custom" to "Comando personalizzato (su)",
        "m26_desc" to "Comandi d'emergenza: ripara permessi, taglia cache, rimonta, riavvia.",
        "m26_name" to "Console di Recupero d'Emergenza",
        "m27_builder" to "Costruttore macro",
        "m27_desc" to "Concatena comandi shell con ritardi in macro salvate a un tocco.",
        "m27_format" to "Un passo per riga: comando|ritardo_ms — prefisso '#root ' per forzare su",
        "m27_name" to "Nome macro",
        "m27_none" to "Ancora nessuna macro",
        "m27_saved" to "Macro salvate",
        "m27_steps" to "Passi",
        "m28_current" to "Trascrizione sessione corrente",
        "m28_desc" to "Salva la trascrizione del terminale e i log di sessione come .txt / .log.",
        "m28_hint" to "I file restano nei log privati dell'app e possono essere condivisi.",
        "m28_lines" to "Righe",
        "m28_name" to "Esportatore Log del Terminale",
        "m28_none" to "Ancora nessun log",
        "m28_saved" to "Log salvati",
        "m29_desc" to "Scrivi note con anteprima markdown istantanea, salvate nella memoria interna.",
        "m29_edit" to "Modifica",
        "m29_hint" to "Supporta # titoli, **grassetto**, `codice`, elenchi e blocchi di codice.",
        "m29_name" to "Editor Note Markdown Offline",
        "m29_new" to "Nuova nota",
        "m29_none" to "Ancora nessuna nota",
        "m29_notes" to "Note",
        "m29_preview" to "Anteprima",
        "m30_desc" to "Scansiona qualsiasi formato di codice a barre e genera QR code esportabili.",
        "m30_generate" to "Generatore",
        "m30_generate_btn" to "Genera QR",
        "m30_name" to "Scanner QR e Codici a Barre",
        "m30_result" to "Risultato",
        "m30_save" to "Salva in Download",
        "m30_scan" to "Scanner",
        "m30_scan_btn" to "Scansiona codice",
        "m30_scan_cancel" to "Scansione annullata",
        "m31_bytes" to "Byte",
        "m31_desc" to "Converti testo tra Base64, esadecimale e binario — più hashing di file.",
        "m31_file" to "Modalità file (≤ 8 MB)",
        "m31_file_b64" to "Codifica file in Base64",
        "m31_file_limit" to "File troppo grande o assente (limite 8 MB)",
        "m31_invalid_b64" to "Input Base64 non valido",
        "m31_invalid_bin" to "Input binario non valido",
        "m31_invalid_hex" to "Input hex non valido",
        "m31_mode" to "Modalità conversione",
        "m31_name" to "Codificatore Base64, Hex e Binario",
        "m32_desc" to "Formatta, valida e abbellisce documenti JSON e XML.",
        "m32_format" to "Formatta e valida",
        "m32_invalid" to "Non valido",
        "m32_invalid_json" to "JSON non valido",
        "m32_invalid_xml" to "XML non valido",
        "m32_mode" to "Formato",
        "m32_name" to "Formattatore JSON e XML",
        "m32_valid" to "Documento valido",
        "m33_add" to "Aggiungi voce",
        "m33_desc" to "Cassaforte AES-256-GCM con derivazione PBKDF2 — completamente offline.",
        "m33_empty" to "La cassaforte è vuota",
        "m33_entries" to "Voci",
        "m33_gen" to "Genera",
        "m33_hint" to "La cassaforte è cifrata con AES-GCM; la chiave non lascia mai il dispositivo.",
        "m33_lock" to "Blocca cassaforte",
        "m33_master" to "Password principale",
        "m33_name" to "Gestore Password Cifrato Offline",
        "m33_pass" to "Password",
        "m33_short_pwd" to "La password principale deve avere almeno 4 caratteri",
        "m33_title" to "Titolo",
        "m33_unlock" to "Cassaforte",
        "m33_unlock_btn" to "Sblocca / crea cassaforte",
        "m33_user" to "Nome utente / email",
        "m33_wrong_pwd" to "Password principale errata",
        "m34_desc" to "Spazia la sottorete /24 in cerca di host attivi e risolve i MAC.",
        "m34_found" to "Dispositivi trovati",
        "m34_hint" to "254 host sondati in parallelo; i MAC arrivano dalla tabella ARP.",
        "m34_name" to "Scanner Dispositivi LAN IP e MAC",
        "m34_none" to "Nessun dispositivo trovato",
        "m34_scan" to "Scansiona sottorete",
        "m34_scanning" to "Scansione…",
        "m34_subnet" to "Sottorete (x.x.x.)",
        "m35_closed" to "chiusa",
        "m35_desc" to "Controlla porte TCP e UDP su qualsiasi host con socket paralleli.",
        "m35_filtered" to "nessuna risposta",
        "m35_host" to "Host",
        "m35_name" to "Scanner Porte (TCP/UDP)",
        "m35_none" to "Scansiona prima un bersaglio",
        "m35_open" to "APERTA",
        "m35_ports" to "Porte",
        "m35_target" to "Bersaglio",
        "m35_udp_hint" to "UDP 'nessuna risposta' di solito significa aperta-o-filtrata (nessun errore ICMP).",
        "m36_count" to "Quantità",
        "m36_desc" to "Ping continuo con grafico di latenza per risposta e statistiche min/med/max.",
        "m36_name" to "Monitor Ping e Latenza Avanzato",
        "m36_start" to "Avvia ping",
        "m36_target" to "Bersaglio del ping",
        "m37_adguard" to "AdGuard (blocco pubblicità)",
        "m37_auto" to "Automatico (opportunistico)",
        "m37_cloudflare" to "Cloudflare (1.1.1.1)",
        "m37_current" to "DNS privato corrente",
        "m37_custom" to "Hostname personalizzato",
        "m37_desc" to "Impo­ni DNS privato (DoT): Cloudflare, Google, AdGuard, Quad9.",
        "m37_google" to "Google (8.8.8.8)",
        "m37_hint" to "Applica il DNS privato di Android su TLS tramite il provider delle impostazioni (root).",
        "m37_name" to "Impostore DNS Personalizzato (Root)",
        "m37_off" to "Disattiva DNS privato",
        "m37_presets" to "Preimpostazioni",
        "m37_quad9" to "Quad9 (sicurezza)",
        "m38_add_rule" to "Aggiungi regola",
        "m38_allow" to "Consenti (rimuovi)",
        "m38_block" to "Blocca porta",
        "m38_desc" to "Ispeziona le catene iptables e aggiungi/rimuovi regole di blocco porte via root.",
        "m38_hint" to "Le regole usano REJECT sulla catena scelta; il ruleset nftables è mostrato se presente.",
        "m38_ipt_unavailable" to "iptables non disponibile o bloccato",
        "m38_name" to "Gestore Regole Firewall",
        "m38_nft" to "nftables",
        "m38_nft_available" to "disponibile",
        "m38_nft_missing" to "non disponibile",
        "m39_desc" to "Tabella netstat in diretta degli endpoint TCP/UDP mappati alle app.",
        "m39_hint" to "Legge /proc/net/tcp, tcp6, udp e udp6; gli UID sono risolti in pacchetti app.",
        "m39_name" to "Ispettore Socket di Rete Attivi",
        "m39_none" to "Nessuno socket leggibile",
        "m39_sockets" to "Socket",
        "m39_table" to "Tabella endpoint",
        "m40_desc" to "Misura latenza, download e upload verso Cloudflare.",
        "m40_down" to "Download",
        "m40_hint" to "Scarica 25 MB e carica 10 MB — occhio al piano dati.",
        "m40_latency" to "Latenza",
        "m40_name" to "Test Velocità Internet",
        "m40_results" to "Risultati",
        "m40_running" to "Misurazione…",
        "m40_start" to "Avvia test",
        "m40_up" to "Upload",
        "m41_desc" to "Cambia l'indirizzo MAC di qualsiasi interfaccia con valori casuali o personalizzati.",
        "m41_hint" to "Il Wi-Fi deve riconnettersi dopo wlan0; alcuni driver rifiutano MAC personalizzati.",
        "m41_iface" to "Interfaccia",
        "m41_interfaces" to "Interfacce",
        "m41_invalid_mac" to "Formato MAC non valido",
        "m41_name" to "Falsificazione Indirizzo MAC (Root)",
        "m41_new_mac" to "Nuovo MAC",
        "m41_random" to "Casuale",
        "m41_spoof" to "Falsifica",
        "m42_channel" to "Canale",
        "m42_congestion" to "Congestione canali",
        "m42_current" to "Connessione attuale",
        "m42_desc" to "Potenza segnale, dati collegamento, congestione canali e reti vicine.",
        "m42_freq" to "Frequenza",
        "m42_grant" to "Concedi localizzazione",
        "m42_level" to "Livello",
        "m42_location" to "Permesso localizzazione",
        "m42_location_hint" to "Android richiede la localizzazione per mostrare i risultati della scansione.",
        "m42_name" to "Analizzatore Segnale e Canali Wi-Fi",
        "m42_networks" to "Reti vicine",
        "m42_rssi" to "Segnale (RSSI)",
        "m43_cert" to "Certificato",
        "m43_chain" to "Catena",
        "m43_cipher" to "Suite di cifratura",
        "m43_desc" to "Esegue un handshake TLS e ispeziona l'intera catena di certificati.",
        "m43_expired" to "SCADUTO",
        "m43_inspect" to "Ispeziona",
        "m43_name" to "Ispezione Certificati SSL e TLS",
        "m43_status" to "Validità",
        "m43_target" to "Host (porta 443)",
        "m43_tls_version" to "Versione TLS",
        "m43_valid" to "valido",
        "m43_valid_from" to "Valido dal",
        "m43_valid_to" to "Valido fino al",
        "m44_connections" to "Connessioni tracciate",
        "m44_desc" to "Tracciamento aperture/chiusure connessioni con contabilità traffico per app.",
        "m44_hint" to "Sonda le tabelle socket del kernel e le confronta; i delta RX/TX arrivano da TrafficStats.",
        "m44_log" to "Log eventi",
        "m44_name" to "Sniffer Pacchetti e Logger Traffico",
        "m44_start" to "Avvia tracciamento",
        "m44_status" to "Stato",
        "m45_ap" to "Stato tethering",
        "m45_ap_off" to "L'hotspot sembra inattivo",
        "m45_clients" to "Client collegati",
        "m45_desc" to "Mostra lo stato del tethering e i client hotspot collegati (via ARP).",
        "m45_hint" to "I client sono derivati dalla tabella ARP quando l'hotspot è attivo.",
        "m45_name" to "Ispettore Hotspot e Tethering",
        "m45_no_clients" to "Nessun client collegato",
        "m46_answer" to "La tua risposta",
        "m46_bench" to "Banco di prova",
        "m46_challenge" to "Sfida",
        "m46_desc" to "Genera captcha locali distorti e misura i tassi di successo/fallimento.",
        "m46_fail" to "FALLITO",
        "m46_log" to "Log tentativi",
        "m46_name" to "Banco di Prova Captcha e Anti-Bot",
        "m46_new" to "Nuova sfida",
        "m46_pass" to "SUPERATO",
        "m46_stats" to "Risolti / falliti",
        "m46_verify" to "Verifica",
        "m47_desc" to "Password SecureRandom, token hex, UUID e passphrase.",
        "m47_hint" to "Tutta l'entropia proviene dal generatore SecureRandom della piattaforma.",
        "m47_length" to "Lunghezza",
        "m47_mode" to "Modalità",
        "m47_name" to "Generatore Sicuro Password e Token",
        "m47_passphrase" to "Passphrase",
        "m47_password" to "Password",
        "m47_regenerate" to "Rigenera",
        "m47_results" to "Generato",
        "m48_confirm" to "Questo distrugge i dati in modo permanente. Continuare?",
        "m48_desc" to "Sovrascrive i file con più passate casuali prima dell'eliminazione.",
        "m48_exists" to "Esiste",
        "m48_hint" to "1-7 passate casuali + passata finale di zeri; le cartelle sono distrutte ricorsivamente.",
        "m48_name" to "Distruttore File Sensibili",
        "m48_passes" to "Passate",
        "m48_running" to "Distruzione…",
        "m48_shred" to "Distruggi definitivamente",
        "m48_target" to "Bersaglio",
        "m49_desc" to "Testa espressioni regolari con anteprima live di corrispondenze e sostituzione.",
        "m49_input" to "Testo di prova",
        "m49_matches" to "Corrispondenze",
        "m49_name" to "Banco di Prova Regex",
        "m49_pattern" to "Pattern",
        "m49_replace" to "Anteprima sostituzione",
        "m49_with" to "Sostituisci con",
        "m50_add_palette" to "Aggiungi alla tavolozza",
        "m50_clear" to "Svuota tavolozza",
        "m50_current" to "Colore attuale",
        "m50_desc" to "Selettore HSL interattivo con codici HEX / RGB e tavolozza salvata.",
        "m50_dials" to "Controlli",
        "m50_hex_input" to "Da HEX",
        "m50_hue" to "Tonalità",
        "m50_lum" to "Luminosità",
        "m50_name" to "Tavolozza Colori e Selettore HEX/RGB",
        "m50_palette" to "Tavolozza",
        "m50_sat" to "Saturazione",
        "m51_arch" to "Architettura",
        "m51_config" to "Download",
        "m51_desc" to "Scaricatore ISO con selettore architettura, ripresa, avanzamento e SHA-256.",
        "m51_dest" to "Destinazione",
        "m51_name" to "Scaricatore ISO ValiantCore",
        "m51_sha256" to "Calcola SHA-256",
        "m51_verify" to "Verifica hash",
        "m51_verify_hint" to "Confronta il digest calcolato con la fonte di cui ti fidi.",
        "m52_config" to "Configurazione server",
        "m52_desc" to "Condividi qualsiasi cartella via HTTP sulla LAN con un indice in stile.",
        "m52_dir" to "Cartella condivisa",
        "m52_hint" to "Gira come servizio in primo piano di sincronizzazione dati; supporta Range per i media.",
        "m52_log" to "Log richieste",
        "m52_log_empty" to "Ancora nessuna richiesta",
        "m52_name" to "Server Locale di Condivisione HTTP",
        "m52_port" to "Porta",
        "m52_running" to "in esecuzione",
        "m52_served" to "Richieste servite",
        "m52_start" to "Avvia server",
        "m52_status" to "Stato",
        "m52_stopped" to "fermato",
        "m53_all" to "Backup di massa",
        "m53_apps" to "Pacchetti installati",
        "m53_backup_user_apps" to "Salva tutte le app utente",
        "m53_desc" to "Copia le APK installate nello storage — singole app o tutte le app utente.",
        "m53_hint" to "I backup vengono scritti in /sdcard/MSI/APKBackups.",
        "m53_name" to "Backup APK ed Estrattore Pacchetti",
        "m54_clean_own" to "Pulisci cache proprie",
        "m54_cleaning" to "Pulizia…",
        "m54_deep_clean" to "Pulizia profonda cache app",
        "m54_desc" to "Pulisci le tue cache, taglia quelle di sistema e pulisci a fondo le cache app (root).",
        "m54_freed" to "Liberato",
        "m54_name" to "Pulitore Profondo Archiviazione e Cache",
        "m54_own" to "Cache MSI",
        "m54_own_cache" to "Dimensione cache propria",
        "m54_system" to "Sistema (root)",
        "m54_system_hint" to "pm trim-caches libera la cache di tutte le app; la pulizia profonda cancella /data/data/*/cache.",
        "m54_trim_caches" to "Taglia cache (pm)",
        "m55_desc" to "Digest MD5 / SHA-1 / SHA-256 con confronto con l'hash atteso.",
        "m55_expected" to "Digest atteso",
        "m55_file" to "File",
        "m55_hash" to "Calcola hash",
        "m55_match" to "HASH CORRISPONDE",
        "m55_mismatch" to "HASH NON CORRISPONDE",
        "m55_name" to "Verificatore Hash ISO e Binari",
        "m55_quick" to "Scelta rapida",
        "m55_verify" to "Verifica",
        "m56_desc" to "Trova i file più grandi che occupano il tuo spazio.",
        "m56_files" to "file",
        "m56_min_size" to "Dim. minima (MB)",
        "m56_name" to "Cacciatore Divora-Spazio",
        "m56_none" to "Nessun file oltre la soglia",
        "m56_results" to "File più grandi",
        "m56_root" to "Radice scansione",
        "m56_scan" to "Caccia",
        "m56_total" to "Totale",
        "m57_archive_path" to "Percorso archivio",
        "m57_create" to "Crea archivio",
        "m57_desc" to "Crea ed estrai archivi .zip e .tar.gz con log di avanzamento.",
        "m57_extract" to "Estrai",
        "m57_name" to "Nome archivio",
        "m57_pack" to "Comprimi",
        "m57_source_dir" to "Cartella sorgente",
        "m57_unpack" to "Decomprimi",
        "m57_working" to "Elaborazione…",
        "m58_active" to "Trasferimenti attivi e recenti",
        "m58_add" to "Aggiungi trasferimento",
        "m58_desc" to "Accoda download con avanzamento live per trasferimento (2 simultanei).",
        "m58_enqueue" to "Accoda",
        "m58_hint" to "I file arrivano in /sdcard/MSI/Downloads.",
        "m58_name" to "Coda Download e Tracker Trasferimenti",
        "m58_none" to "Ancora nessun trasferimento",
        "m59_clear" to "Svuota cronologia",
        "m59_desc" to "Sorveglia gli appunti, conserva la cronologia e salva snippet riutilizzabili.",
        "m59_history" to "Cronologia appunti",
        "m59_name" to "Cronologia Appunti e Snippet",
        "m59_none" to "Niente copiato finora",
        "m59_paused" to "In pausa",
        "m59_save_snippet" to "Salva snippet",
        "m59_snippets" to "Snippet",
        "m59_watching" to "Sorveglianza appunti",
        "m60_desc" to "Report diagnostico completo: hardware, memoria, storage, logcat e dmesg.",
        "m60_generate" to "Genera report",
        "m60_name" to "Esportatore Log e Report Diagnostico",
        "m60_preview" to "Anteprima",
        "m60_report" to "Report",
        "m60_save" to "Salva in Download",
        "m61_confirm" to "La partizione system viene rimontata rw e Roboto-Regular è salvato. Continuare?",
        "m61_current" to "Font correnti (campione)",
        "m61_desc" to "Installa una TTF personalizzata in /system/fonts con backup e ripristino.",
        "m61_font_path" to "Percorso TTF",
        "m61_hint" to "Il font è copiato come /system/fonts/MSICustom-Regular.ttf (644).",
        "m61_install" to "Installa font",
        "m61_install_btn" to "Installa come MSICustom",
        "m61_name" to "Personalizzatore Font di Sistema (Root)",
        "m61_not_ttf" to "Il file selezionato non è un .ttf",
        "m61_restore" to "Ripristina",
        "m61_restore_btn" to "Rimuovi font personalizzato",
        "m62_confirm" to "La bootanimation attuale è salvata in /sdcard/MSI. Continuare?",
        "m62_current" to "Media correnti",
        "m62_desc" to "Valida e installa bootanimation.zip in /system/media.",
        "m62_hint" to "Un bootanimation.zip deve contenere desc.txt e cartelle part.",
        "m62_install" to "Installa",
        "m62_install_btn" to "Installa bootanimation",
        "m62_invalid_zip" to "Non valido: manca desc.txt",
        "m62_name" to "Personalizzatore Bootanimation (Root)",
        "m62_no_file" to "File non trovato",
        "m62_restore" to "Ripristina",
        "m62_restore_btn" to "Ripristina backup",
        "m62_valid_zip" to "Struttura valida (desc.txt presente)",
        "m62_validate" to "Valida zip",
        "m62_zip_path" to "Percorso bootanimation.zip",
        "m63_action" to "Azione tile",
        "m63_action_desc" to "Apre la sessione terminale Alpine",
        "m63_added" to "aggiunta al pannello",
        "m63_desc" to "Tile QS che apre il terminale MSI all'istante dal pannello.",
        "m63_howto" to "Trascina giù il pannello, modifica i tile e trascina 'MSI Terminal' al suo posto.",
        "m63_name" to "Integrazione Tile Impostazioni Rapide",
        "m63_not_added" to "non ancora aggiunta",
        "m63_notification" to "Notifiche",
        "m63_open_terminal" to "Simula tocco tile",
        "m63_state" to "Stato tile",
        "m63_test_notification" to "Invia notifica di test",
        "m63_tile" to "Tile",
        "m64_clear" to "Cancella crash",
        "m64_crashes" to "Crash registrati",
        "m64_desc" to "Raccogli log di crash, logcat e diagnostica in uno zip condivisibile.",
        "m64_hint" to "Lo zip contiene log di crash, logcat, dmesg e il report diagnostico.",
        "m64_name" to "Supporto Debug e Packager Log Crash",
        "m64_none" to "Nessun crash registrato",
        "m64_package" to "Pacchetto di supporto",
        "m64_view" to "Vedi l'ultimo",
        "m64_zip" to "Crea zip di debug",
        "m65_caches" to "Topologia cache",
        "m65_cores" to "Core",
        "m65_desc" to "SoC, topologia CPU, cache, GPU, memoria e storage in un solo pannello.",
        "m65_device" to "Dispositivo",
        "m65_freqs" to "Frequenze in diretta",
        "m65_name" to "Profilatore Hardware Avanzato",
        "m65_no_caches" to "sysfs delle cache non esposto",
        "m65_soc" to "SoC",
        "m66_available" to "Disponibile",
        "m66_desc" to "Memoria, swap e zram in diretta con grafico storico.",
        "m66_details" to "Dettagli",
        "m66_name" to "Monitor RAM e Swap in Tempo Reale",
        "m66_ram" to "RAM",
        "m66_total" to "Totale",
        "m66_used" to "Usata",
        "m67_all" to "Tutte",
        "m67_apps" to "Pacchetti",
        "m67_desc" to "Ogni pacchetto installato con copia del nome a un tocco.",
        "m67_installed_at" to "Installato il",
        "m67_name" to "Ispettore Pacchetti Installati",
        "m67_search" to "Cerca app",
        "m67_system" to "Solo sistema",
        "m68_desc" to "Tabella processi in diretta con memoria RSS e terminazione via root.",
        "m68_kill" to "Termina",
        "m68_name" to "Gestore Processi in Background",
        "m68_processes" to "Processi",
        "m69_desc" to "Logcat in diretta con filtri livello e testo (root per tutte le app).",
        "m69_empty" to "Nessun flusso",
        "m69_filter" to "Filtro",
        "m69_hint" to "la modalità root legge il buffer globale; quella utente mostra solo i log di MSI.",
        "m69_name" to "Flusso Logcat di Sistema in Diretta",
        "m69_start" to "Avvia flusso",
        "m70_desc" to "Tabella mount completa con tipi filesystem, flag RO e barre d'uso.",
        "m70_mounts" to "Mount",
        "m70_name" to "Punti di Mount e Uso Disco",
        "m70_none" to "df non disponibile",
        "m71_battery" to "Batteria",
        "m71_desc" to "Zone termiche, temperatura batteria e tendenza di throttling.",
        "m71_hint" to "I nomi delle zone arrivano dal kernel; ≥ 60 °C indica territorio di throttling pesante.",
        "m71_name" to "Ispettore Termico CPU",
        "m71_zones" to "Zone termiche",
        "m72_desc" to "Cronometro di precisione con giri e timer countdown con allarme.",
        "m72_lap" to "Giro",
        "m72_name" to "Timer, Cronometro e Cronografo",
        "m72_stopwatch" to "Cronometro",
        "m72_timer" to "Timer",
        "m73_desc" to "Cambia tutta l'interfaccia tra TR, EN, ES, FR e IT all'istante.",
        "m73_hint" to "Il cambio è istantaneo — nessun riavvio, nessun ricaricamento.",
        "m73_name" to "Motore Multilingua",
        "m73_status" to "Stato motore",
        "m74_active" to "attivo",
        "m74_classic" to "Utility Classica",
        "m74_desc" to "Tre temi live: Material 3, Hacker/Cyberpunk e Utility Classica.",
        "m74_name" to "Motore Temi UI Dinamico",
        "m74_preview" to "Anteprima live",
        "m74_select" to "Tema",
        "m75_desc" to "Installa, aggiorna, verifica o rimuovi il rootfs Alpine e monitora il motore.",
        "m75_hint" to "Il minirootfs è incluso per l'installazione offline; l'aggiornamento scarica la 3.21.x più recente.",
        "m75_install" to "Installa rootfs",
        "m75_log" to "Log motore",
        "m75_name" to "Stato Bootstrap Rootfs Alpine",
        "m75_not_ready" to "NON INSTALLATO",
        "m75_path" to "Posizione",
        "m75_ready" to "PRONTO",
        "m75_remove" to "Rimuovi rootfs",
        "m75_status" to "Stato rootfs",
        "m75_update" to "Riscarica e aggiorna",
        "m75_verified" to "SHA-256 verificato",
        "m76_check" to "Controlla binario",
        "m76_desc" to "Confronta il tipo macchina ELF di un binario con le ABI supportate dal dispositivo.",
        "m76_device" to "ABI del dispositivo",
        "m76_hint" to "Utile prima di eseguire binari scaricati su dispositivi ed emulatori particolari.",
        "m76_match" to "Confronta",
        "m76_name" to "Confrontatore Architettura ELF Nativa",
        "m76_will_run" to "Questo binario funzionerà su questo dispositivo",
        "m76_wont_run" to "Architettura incompatibile — NON funzionerà",
        "m77_app" to "App",
        "m77_available" to "aggiornamento disponibile",
        "m77_check" to "Controllo aggiornamenti",
        "m77_checking" to "Verifica…",
        "m77_desc" to "Info versione MSI, stato motore e controllo manifesto remoto.",
        "m77_hint" to "Manifesto remoto: github.com/finndev/msi-manifest (version.json).",
        "m77_module_versions" to "Moduli del motore",
        "m77_modules" to "Moduli",
        "m77_name" to "Verificatore Aggiornamenti e Versioni",
        "m77_offline" to "Nessuna rete o manifesto non disponibile",
        "m77_parse_error" to "Errore di formato del manifesto",
        "m77_up_to_date" to "Aggiornato",
        "m78_desc" to "Il centro di controllo MSI v4.0.0: panoramica di sistema e accesso a tutti i 78 moduli.",
        "m78_name" to "Dashboard Sistema Principale",
        "nav_home" to "Home",
        "nav_modules" to "Moduli",
        "nav_settings" to "Impostazioni",
        "nav_terminal" to "Terminale",
        "no" to "No",
        "ob_continue" to "Continua",
        "ob_lang_desc" to "L'intera interfaccia — tutti i 78 moduli, menu e pulsanti — cambierà all'istante.",
        "ob_lang_note" to "Puoi cambiare lingua in seguito nel modulo 73.",
        "ob_lang_title" to "Seleziona la tua lingua",
        "ob_perm_allfiles" to "Accesso a tutti i file (Android 11+)",
        "ob_perm_desc" to "MSI necessita dell'accesso all'archiviazione per gestire file, ISO, backup e log. I permessi vengono richiesti ora, prima di tutto.",
        "ob_perm_grant" to "Concedi permessi",
        "ob_perm_granted" to "concesso",
        "ob_perm_missing" to "mancante",
        "ob_perm_read" to "Leggi archiviazione esterna",
        "ob_perm_skip_warn" to "Alcuni moduli saranno limitati senza accesso all'archiviazione",
        "ob_perm_write" to "Scrivi archiviazione esterna",
        "ob_skip" to "Salta",
        "ob_start" to "Avvia MSI",
        "ob_welcome" to "Benvenuto in MSI",
        "open" to "Apri",
        "open_module" to "Apri modulo",
        "output" to "Output",
        "refresh" to "Aggiorna",
        "reset" to "Ripristina",
        "root_hint" to "concedi l'accesso root (Magisk / KernelSU / APatch) per abilitare questo modulo",
        "root_required" to "Root richiesto",
        "run" to "Esegui",
        "save" to "Salva",
        "scan" to "Scansiona",
        "scanning" to "Scansione…",
        "search_modules" to "Cerca tra 78 moduli…",
        "share" to "Condividi",
        "size" to "Dimensione",
        "start" to "Avvia",
        "stop" to "Ferma",
        "version" to "Versione",
        "yes" to "Sì",
    )
}
