package com.finndev.master.system.inspector.core

/** Generated MSI string table (English) — 728 keys. */
object LocDataEn {
    val data: Map<String, String> = mapOf(
        "abort" to "Abort",
        "about" to "About",
        "about_modules_count" to "{0} modules — all fully functional",
        "actions" to "Actions",
        "app_tagline" to "Ana Sistem Denetçisi — Master System Inspector",
        "apply" to "Apply",
        "cancel" to "Cancel",
        "cat_all" to "All",
        "cat_network" to "Network, Security & Diagnostics",
        "cat_root" to "Root & Kernel Tweaks",
        "cat_storage" to "Storage, ISO & Files",
        "cat_system" to "System Profiling & Utilities",
        "cat_terminal" to "Terminal, RootFS & Scripts",
        "check_updates" to "Check for updates",
        "clear" to "Clear",
        "confirm" to "Confirm",
        "copy" to "Copy",
        "current_language" to "Current language",
        "dash_all_modules" to "All modules (1–78)",
        "dash_android" to "Android",
        "dash_categories" to "Categories",
        "dash_quick" to "Quick actions",
        "dash_ram" to "RAM free",
        "dash_ram_sub" to "of {0} total",
        "dash_root" to "Root",
        "dash_root_no" to "Not rooted",
        "dash_root_unknown" to "checking…",
        "dash_root_yes" to "Rooted",
        "dash_storage" to "Storage free",
        "dash_storage_free" to "free",
        "dash_storage_sub" to "of {0}",
        "delete" to "Delete",
        "download" to "Download",
        "downloading" to "Downloading…",
        "empty_list" to "Nothing here yet",
        "error" to "Error",
        "export" to "Export",
        "filter" to "Filter",
        "input" to "Input",
        "m01_desc" to "Deep root detection: Magisk, KernelSU, APatch managers, su binaries and evidence log.",
        "m01_evidence" to "Detection evidence",
        "m01_manager" to "Root manager",
        "m01_name" to "Advanced Root Auditor",
        "m01_no_evidence" to "No root evidence found",
        "m01_su_path" to "su binary path",
        "m02_desc" to "Read and switch SELinux between Enforcing and Permissive via root.",
        "m02_name" to "SELinux Mode Switcher",
        "m02_set_enforcing" to "Set Enforcing",
        "m02_set_permissive" to "Set Permissive",
        "m02_warn" to "Permissive mode lowers security. Use only for debugging.",
        "m03_desc" to "Read, search and append system build properties with root write support.",
        "m03_edit" to "Append new property",
        "m03_hint" to "Properties are appended to /system/build.prop (system is remounted rw).",
        "m03_loaded" to "Loaded properties",
        "m03_name" to "Build.prop Live Editor",
        "m04_desc" to "List, run and install /system/etc/init.d startup scripts with root.",
        "m04_found" to "Installed scripts",
        "m04_hint" to "Script is base64-encoded to survive shell quoting; it runs at next boot.",
        "m04_install" to "Install",
        "m04_name" to "Init.d Script Runner",
        "m04_new" to "Install new script",
        "m04_none" to "No init.d scripts found (init.d support may be missing)",
        "m04_script" to "Script body",
        "m05_current" to "Current mount flags",
        "m05_desc" to "Remount /system and /vendor read-write or read-only with root.",
        "m05_hint" to "On system-as-root devices the / mount point is remounted instead.",
        "m05_name" to "System Partition Remounter",
        "m05_none" to "No system/vendor entries found",
        "m05_remount_ro" to "Remount RO",
        "m05_remount_rw" to "Remount RW",
        "m06_available" to "Available governors",
        "m06_current" to "Per-core status",
        "m06_desc" to "Profile per-core frequency and governor; switch governors on the fly.",
        "m06_name" to "CPU Governor Profiler",
        "m06_no_governors" to "Governor list not exposed by this kernel",
        "m07_cores" to "Cores",
        "m07_cpu0_note" to "CPU0 is the boot core and cannot be offlined.",
        "m07_desc" to "Online/offline CPU cores and clamp min/max scaling frequencies.",
        "m07_freq_limit" to "Frequency limits",
        "m07_limit_hint" to "Limits apply to all cpufreq policies as a percentage of hardware max.",
        "m07_max" to "Max frequency",
        "m07_min" to "Min frequency",
        "m07_name" to "CPU Hotplug & Frequency Limiter",
        "m07_offline" to "Offline",
        "m07_online" to "Online",
        "m08_current" to "Current LMK state",
        "m08_desc" to "Read and tune the lowmemorykiller minfree thresholds.",
        "m08_edit" to "Adjust minfree",
        "m08_hint" to "Values are kB per priority level, comma separated (6 levels).",
        "m08_lmk_missing" to "LMK not exposed (modern kernels use PSI/lmkd)",
        "m08_name" to "Low Memory Killer Tweaker",
        "m09_cycles" to "Cycle count",
        "m09_cycles_na" to "Android 14+ only",
        "m09_desc" to "Battery health, temperature, cycles and charging threshold control.",
        "m09_health" to "Health",
        "m09_level" to "Level",
        "m09_name" to "Battery Health & Charging Manager",
        "m09_now" to "Current battery",
        "m09_tech" to "Technology",
        "m09_temp" to "Temperature",
        "m09_threshold" to "Charging threshold",
        "m09_threshold_current" to "Current threshold",
        "m09_threshold_hint" to "e.g. 80 keeps the battery between 20-80% for longevity (supported devices).",
        "m09_threshold_na" to "not supported by kernel",
        "m09_threshold_new" to "New threshold (%)",
        "m09_voltage" to "Voltage",
        "m10_current" to "Current display overrides",
        "m10_density" to "Density (DPI)",
        "m10_desc" to "Override display resolution and density with wm size / wm density.",
        "m10_name" to "Screen Resolution & DPI Manipulator",
        "m10_size" to "Resolution",
        "m10_warn" to "Aggressive values can make the UI unreadable — Reset restores defaults.",
        "m11_apps" to "Installed apps",
        "m11_desc" to "Freeze, hide, uninstall (user 0) and restore system packages via pm.",
        "m11_enable" to "Enable",
        "m11_freeze" to "Freeze",
        "m11_hint" to "Uninstall uses 'pm uninstall --user 0' — reversible with Enable; the APK stays on disk.",
        "m11_name" to "Bloatware System App Freezer",
        "m11_restore" to "Restore a package",
        "m11_restore_pkg" to "package name",
        "m11_unhide" to "Unhide",
        "m11_uninstall" to "Uninstall",
        "m12_count" to "Sensors on this device",
        "m12_desc" to "Live stream of gyroscope, accelerometer, magnetometer and more.",
        "m12_name" to "Live Hardware Sensors Streamer",
        "m12_power" to "Power draw",
        "m12_range" to "Maximum range",
        "m12_resolution" to "Resolution",
        "m13_buffer" to "Buffer snapshot",
        "m13_desc" to "Read the kernel ring buffer and follow it live with dmesg -w.",
        "m13_empty" to "Buffer is empty or unreadable",
        "m13_follow" to "Start following",
        "m13_live" to "Live follow",
        "m13_name" to "Kernel Log (dmesg) Reader",
        "m13_read" to "Read buffer (root)",
        "m14_awake" to "Awake time",
        "m14_boot_id" to "Boot ID",
        "m14_deep" to "Deep sleep",
        "m14_desc" to "Uptime, deep-sleep share and boot event timeline.",
        "m14_name" to "Boot Stage & Startup Analyzer",
        "m14_no_log" to "No boot events available",
        "m14_stages" to "Boot events",
        "m14_stats" to "Boot statistics",
        "m14_uptime" to "Time since boot",
        "m15_cores" to "Threads",
        "m15_desc" to "SHA-256 CPU stress benchmark (single/multi) plus memory bandwidth test.",
        "m15_hint" to "Runs a 2s single-core, 2s all-core SHA-256 load and a 96 MB memory pass.",
        "m15_mem" to "Memory",
        "m15_multi" to "Multi-core",
        "m15_name" to "CPU & RAM Benchmark Tester",
        "m15_running" to "Benchmarking…",
        "m15_scores" to "Benchmark scores",
        "m15_single" to "Single-core",
        "m16_apk_update" to "apk update && upgrade",
        "m16_bootstrapping" to "bootstrapping",
        "m16_desc" to "Genuine Alpine Linux rootfs via PRoot inside app storage — with full apk package management.",
        "m16_exited" to "exited",
        "m16_hint" to "Try: apk update • apk add python3 • cat /etc/alpine-release",
        "m16_idle" to "idle",
        "m16_input_hint" to "type a command and press Send",
        "m16_name" to "True Alpine Linux PRoot Terminal",
        "m16_restart" to "Restart session",
        "m16_running" to "running",
        "m16_share_log" to "Share transcript",
        "m16_state" to "Session",
        "m16_stop" to "Stop session",
        "m17_clone" to "Clone repository (depth 1)",
        "m17_desc" to "Detects com.termux, launches it and clones Git repositories via Alpine git.",
        "m17_git" to "Git cloner",
        "m17_git_hint" to "Repositories are cloned into /sdcard/MSI/GitRepos using the bundled Alpine git.",
        "m17_installed" to "installed",
        "m17_launch" to "Launch Termux",
        "m17_name" to "Termux Integration & Git Cloner",
        "m17_not_installed" to "not installed",
        "m18_arch" to "Architecture",
        "m18_config" to "Machine configuration",
        "m18_create_disk" to "Create qcow2 disk",
        "m18_desc" to "Install and launch QEMU (x86_64 / i386 / aarch64) machines inside the Alpine rootfs.",
        "m18_disk" to "Disk size (GB)",
        "m18_hint" to "QEMU runs headless with serial console; the ISO path points to a file under /sdcard.",
        "m18_install" to "Install QEMU (apk)",
        "m18_launch" to "Launch in terminal",
        "m18_name" to "QEMU Multi-Architecture Emulator",
        "m18_ram" to "Memory",
        "m19_bash_note" to "bash is installed on demand inside the Alpine rootfs (apk add bash).",
        "m19_desc" to "Run .sh scripts with live output via Alpine /bin/sh, Alpine bash or Android sh.",
        "m19_engine" to "Script engine",
        "m19_name" to "Bash & Shell Script Runner",
        "m19_running" to "Running…",
        "m19_script" to "Script",
        "m20_args" to "Arguments",
        "m20_compat" to "Device compatibility",
        "m20_compat_no" to "incompatible ABI",
        "m20_compat_yes" to "compatible",
        "m20_desc" to "Inspect and directly execute ARM/x86 binaries with root.",
        "m20_hint" to "chmod +x is applied automatically; binaries execute via su.",
        "m20_inspect" to "Inspect ELF",
        "m20_name" to "Native ELF Binary Runner",
        "m20_not_elf" to "Not an ELF file",
        "m20_path" to "Binary path",
        "m20_pick" to "Binary",
        "m21_code" to "Code",
        "m21_desc" to "Run Python 3 and Lua 5.4 scripts inside the Alpine rootfs — real interpreters.",
        "m21_in_terminal" to "Open interactive in terminal",
        "m21_install" to "Install via apk",
        "m21_installed" to "ready",
        "m21_lang" to "Language",
        "m21_name" to "Python & Lua Interpreter",
        "m21_not_installed" to "not installed yet",
        "m21_running" to "Executing…",
        "m21_runtime" to "Runtime",
        "m22_analyze" to "Analyze",
        "m22_desc" to "Full ELF header inspection: class, endianness, machine, entry point, PT_INTERP.",
        "m22_invalid" to "Invalid ELF",
        "m22_list" to "List directory",
        "m22_listing" to "Directory listing",
        "m22_machine" to "Machine",
        "m22_name" to "ELF Binary Deep Analyzer",
        "m22_no_dir" to "Directory not readable",
        "m22_pick" to "An ELF file",
        "m22_type" to "Type",
        "m23_desc" to "chmod / chown any file via root with live stat display.",
        "m23_mode" to "Mode (octal)",
        "m23_name" to "File Permission Manager",
        "m23_stat" to "Current status",
        "m24_custom" to "Custom PATH entries",
        "m24_desc" to "Inspect the MSI shell PATH and add custom directories.",
        "m24_extra" to "Extra directories (colon separated)",
        "m24_hint" to "Applied to every MSI shell session and the PRoot environment.",
        "m24_name" to "Environment PATH Manager",
        "m25_applets" to "Applets",
        "m25_desc" to "Detect busybox, list its applets and install busybox-static via Alpine.",
        "m25_detect" to "Detection",
        "m25_install" to "Install busybox-static",
        "m25_install_btn" to "Install",
        "m25_install_hint" to "The static binary is exported to /sdcard/MSI/busybox via the Alpine package manager.",
        "m25_name" to "Busybox Integration & Validator",
        "m25_not_found" to "not found",
        "m26_actions" to "Emergency actions",
        "m26_confirm" to "Execute this command?",
        "m26_custom" to "Custom command (su)",
        "m26_desc" to "Curated emergency commands: fix permissions, trim caches, remount, reboot.",
        "m26_name" to "Emergency Recovery Console",
        "m27_builder" to "Macro builder",
        "m27_desc" to "Chain shell commands with delays into saved, one-tap macros.",
        "m27_format" to "One step per line: command|delay_ms — prefix '#root ' to force su",
        "m27_name" to "Macro name",
        "m27_none" to "No macros yet",
        "m27_saved" to "Saved macros",
        "m27_steps" to "Steps",
        "m28_current" to "Current session transcript",
        "m28_desc" to "Save the terminal transcript and session logs as .txt / .log files.",
        "m28_hint" to "Files are stored in app-private logs and can be shared anywhere.",
        "m28_lines" to "Lines",
        "m28_name" to "Terminal Output Log Exporter",
        "m28_none" to "No logs saved yet",
        "m28_saved" to "Saved logs",
        "m29_desc" to "Write notes with instant markdown preview, stored in internal storage.",
        "m29_edit" to "Edit",
        "m29_hint" to "Supports # headings, **bold**, `code`, lists and code blocks.",
        "m29_name" to "Offline Markdown Note Editor",
        "m29_new" to "New note",
        "m29_none" to "No notes yet",
        "m29_notes" to "Notes",
        "m29_preview" to "Preview",
        "m30_desc" to "Scan any barcode format and generate QR codes with export.",
        "m30_generate" to "Generator",
        "m30_generate_btn" to "Generate QR",
        "m30_name" to "QR Code & Barcode Scanner",
        "m30_result" to "Result",
        "m30_save" to "Save to Downloads",
        "m30_scan" to "Scanner",
        "m30_scan_btn" to "Scan barcode",
        "m30_scan_cancel" to "Scan cancelled",
        "m31_bytes" to "Bytes",
        "m31_desc" to "Convert text between Base64, hexadecimal and binary — plus file hashing.",
        "m31_file" to "File mode (≤ 8 MB)",
        "m31_file_b64" to "Encode file to Base64",
        "m31_file_limit" to "File too large or missing (limit 8 MB)",
        "m31_invalid_b64" to "Invalid Base64 input",
        "m31_invalid_bin" to "Invalid binary input",
        "m31_invalid_hex" to "Invalid hex input",
        "m31_mode" to "Conversion mode",
        "m31_name" to "Base64, Hex & Binary Encoder",
        "m32_desc" to "Pretty-print, validate and format JSON and XML documents.",
        "m32_format" to "Format & validate",
        "m32_invalid" to "Invalid",
        "m32_invalid_json" to "Invalid JSON",
        "m32_invalid_xml" to "Invalid XML",
        "m32_mode" to "Format",
        "m32_name" to "JSON & XML Formatter",
        "m32_valid" to "Valid document",
        "m33_add" to "Add entry",
        "m33_desc" to "AES-256-GCM vault with PBKDF2 key derivation — fully offline.",
        "m33_empty" to "Vault is empty",
        "m33_entries" to "Entries",
        "m33_gen" to "Generate",
        "m33_hint" to "The vault is encrypted with AES-GCM; the key never leaves the device.",
        "m33_lock" to "Lock vault",
        "m33_master" to "Master password",
        "m33_name" to "Offline Encrypted Password Manager",
        "m33_pass" to "Password",
        "m33_short_pwd" to "Master password must be at least 4 characters",
        "m33_title" to "Title",
        "m33_unlock" to "Vault",
        "m33_unlock_btn" to "Unlock / create vault",
        "m33_user" to "Username / email",
        "m33_wrong_pwd" to "Wrong master password",
        "m34_desc" to "Sweep the /24 subnet for live hosts and resolve MAC addresses.",
        "m34_found" to "Discovered devices",
        "m34_hint" to "254 hosts are probed in parallel; MAC comes from the ARP table.",
        "m34_name" to "LAN IP & MAC Device Scanner",
        "m34_none" to "No devices found",
        "m34_scan" to "Scan subnet",
        "m34_scanning" to "Scanning…",
        "m34_subnet" to "Subnet (x.x.x.)",
        "m35_closed" to "closed",
        "m35_desc" to "Check TCP and UDP ports on any host with parallel sockets.",
        "m35_filtered" to "no response",
        "m35_host" to "Host",
        "m35_name" to "Port Scanner (TCP/UDP)",
        "m35_none" to "Scan a target first",
        "m35_open" to "OPEN",
        "m35_ports" to "Ports",
        "m35_target" to "Target",
        "m35_udp_hint" to "UDP 'no response' usually means open-or-filtered (no ICMP error received).",
        "m36_count" to "Count",
        "m36_desc" to "Continuous ping with per-reply latency chart and min/avg/max stats.",
        "m36_name" to "Advanced Ping & Latency Monitor",
        "m36_start" to "Start ping",
        "m36_target" to "Ping target",
        "m37_adguard" to "AdGuard (ad-blocking)",
        "m37_auto" to "Automatic (opportunistic)",
        "m37_cloudflare" to "Cloudflare (1.1.1.1)",
        "m37_current" to "Current Private DNS",
        "m37_custom" to "Custom hostname",
        "m37_desc" to "Enforce Private DNS (DoT) presets: Cloudflare, Google, AdGuard, Quad9.",
        "m37_google" to "Google (8.8.8.8)",
        "m37_hint" to "Applies Android Private DNS over TLS via the settings provider (root).",
        "m37_name" to "Custom DNS Enforcer (Root)",
        "m37_off" to "Disable Private DNS",
        "m37_presets" to "Presets",
        "m37_quad9" to "Quad9 (security)",
        "m38_add_rule" to "Add rule",
        "m38_allow" to "Allow (remove)",
        "m38_block" to "Block port",
        "m38_desc" to "Inspect iptables chains and add/remove port block rules via root.",
        "m38_hint" to "Rules use REJECT on the selected chain; nftables ruleset is shown when present.",
        "m38_ipt_unavailable" to "iptables unavailable or blocked",
        "m38_name" to "Firewall Rule Manager",
        "m38_nft" to "nftables",
        "m38_nft_available" to "available",
        "m38_nft_missing" to "not available",
        "m39_desc" to "Netstat-style live table of TCP/UDP endpoints mapped to apps.",
        "m39_hint" to "Reads /proc/net/tcp, tcp6, udp and udp6; UIDs are resolved to app packages.",
        "m39_name" to "Active Network Socket Inspector",
        "m39_none" to "No sockets readable",
        "m39_sockets" to "Sockets",
        "m39_table" to "Endpoint table",
        "m40_desc" to "Latency, download and upload measurement against Cloudflare.",
        "m40_down" to "Download",
        "m40_hint" to "Downloads 25 MB and uploads 10 MB — watch your data plan.",
        "m40_latency" to "Latency",
        "m40_name" to "Internet Bandwidth Speed Test",
        "m40_results" to "Results",
        "m40_running" to "Measuring…",
        "m40_start" to "Start speed test",
        "m40_up" to "Upload",
        "m41_desc" to "Change the MAC address of any interface with random or custom values.",
        "m41_hint" to "Wi-Fi must reconnect after changing wlan0; some drivers reject custom MACs.",
        "m41_iface" to "Interface",
        "m41_interfaces" to "Interfaces",
        "m41_invalid_mac" to "Invalid MAC format",
        "m41_name" to "MAC Address Spoofing (Root)",
        "m41_new_mac" to "New MAC",
        "m41_random" to "Random",
        "m41_spoof" to "Spoof",
        "m42_channel" to "Channel",
        "m42_congestion" to "Channel congestion",
        "m42_current" to "Current connection",
        "m42_desc" to "Signal strength, link data, channel congestion and nearby networks.",
        "m42_freq" to "Frequency",
        "m42_grant" to "Grant location",
        "m42_level" to "Level",
        "m42_location" to "Location permission",
        "m42_location_hint" to "Android requires location permission to expose scan results.",
        "m42_name" to "Wi-Fi Signal & Channel Analyzer",
        "m42_networks" to "Nearby networks",
        "m42_rssi" to "Signal (RSSI)",
        "m43_cert" to "Certificate",
        "m43_chain" to "Chain",
        "m43_cipher" to "Cipher suite",
        "m43_desc" to "Handshake a TLS connection and inspect the full certificate chain.",
        "m43_expired" to "EXPIRED",
        "m43_inspect" to "Inspect",
        "m43_name" to "SSL Certificate & TLS Inspection",
        "m43_status" to "Validity",
        "m43_target" to "Host (port 443)",
        "m43_tls_version" to "TLS version",
        "m43_valid" to "valid",
        "m43_valid_from" to "Valid from",
        "m43_valid_to" to "Valid until",
        "m44_connections" to "Tracked connections",
        "m44_desc" to "Connection-open/close tracking with per-app traffic accounting.",
        "m44_hint" to "Polls the kernel socket tables and diffs them; RX/TX deltas come from TrafficStats.",
        "m44_log" to "Event log",
        "m44_name" to "Packet Sniffer & Traffic Logger",
        "m44_start" to "Start tracking",
        "m44_status" to "Status",
        "m45_ap" to "Tethering state",
        "m45_ap_off" to "Hotspot appears inactive",
        "m45_clients" to "Connected clients",
        "m45_desc" to "Show tethering state and connected hotspot clients (ARP based).",
        "m45_hint" to "Clients are derived from the ARP table while the hotspot is up.",
        "m45_name" to "Hotspot & Tethering Inspector",
        "m45_no_clients" to "No clients connected",
        "m46_answer" to "Your answer",
        "m46_bench" to "Test bench",
        "m46_challenge" to "Challenge",
        "m46_desc" to "Generate distorted local captchas and benchmark pass/fail rates.",
        "m46_fail" to "FAILED",
        "m46_log" to "Attempt log",
        "m46_name" to "Captcha & Bot Filtering Bench",
        "m46_new" to "New challenge",
        "m46_pass" to "PASSED",
        "m46_stats" to "Solved / failed",
        "m46_verify" to "Verify",
        "m47_desc" to "SecureRandom passwords, hex tokens, UUIDs and passphrases.",
        "m47_hint" to "All entropy comes from the platform SecureRandom generator.",
        "m47_length" to "Length",
        "m47_mode" to "Mode",
        "m47_name" to "Secure Password & Token Generator",
        "m47_passphrase" to "Passphrase",
        "m47_password" to "Password",
        "m47_regenerate" to "Regenerate",
        "m47_results" to "Generated",
        "m48_confirm" to "This permanently destroys the data. Continue?",
        "m48_desc" to "Overwrite files with multiple random passes before deletion.",
        "m48_exists" to "Exists",
        "m48_hint" to "1-7 random passes + final zero pass; directories are shredded recursively.",
        "m48_name" to "Sensitive File Shredder",
        "m48_passes" to "Passes",
        "m48_running" to "Shredding…",
        "m48_shred" to "Shred permanently",
        "m48_target" to "Target",
        "m49_desc" to "Test regular expressions with live match and replace preview.",
        "m49_input" to "Test text",
        "m49_matches" to "Matches",
        "m49_name" to "Regex Pattern Workbench",
        "m49_pattern" to "Pattern",
        "m49_replace" to "Replace preview",
        "m49_with" to "Replace with",
        "m50_add_palette" to "Add to palette",
        "m50_clear" to "Clear palette",
        "m50_current" to "Current color",
        "m50_desc" to "Interactive HSL color picker with HEX / RGB codes and palette storage.",
        "m50_dials" to "Controls",
        "m50_hex_input" to "From HEX",
        "m50_hue" to "Hue",
        "m50_lum" to "Lightness",
        "m50_name" to "Color Palette & HEX/RGB Picker",
        "m50_palette" to "Palette",
        "m50_sat" to "Saturation",
        "m51_arch" to "Architecture",
        "m51_config" to "Download",
        "m51_desc" to "Architecture-selectable ISO downloader with resume, progress and SHA-256.",
        "m51_dest" to "Destination",
        "m51_name" to "ValiantCore ISO Downloader",
        "m51_sha256" to "Compute SHA-256",
        "m51_verify" to "Hash check",
        "m51_verify_hint" to "Compare the computed digest against the source you trust.",
        "m52_config" to "Server configuration",
        "m52_desc" to "Serve any folder over HTTP on the LAN with a styled directory index.",
        "m52_dir" to "Shared directory",
        "m52_hint" to "Runs as a data-sync foreground service; supports Range requests for media.",
        "m52_log" to "Request log",
        "m52_log_empty" to "No requests yet",
        "m52_name" to "Local HTTP File Sharing Server",
        "m52_port" to "Port",
        "m52_running" to "running",
        "m52_served" to "Requests served",
        "m52_start" to "Start server",
        "m52_status" to "Status",
        "m52_stopped" to "stopped",
        "m53_all" to "Bulk backup",
        "m53_apps" to "Installed packages",
        "m53_backup_user_apps" to "Backup all user apps",
        "m53_desc" to "Copy installed APKs to storage — single apps or all user apps at once.",
        "m53_hint" to "Backups are written to /sdcard/MSI/APKBackups.",
        "m53_name" to "APK Backup & Package Extractor",
        "m54_clean_own" to "Clean own caches",
        "m54_cleaning" to "Cleaning…",
        "m54_deep_clean" to "Deep clean app caches",
        "m54_desc" to "Clean own caches, trim system caches and deep-clean app caches (root).",
        "m54_freed" to "Freed",
        "m54_name" to "Deep Storage & Cache Cleaner",
        "m54_own" to "MSI caches",
        "m54_own_cache" to "Own cache size",
        "m54_system" to "System (root)",
        "m54_system_hint" to "pm trim-caches frees cache from all apps; deep clean wipes /data/data/*/cache.",
        "m54_trim_caches" to "Trim caches (pm)",
        "m55_desc" to "MD5 / SHA-1 / SHA-256 digests with expected-hash comparison.",
        "m55_expected" to "Expected digest",
        "m55_file" to "File",
        "m55_hash" to "Compute hash",
        "m55_match" to "HASH MATCH",
        "m55_mismatch" to "HASH MISMATCH",
        "m55_name" to "ISO & Binary Hash Verifier",
        "m55_quick" to "Quick pick",
        "m55_verify" to "Verify",
        "m56_desc" to "Locate the largest files hogging your storage.",
        "m56_files" to "files",
        "m56_min_size" to "Min size (MB)",
        "m56_name" to "Storage Hog Hunter",
        "m56_none" to "No files over the threshold",
        "m56_results" to "Largest files",
        "m56_root" to "Scan root",
        "m56_scan" to "Hunt",
        "m56_total" to "Total",
        "m57_archive_path" to "Archive path",
        "m57_create" to "Create archive",
        "m57_desc" to "Create and extract .zip and .tar.gz archives with progress log.",
        "m57_extract" to "Extract",
        "m57_name" to "Archive name",
        "m57_pack" to "Pack",
        "m57_source_dir" to "Source directory",
        "m57_unpack" to "Unpack",
        "m57_working" to "Working…",
        "m58_active" to "Active & recent transfers",
        "m58_add" to "Add transfer",
        "m58_desc" to "Queue downloads with live per-transfer progress (2 concurrent).",
        "m58_enqueue" to "Enqueue",
        "m58_hint" to "Files land in /sdcard/MSI/Downloads.",
        "m58_name" to "Download Queue & Transfer Tracker",
        "m58_none" to "No transfers yet",
        "m59_clear" to "Clear history",
        "m59_desc" to "Watch the clipboard, keep history and save reusable snippets.",
        "m59_history" to "Clipboard history",
        "m59_name" to "Clipboard History & Snippets",
        "m59_none" to "Nothing copied yet",
        "m59_paused" to "Paused",
        "m59_save_snippet" to "Save snippet",
        "m59_snippets" to "Snippets",
        "m59_watching" to "Watching clipboard",
        "m60_desc" to "Full diagnostic report: hardware, memory, storage, logcat and dmesg.",
        "m60_generate" to "Generate report",
        "m60_name" to "System Log & Diagnostic Exporter",
        "m60_preview" to "Preview",
        "m60_report" to "Report",
        "m60_save" to "Save to Downloads",
        "m61_confirm" to "The system partition is remounted rw and Roboto-Regular is backed up. Continue?",
        "m61_current" to "Current fonts (sample)",
        "m61_desc" to "Install a custom TTF into /system/fonts with backup and restore.",
        "m61_font_path" to "TTF path",
        "m61_hint" to "Font is copied as /system/fonts/MSICustom-Regular.ttf (644).",
        "m61_install" to "Install font",
        "m61_install_btn" to "Install as MSICustom",
        "m61_name" to "System Font Customizer (Root)",
        "m61_not_ttf" to "Selected file is not a .ttf",
        "m61_restore" to "Restore",
        "m61_restore_btn" to "Remove custom font",
        "m62_confirm" to "The current bootanimation is backed up to /sdcard/MSI. Continue?",
        "m62_current" to "Current media",
        "m62_desc" to "Validate and install bootanimation.zip to /system/media.",
        "m62_hint" to "A bootanimation.zip must contain desc.txt and part folders.",
        "m62_install" to "Install",
        "m62_install_btn" to "Install bootanimation",
        "m62_invalid_zip" to "Invalid: missing desc.txt",
        "m62_name" to "Bootanimation Customizer (Root)",
        "m62_no_file" to "File not found",
        "m62_restore" to "Restore",
        "m62_restore_btn" to "Restore backup",
        "m62_valid_zip" to "Valid bootanimation structure (desc.txt found)",
        "m62_validate" to "Validate zip",
        "m62_zip_path" to "bootanimation.zip path",
        "m63_action" to "Tile action",
        "m63_action_desc" to "Opens the Alpine terminal session",
        "m63_added" to "added to the shade",
        "m63_desc" to "QS tile that opens the MSI terminal instantly from the shade.",
        "m63_howto" to "Pull down the shade, edit tiles and drag 'MSI Terminal' into place.",
        "m63_name" to "Quick Settings Tile Integration",
        "m63_not_added" to "not added yet",
        "m63_notification" to "Notifications",
        "m63_open_terminal" to "Simulate tile tap",
        "m63_state" to "Tile state",
        "m63_test_notification" to "Send test notification",
        "m63_tile" to "Tile",
        "m64_clear" to "Clear crashes",
        "m64_crashes" to "Recorded crashes",
        "m64_desc" to "Collect crash logs, logcat and diagnostics into a shareable zip.",
        "m64_hint" to "The zip contains crash logs, logcat, dmesg and the diagnostic report.",
        "m64_name" to "Debug Support & Crash Packager",
        "m64_none" to "No crashes recorded",
        "m64_package" to "Support package",
        "m64_view" to "View latest",
        "m64_zip" to "Build debug zip",
        "m65_caches" to "Cache topology",
        "m65_cores" to "Cores",
        "m65_desc" to "SoC, CPU topology, caches, GPU, memory and storage in one panel.",
        "m65_device" to "Device",
        "m65_freqs" to "Live frequencies",
        "m65_name" to "Advanced Hardware Profiler",
        "m65_no_caches" to "Cache sysfs not exposed",
        "m65_soc" to "SoC",
        "m66_available" to "Available",
        "m66_desc" to "Live memory, swap and zram usage with history graph.",
        "m66_details" to "Details",
        "m66_name" to "Real-time RAM & Swap Monitor",
        "m66_ram" to "RAM",
        "m66_total" to "Total",
        "m66_used" to "Used",
        "m67_all" to "All apps",
        "m67_apps" to "Packages",
        "m67_desc" to "Every installed package with one-tap package-name copy.",
        "m67_installed_at" to "Installed",
        "m67_name" to "Installed Package Inspector",
        "m67_search" to "Search apps",
        "m67_system" to "System only",
        "m68_desc" to "Live process table with RSS memory and root kill support.",
        "m68_kill" to "Kill",
        "m68_name" to "Background Processes Manager",
        "m68_processes" to "Processes",
        "m69_desc" to "Stream logcat live with level and text filters (root for all apps).",
        "m69_empty" to "Not streaming",
        "m69_filter" to "Filter",
        "m69_hint" to "root mode reads the global buffer; user mode only shows MSI's own logs.",
        "m69_name" to "System Logcat Live Stream",
        "m69_start" to "Start stream",
        "m70_desc" to "Full mount table with filesystem types, RO flags and usage bars.",
        "m70_mounts" to "Mounts",
        "m70_name" to "Mount Points & Disk Usage",
        "m70_none" to "df unavailable",
        "m71_battery" to "Battery",
        "m71_desc" to "Thermal zones, battery temperature and throttling trend.",
        "m71_hint" to "Zone names are kernel-provided; ≥ 60 °C indicates heavy throttling territory.",
        "m71_name" to "CPU Thermal Inspector",
        "m71_zones" to "Thermal zones",
        "m72_desc" to "Precision stopwatch with laps and a countdown timer with alarm.",
        "m72_lap" to "Lap",
        "m72_name" to "Timer, Stopwatch & Chronometer",
        "m72_stopwatch" to "Stopwatch",
        "m72_timer" to "Timer",
        "m73_desc" to "Switch the entire interface between TR, EN, ES, FR and IT instantly.",
        "m73_hint" to "Switching is instant — no restart, no reload.",
        "m73_name" to "Multi-Language Engine",
        "m73_status" to "Engine status",
        "m74_active" to "active",
        "m74_classic" to "Classic Utility",
        "m74_desc" to "Three live themes: Material 3, Hacker/Cyberpunk and Classic Utility.",
        "m74_name" to "Dynamic UI Theme Engine",
        "m74_preview" to "Live preview",
        "m74_select" to "Theme",
        "m75_desc" to "Install, update, verify or remove the Alpine rootfs and monitor the engine.",
        "m75_hint" to "The minirootfs is bundled for offline install; update fetches the latest 3.21.x release.",
        "m75_install" to "Bootstrap rootfs",
        "m75_log" to "Engine log",
        "m75_name" to "Alpine Rootfs Bootstrap Status",
        "m75_not_ready" to "NOT INSTALLED",
        "m75_path" to "Location",
        "m75_ready" to "READY",
        "m75_remove" to "Remove rootfs",
        "m75_status" to "Rootfs status",
        "m75_update" to "Re-download & update",
        "m75_verified" to "SHA-256 verified",
        "m76_check" to "Check binary",
        "m76_desc" to "Match a binary's ELF machine type against this device's supported ABIs.",
        "m76_device" to "Device ABIs",
        "m76_hint" to "Useful before running downloaded binaries on exotic devices and emulators.",
        "m76_match" to "Match",
        "m76_name" to "Native ELF Architecture Matcher",
        "m76_will_run" to "This binary will run on this device",
        "m76_wont_run" to "Architecture mismatch — will NOT run",
        "m77_app" to "App",
        "m77_available" to "update available",
        "m77_check" to "Update check",
        "m77_checking" to "Checking…",
        "m77_desc" to "MSI version info, engine status and remote update manifest check.",
        "m77_hint" to "Remote manifest: github.com/finndev/msi-manifest (version.json).",
        "m77_module_versions" to "Engine modules",
        "m77_modules" to "Modules",
        "m77_name" to "App Update & Version Checker",
        "m77_offline" to "No network or manifest unavailable",
        "m77_parse_error" to "Manifest format error",
        "m77_up_to_date" to "Up to date",
        "m78_desc" to "The MSI v4.0.0 control center: system overview and gateway to all 78 modules.",
        "m78_name" to "Master System Dashboard",
        "nav_home" to "Home",
        "nav_modules" to "Modules",
        "nav_settings" to "Settings",
        "nav_terminal" to "Terminal",
        "no" to "No",
        "ob_continue" to "Continue",
        "ob_lang_desc" to "The entire interface — all 78 modules, menus and buttons — will switch instantly.",
        "ob_lang_note" to "You can change the language later in module 73.",
        "ob_lang_title" to "Please select your language",
        "ob_perm_allfiles" to "All files access (Android 11+)",
        "ob_perm_desc" to "MSI needs storage access to manage files, ISOs, backups and logs. Storage permissions are requested now, before anything else.",
        "ob_perm_grant" to "Grant permissions",
        "ob_perm_granted" to "granted",
        "ob_perm_missing" to "missing",
        "ob_perm_read" to "Read external storage",
        "ob_perm_skip_warn" to "Some modules will be limited without storage access",
        "ob_perm_write" to "Write external storage",
        "ob_skip" to "Skip",
        "ob_start" to "Start MSI",
        "ob_welcome" to "Welcome to MSI",
        "open" to "Open",
        "open_module" to "Open module",
        "output" to "Output",
        "refresh" to "Refresh",
        "reset" to "Reset",
        "root_hint" to "grant root access (Magisk / KernelSU / APatch) to enable this module",
        "root_required" to "Root required",
        "run" to "Run",
        "save" to "Save",
        "scan" to "Scan",
        "scanning" to "Scanning…",
        "search_modules" to "Search 78 modules…",
        "share" to "Share",
        "size" to "Size",
        "start" to "Start",
        "stop" to "Stop",
        "version" to "Version",
        "yes" to "Yes",
    )
}
