package com.finndev.master.system.inspector.core

/** Generated MSI string table (French) — 728 keys. */
object LocDataFr {
    val data: Map<String, String> = mapOf(
        "abort" to "Abandonner",
        "about" to "À propos",
        "about_modules_count" to "{0} modules — tous entièrement fonctionnels",
        "actions" to "Actions",
        "app_tagline" to "Ana Sistem Denetçisi — Master System Inspector",
        "apply" to "Appliquer",
        "cancel" to "Annuler",
        "cat_all" to "Tous",
        "cat_network" to "Réseau, Sécurité et Diagnostic",
        "cat_root" to "Root et Noyau",
        "cat_storage" to "Stockage, ISO et Fichiers",
        "cat_system" to "Profilage Système et Utilitaires",
        "cat_terminal" to "Terminal, RootFS et Scripts",
        "check_updates" to "Vérifier les mises à jour",
        "clear" to "Effacer",
        "confirm" to "Confirmer",
        "copy" to "Copier",
        "current_language" to "Langue actuelle",
        "dash_all_modules" to "Tous les modules (1–78)",
        "dash_android" to "Android",
        "dash_categories" to "Catégories",
        "dash_quick" to "Actions rapides",
        "dash_ram" to "RAM libre",
        "dash_ram_sub" to "sur {0} au total",
        "dash_root" to "Root",
        "dash_root_no" to "Non rooté",
        "dash_root_unknown" to "vérification…",
        "dash_root_yes" to "Rooté",
        "dash_storage" to "Stockage libre",
        "dash_storage_free" to "libre",
        "dash_storage_sub" to "sur {0}",
        "delete" to "Supprimer",
        "download" to "Télécharger",
        "downloading" to "Téléchargement…",
        "empty_list" to "Rien ici pour le moment",
        "error" to "Erreur",
        "export" to "Exporter",
        "filter" to "Filtrer",
        "input" to "Entrée",
        "m01_desc" to "Détection root approfondie : gestionnaires Magisk, KernelSU, APatch, binaires su et journal de preuves.",
        "m01_evidence" to "Preuves de détection",
        "m01_manager" to "Gestionnaire root",
        "m01_name" to "Auditeur Root Avancé",
        "m01_no_evidence" to "Aucune preuve de root trouvée",
        "m01_su_path" to "Chemin du binaire su",
        "m02_desc" to "Lit et bascule SELinux entre Enforcing et Permissive via root.",
        "m02_name" to "Basculeur de Mode SELinux",
        "m02_set_enforcing" to "Passer en Enforcing",
        "m02_set_permissive" to "Passer en Permissive",
        "m02_warn" to "Le mode Permissive réduit la sécurité. À réserver au débogage.",
        "m03_desc" to "Lisez, cherchez et ajoutez des propriétés système avec écriture root.",
        "m03_edit" to "Ajouter une propriété",
        "m03_hint" to "Les propriétés sont ajoutées à /system/build.prop (le système est remonté rw).",
        "m03_loaded" to "Propriétés chargées",
        "m03_name" to "Éditeur Build.prop en Direct",
        "m04_desc" to "Liste, exécute et installe des scripts /system/etc/init.d avec root.",
        "m04_found" to "Scripts installés",
        "m04_hint" to "Le script est encodé en base64 pour survivre au quoting ; il s'exécute au prochain démarrage.",
        "m04_install" to "Installer",
        "m04_name" to "Lanceur de Scripts Init.d",
        "m04_new" to "Installer un nouveau script",
        "m04_none" to "Aucun script init.d (le support init.d peut manquer)",
        "m04_script" to "Contenu du script",
        "m05_current" to "Indicateurs de montage actuels",
        "m05_desc" to "Remonte /system et /vendor en lecture-écriture ou lecture seule via root.",
        "m05_hint" to "Sur les appareils system-as-root, le point / est remonté à la place.",
        "m05_name" to "Remonteur de Partitions Système",
        "m05_none" to "Aucune entrée system/vendor trouvée",
        "m05_remount_ro" to "Remonter RO",
        "m05_remount_rw" to "Remonter RW",
        "m06_available" to "Gouverneurs disponibles",
        "m06_current" to "État par cœur",
        "m06_desc" to "Profil de fréquence par cœur et gouverneur ; changez de gouverneur à la volée.",
        "m06_name" to "Profileur de Gouverneur CPU",
        "m06_no_governors" to "Le noyau n'expose pas la liste des gouverneurs",
        "m07_cores" to "Cœurs",
        "m07_cpu0_note" to "CPU0 est le cœur de démarrage et ne peut pas être désactivé.",
        "m07_desc" to "Active/désactive les cœurs CPU et borne les fréquences min/max.",
        "m07_freq_limit" to "Limites de fréquence",
        "m07_limit_hint" to "Les limites s'appliquent à toutes les politiques cpufreq en pourcentage du maximum matériel.",
        "m07_max" to "Fréquence maximale",
        "m07_min" to "Fréquence minimale",
        "m07_name" to "Hotplug CPU et Limiteur de Fréquence",
        "m07_offline" to "Désactiver",
        "m07_online" to "Activer",
        "m08_current" to "État LMK actuel",
        "m08_desc" to "Lit et règle les seuils minfree du lowmemorykiller.",
        "m08_edit" to "Ajuster minfree",
        "m08_hint" to "Valeurs en kB par niveau de priorité, séparées par des virgules (6 niveaux).",
        "m08_lmk_missing" to "LMK non exposé (les noyaux modernes utilisent PSI/lmkd)",
        "m08_name" to "Ajusteur du Low Memory Killer",
        "m09_cycles" to "Nombre de cycles",
        "m09_cycles_na" to "Android 14+ uniquement",
        "m09_desc" to "Santé de la batterie, température, cycles et contrôle du seuil de charge.",
        "m09_health" to "Santé",
        "m09_level" to "Niveau",
        "m09_name" to "Gestionnaire Batterie et Charge",
        "m09_now" to "Batterie actuelle",
        "m09_tech" to "Technologie",
        "m09_temp" to "Température",
        "m09_threshold" to "Seuil de charge",
        "m09_threshold_current" to "Seuil actuel",
        "m09_threshold_hint" to "ex. 80 garde la batterie entre 20 et 80 % pour la longévité (appareils compatibles).",
        "m09_threshold_na" to "non pris en charge par le noyau",
        "m09_threshold_new" to "Nouveau seuil (%)",
        "m09_voltage" to "Tension",
        "m10_current" to "Remplacements d'écran actuels",
        "m10_density" to "Densité (DPI)",
        "m10_desc" to "Remplace la résolution et la densité d'écran via wm size / wm density.",
        "m10_name" to "Manipulateur de Résolution et DPI",
        "m10_size" to "Résolution",
        "m10_warn" to "Des valeurs extrêmes peuvent rendre l'UI illisible — Réinitialiser restaure les défauts.",
        "m11_apps" to "Applications installées",
        "m11_desc" to "Gele, masque, désinstalle (user 0) et restaure des paquets système via pm.",
        "m11_enable" to "Activer",
        "m11_freeze" to "Geler",
        "m11_hint" to "La désinstallation utilise 'pm uninstall --user 0' — réversible avec Activer ; l'APA reste sur disque.",
        "m11_name" to "Congélateur d'Apps Système",
        "m11_restore" to "Restaurer un paquet",
        "m11_restore_pkg" to "nom du paquet",
        "m11_unhide" to "Afficher",
        "m11_uninstall" to "Désinstaller",
        "m12_count" to "Capteurs sur cet appareil",
        "m12_desc" to "Flux en direct du gyroscope, de l'accéléromètre, du magnétomètre et plus.",
        "m12_name" to "Flux de Capteurs Matériels en Direct",
        "m12_power" to "Consommation",
        "m12_range" to "Plage maximale",
        "m12_resolution" to "Résolution",
        "m13_buffer" to "Instantané du tampon",
        "m13_desc" to "Lit le tampon circulaire du noyau et le suit en direct avec dmesg -w.",
        "m13_empty" to "Tampon vide ou illisible",
        "m13_follow" to "Démarrer le suivi",
        "m13_live" to "Suivi en direct",
        "m13_name" to "Lecteur du Journal du Noyau (dmesg)",
        "m13_read" to "Lire le tampon (root)",
        "m14_awake" to "Temps d'éveil",
        "m14_boot_id" to "ID de démarrage",
        "m14_deep" to "Veille profonde",
        "m14_desc" to "Durée de fonctionnement, part de veille profonde et chronologie des événements de boot.",
        "m14_name" to "Analyseur de Démarrage",
        "m14_no_log" to "Aucun événement de démarrage disponible",
        "m14_stages" to "Événements de démarrage",
        "m14_stats" to "Statistiques de démarrage",
        "m14_uptime" to "Temps depuis le démarrage",
        "m15_cores" to "Threads",
        "m15_desc" to "Benchmark de stress SHA-256 (mono/multi cœur) plus test de bande passante mémoire.",
        "m15_hint" to "Exécute 2 s monocœur, 2 s tous cœurs en SHA-256 et une passe mémoire de 96 Mo.",
        "m15_mem" to "Mémoire",
        "m15_multi" to "Multicœur",
        "m15_name" to "Test de Performance CPU et RAM",
        "m15_running" to "Benchmark en cours…",
        "m15_scores" to "Scores",
        "m15_single" to "Monocœur",
        "m16_apk_update" to "apk update && upgrade",
        "m16_bootstrapping" to "préparation",
        "m16_desc" to "Rootfs Alpine Linux authentique via PRoot dans le stockage de l'app — avec gestion apk complète.",
        "m16_exited" to "terminée",
        "m16_hint" to "Essayez : apk update • apk add python3 • cat /etc/alpine-release",
        "m16_idle" to "inactive",
        "m16_input_hint" to "tapez une commande puis Envoyer",
        "m16_name" to "Vrai Terminal Alpine Linux PRoot",
        "m16_restart" to "Redémarrer la session",
        "m16_running" to "en cours",
        "m16_share_log" to "Partager la transcription",
        "m16_state" to "Session",
        "m16_stop" to "Arrêter la session",
        "m17_clone" to "Cloner le dépôt (depth 1)",
        "m17_desc" to "Détecte com.termux, le lance et clone des dépôts Git via le git Alpine.",
        "m17_git" to "Cloneur Git",
        "m17_git_hint" to "Les dépôts sont clonés dans /sdcard/MSI/GitRepos avec le git Alpine intégré.",
        "m17_installed" to "installé",
        "m17_launch" to "Lancer Termux",
        "m17_name" to "Intégration Termux et Cloneur Git",
        "m17_not_installed" to "non installé",
        "m18_arch" to "Architecture",
        "m18_config" to "Configuration de la machine",
        "m18_create_disk" to "Créer un disque qcow2",
        "m18_desc" to "Installe et lance des machines QEMU (x86_64 / i386 / aarch64) dans le rootfs Alpine.",
        "m18_disk" to "Taille du disque (Go)",
        "m18_hint" to "QEMU fonctionne sans interface avec console série ; le chemin ISO pointe sous /sdcard.",
        "m18_install" to "Installer QEMU (apk)",
        "m18_launch" to "Lancer dans le terminal",
        "m18_name" to "Émulateur QEMU Multi-Architecture",
        "m18_ram" to "Mémoire",
        "m19_bash_note" to "bash est installé à la demande dans le rootfs Alpine (apk add bash).",
        "m19_desc" to "Exécutez des scripts .sh avec sortie en direct via Alpine /bin/sh, bash Alpine ou sh Android.",
        "m19_engine" to "Moteur de script",
        "m19_name" to "Lanceur de Scripts Bash et Shell",
        "m19_running" to "Exécution…",
        "m19_script" to "Script",
        "m20_args" to "Arguments",
        "m20_compat" to "Compatibilité de l'appareil",
        "m20_compat_no" to "ABI incompatible",
        "m20_compat_yes" to "compatible",
        "m20_desc" to "Inspectez et exécutez directement des binaires ARM/x86 avec root.",
        "m20_hint" to "chmod +x est appliqué automatiquement ; les binaires s'exécutent via su.",
        "m20_inspect" to "Inspecter l'ELF",
        "m20_name" to "Lanceur de Binaires ELF Natifs",
        "m20_not_elf" to "Ce n'est pas un fichier ELF",
        "m20_path" to "Chemin du binaire",
        "m20_pick" to "Binaire",
        "m21_code" to "Code",
        "m21_desc" to "Exécutez des scripts Python 3 et Lua 5.4 dans le rootfs Alpine — de vrais interpréteurs.",
        "m21_in_terminal" to "Ouvrir interactif dans le terminal",
        "m21_install" to "Installer via apk",
        "m21_installed" to "prêt",
        "m21_lang" to "Langage",
        "m21_name" to "Interpréteur Python et Lua",
        "m21_not_installed" to "pas encore installé",
        "m21_running" to "Exécution…",
        "m21_runtime" to "Runtime",
        "m22_analyze" to "Analyser",
        "m22_desc" to "Inspection complète des en-têtes ELF : classe, endianness, machine, point d'entrée, PT_INTERP.",
        "m22_invalid" to "ELF invalide",
        "m22_list" to "Lister le dossier",
        "m22_listing" to "Contenu du dossier",
        "m22_machine" to "Machine",
        "m22_name" to "Analyseur Profond de Binaires ELF",
        "m22_no_dir" to "Dossier illisible",
        "m22_pick" to "Un fichier ELF",
        "m22_type" to "Type",
        "m23_desc" to "chmod / chown n'importe quel fichier via root avec stat en direct.",
        "m23_mode" to "Mode (octal)",
        "m23_name" to "Gestionnaire de Permissions de Fichiers",
        "m23_stat" to "État actuel",
        "m24_custom" to "Entrées PATH personnalisées",
        "m24_desc" to "Inspectez le PATH du shell MSI et ajoutez des dossiers personnalisés.",
        "m24_extra" to "Dossiers supplémentaires (séparés par deux-points)",
        "m24_hint" to "Appliqué à chaque session shell MSI et à l'environnement PRoot.",
        "m24_name" to "Gestionnaire du PATH d'Environnement",
        "m25_applets" to "Applets",
        "m25_desc" to "Détecte busybox, liste ses applets et installe busybox-static via Alpine.",
        "m25_detect" to "Détection",
        "m25_install" to "Installer busybox-static",
        "m25_install_btn" to "Installer",
        "m25_install_hint" to "Le binaire statique est exporté vers /sdcard/MSI/busybox via le gestionnaire de paquets Alpine.",
        "m25_name" to "Intégration et Validateur Busybox",
        "m25_not_found" to "introuvable",
        "m26_actions" to "Actions d'urgence",
        "m26_confirm" to "Exécuter cette commande ?",
        "m26_custom" to "Commande personnalisée (su)",
        "m26_desc" to "Commandes d'urgence : réparer les permissions, purger les caches, remonter, redémarrer.",
        "m26_name" to "Console de Récupération d'Urgence",
        "m27_builder" to "Constructeur de macro",
        "m27_desc" to "Enchaînez des commandes shell avec des délais en macros sauvegardées.",
        "m27_format" to "Une étape par ligne : commande|délai_ms — préfixe '#root ' pour forcer su",
        "m27_name" to "Nom de la macro",
        "m27_none" to "Aucune macro pour l'instant",
        "m27_saved" to "Macros enregistrées",
        "m27_steps" to "Étapes",
        "m28_current" to "Transcription de la session",
        "m28_desc" to "Enregistre la transcription du terminal et les journaux en .txt / .log.",
        "m28_hint" to "Les fichiers sont conservés dans les journaux privés de l'app et partageables.",
        "m28_lines" to "Lignes",
        "m28_name" to "Exportateur de Journaux du Terminal",
        "m28_none" to "Aucun journal pour l'instant",
        "m28_saved" to "Journaux enregistrés",
        "m29_desc" to "Écrivez des notes avec aperçu markdown instantané, stockées en mémoire interne.",
        "m29_edit" to "Modifier",
        "m29_hint" to "Prend en charge # titres, **gras**, `code`, listes et blocs de code.",
        "m29_name" to "Éditeur de Notes Markdown Hors Ligne",
        "m29_new" to "Nouvelle note",
        "m29_none" to "Aucune note pour l'instant",
        "m29_notes" to "Notes",
        "m29_preview" to "Aperçu",
        "m30_desc" to "Scannez tout format de code-barres et générez des QR codes exportables.",
        "m30_generate" to "Générateur",
        "m30_generate_btn" to "Générer le QR",
        "m30_name" to "Scanner QR et Codes-Barres",
        "m30_result" to "Résultat",
        "m30_save" to "Enregistrer dans Téléchargements",
        "m30_scan" to "Scanner",
        "m30_scan_btn" to "Scanner un code",
        "m30_scan_cancel" to "Scan annulé",
        "m31_bytes" to "Octets",
        "m31_desc" to "Convertissez du texte entre Base64, hexadécimal et binaire — plus hachage de fichiers.",
        "m31_file" to "Mode fichier (≤ 8 Mo)",
        "m31_file_b64" to "Encoder le fichier en Base64",
        "m31_file_limit" to "Fichier trop volumineux ou absent (limite 8 Mo)",
        "m31_invalid_b64" to "Entrée Base64 invalide",
        "m31_invalid_bin" to "Entrée binaire invalide",
        "m31_invalid_hex" to "Entrée hex invalide",
        "m31_mode" to "Mode de conversion",
        "m31_name" to "Encodeur Base64, Hex et Binaire",
        "m32_desc" to "Indente, valide et formate des documents JSON et XML.",
        "m32_format" to "Formater et valider",
        "m32_invalid" to "Invalide",
        "m32_invalid_json" to "JSON invalide",
        "m32_invalid_xml" to "XML invalide",
        "m32_mode" to "Format",
        "m32_name" to "Formateur JSON et XML",
        "m32_valid" to "Document valide",
        "m33_add" to "Ajouter une entrée",
        "m33_desc" to "Coffre AES-256-GCM avec dérivation PBKDF2 — entièrement hors ligne.",
        "m33_empty" to "Le coffre est vide",
        "m33_entries" to "Entrées",
        "m33_gen" to "Générer",
        "m33_hint" to "Le coffre est chiffré en AES-GCM ; la clé ne quitte jamais l'appareil.",
        "m33_lock" to "Verrouiller le coffre",
        "m33_master" to "Mot de passe maître",
        "m33_name" to "Gestionnaire de Mots de Passe Chiffré",
        "m33_pass" to "Mot de passe",
        "m33_short_pwd" to "Le mot de passe maître doit contenir au moins 4 caractères",
        "m33_title" to "Titre",
        "m33_unlock" to "Coffre",
        "m33_unlock_btn" to "Déverrouiller / créer le coffre",
        "m33_user" to "Nom d'utilisateur / e-mail",
        "m33_wrong_pwd" to "Mot de passe maître incorrect",
        "m34_desc" to "Balaie le sous-réseau /24 à la recherche d'hôtes actifs et résout les MAC.",
        "m34_found" to "Appareils découverts",
        "m34_hint" to "254 hôtes sont sondés en parallèle ; les MAC viennent de la table ARP.",
        "m34_name" to "Scanner de Dispositifs LAN IP et MAC",
        "m34_none" to "Aucun appareil trouvé",
        "m34_scan" to "Balayer le sous-réseau",
        "m34_scanning" to "Balayage…",
        "m34_subnet" to "Sous-réseau (x.x.x.)",
        "m35_closed" to "fermé",
        "m35_desc" to "Vérifiez les ports TCP et UDP de n'importe quel hôte avec des sockets parallèles.",
        "m35_filtered" to "sans réponse",
        "m35_host" to "Hôte",
        "m35_name" to "Scanner de Ports (TCP/UDP)",
        "m35_none" to "Analysez d'abord une cible",
        "m35_open" to "OUVERT",
        "m35_ports" to "Ports",
        "m35_target" to "Cible",
        "m35_udp_hint" to "UDP « sans réponse » signifie généralement ouvert-ou-filtré (pas d'erreur ICMP).",
        "m36_count" to "Nombre",
        "m36_desc" to "Ping continu avec graphique de latence par réponse et stats min/moy/max.",
        "m36_name" to "Moniteur Avancé de Ping et Latence",
        "m36_start" to "Démarrer le ping",
        "m36_target" to "Cible du ping",
        "m37_adguard" to "AdGuard (blocage de pub)",
        "m37_auto" to "Automatique (opportuniste)",
        "m37_cloudflare" to "Cloudflare (1.1.1.1)",
        "m37_current" to "DNS privé actuel",
        "m37_custom" to "Nom d'hôte personnalisé",
        "m37_desc" to "Impose le DNS privé (DoT) : Cloudflare, Google, AdGuard, Quad9.",
        "m37_google" to "Google (8.8.8.8)",
        "m37_hint" to "Applique le DNS privé Android sur TLS via le fournisseur de réglages (root).",
        "m37_name" to "Imposition DNS Personnalisé (Root)",
        "m37_off" to "Désactiver le DNS privé",
        "m37_presets" to "Préréglages",
        "m37_quad9" to "Quad9 (sécurité)",
        "m38_add_rule" to "Ajouter une règle",
        "m38_allow" to "Autoriser (supprimer)",
        "m38_block" to "Bloquer le port",
        "m38_desc" to "Inspecte les chaînes iptables et ajoute/supprime des règles de blocage via root.",
        "m38_hint" to "Les règles utilisent REJECT sur la chaîne choisie ; le ruleset nftables est affiché s'il existe.",
        "m38_ipt_unavailable" to "iptables indisponible ou bloqué",
        "m38_name" to "Gestionnaire de Règles Pare-feu",
        "m38_nft" to "nftables",
        "m38_nft_available" to "disponible",
        "m38_nft_missing" to "indisponible",
        "m39_desc" to "Table netstat en direct des points de terminaison TCP/UDP mappés aux apps.",
        "m39_hint" to "Lit /proc/net/tcp, tcp6, udp et udp6 ; les UID sont résolus en paquets d'apps.",
        "m39_name" to "Inspecteur de Sockets Réseau Actifs",
        "m39_none" to "Aucun socket lisible",
        "m39_sockets" to "Sockets",
        "m39_table" to "Table des points de terminaison",
        "m40_desc" to "Mesure de latence, débit descendant et montant vers Cloudflare.",
        "m40_down" to "Descendant",
        "m40_hint" to "Télécharge 25 Mo et envoie 10 Mo — surveillez votre forfait.",
        "m40_latency" to "Latence",
        "m40_name" to "Test de Débit Internet",
        "m40_results" to "Résultats",
        "m40_running" to "Mesure…",
        "m40_start" to "Démarrer le test",
        "m40_up" to "Montant",
        "m41_desc" to "Changez l'adresse MAC de n'importe quelle interface avec des valeurs aléatoires ou custom.",
        "m41_hint" to "Le Wi-Fi doit se reconnecter après wlan0 ; certains pilotes refusent les MAC custom.",
        "m41_iface" to "Interface",
        "m41_interfaces" to "Interfaces",
        "m41_invalid_mac" to "Format MAC invalide",
        "m41_name" to "Falsification d'Adresse MAC (Root)",
        "m41_new_mac" to "Nouvelle MAC",
        "m41_random" to "Aléatoire",
        "m41_spoof" to "Falsifier",
        "m42_channel" to "Canal",
        "m42_congestion" to "Congestion des canaux",
        "m42_current" to "Connexion actuelle",
        "m42_desc" to "Puissance du signal, données de liaison, congestion des canaux et réseaux proches.",
        "m42_freq" to "Fréquence",
        "m42_grant" to "Accorder la localisation",
        "m42_level" to "Niveau",
        "m42_location" to "Permission de localisation",
        "m42_location_hint" to "Android exige la localisation pour exposer les résultats de scan.",
        "m42_name" to "Analyseur de Signal et Canaux Wi-Fi",
        "m42_networks" to "Réseaux proches",
        "m42_rssi" to "Signal (RSSI)",
        "m43_cert" to "Certificat",
        "m43_chain" to "Chaîne",
        "m43_cipher" to "Suite de chiffrement",
        "m43_desc" to "Effectue un handshake TLS et inspecte toute la chaîne de certificats.",
        "m43_expired" to "EXPIRÉ",
        "m43_inspect" to "Inspecter",
        "m43_name" to "Inspection de Certificats SSL et TLS",
        "m43_status" to "Validité",
        "m43_target" to "Hôte (port 443)",
        "m43_tls_version" to "Version TLS",
        "m43_valid" to "valide",
        "m43_valid_from" to "Valide depuis",
        "m43_valid_to" to "Valide jusqu'au",
        "m44_connections" to "Connexions suivies",
        "m44_desc" to "Suivi des ouvertures/fermetures de connexions avec comptabilité par app.",
        "m44_hint" to "Sonde les tables de sockets du noyau et les compare ; les deltas RX/TX viennent de TrafficStats.",
        "m44_log" to "Journal d'événements",
        "m44_name" to "Sniffer de Paquets et Journal de Trafic",
        "m44_start" to "Démarrer le suivi",
        "m44_status" to "État",
        "m45_ap" to "État du tethering",
        "m45_ap_off" to "Le hotspot semble inactif",
        "m45_clients" to "Clients connectés",
        "m45_desc" to "Affiche l'état du tethering et les clients du hotspot (via ARP).",
        "m45_hint" to "Les clients sont dérivés de la table ARP quand le hotspot est actif.",
        "m45_name" to "Inspecteur de Hotspot et Partage de Connexion",
        "m45_no_clients" to "Aucun client connecté",
        "m46_answer" to "Votre réponse",
        "m46_bench" to "Banc d'essai",
        "m46_challenge" to "Défi",
        "m46_desc" to "Générez des captchas locaux déformés et mesurez les taux de réussite/échec.",
        "m46_fail" to "ÉCHOUÉ",
        "m46_log" to "Journal des tentatives",
        "m46_name" to "Banc d'Essai Captcha et Anti-Bot",
        "m46_new" to "Nouveau défi",
        "m46_pass" to "RÉUSSI",
        "m46_stats" to "Résolus / échoués",
        "m46_verify" to "Vérifier",
        "m47_desc" to "Mots de passe SecureRandom, jetons hex, UUID et phrases de passe.",
        "m47_hint" to "Toute l'entropie provient du générateur SecureRandom de la plateforme.",
        "m47_length" to "Longueur",
        "m47_mode" to "Mode",
        "m47_name" to "Générateur Sécurisé de Mots de Passe et Jetons",
        "m47_passphrase" to "Phrase de passe",
        "m47_password" to "Mot de passe",
        "m47_regenerate" to "Régénérer",
        "m47_results" to "Généré",
        "m48_confirm" to "Cela détruit les données de façon permanente. Continuer ?",
        "m48_desc" to "Écrase les fichiers avec plusieurs passes aléatoires avant suppression.",
        "m48_exists" to "Existe",
        "m48_hint" to "1-7 passes aléatoires + passe finale de zéros ; les dossiers sont broyés récursivement.",
        "m48_name" to "Broyeur de Fichiers Sensibles",
        "m48_passes" to "Passes",
        "m48_running" to "Broyage…",
        "m48_shred" to "Broyer définitivement",
        "m48_target" to "Cible",
        "m49_desc" to "Testez des expressions régulières avec aperçu de correspondance et remplacement.",
        "m49_input" to "Texte de test",
        "m49_matches" to "Correspondances",
        "m49_name" to "Atelier de Regex",
        "m49_pattern" to "Motif",
        "m49_replace" to "Aperçu du remplacement",
        "m49_with" to "Remplacer par",
        "m50_add_palette" to "Ajouter à la palette",
        "m50_clear" to "Vider la palette",
        "m50_current" to "Couleur actuelle",
        "m50_desc" to "Sélecteur HSL interactif avec codes HEX / RGB et palette enregistrée.",
        "m50_dials" to "Réglages",
        "m50_hex_input" to "Depuis HEX",
        "m50_hue" to "Teinte",
        "m50_lum" to "Luminosité",
        "m50_name" to "Palette de Couleurs et Sélecteur HEX/RGB",
        "m50_palette" to "Palette",
        "m50_sat" to "Saturation",
        "m51_arch" to "Architecture",
        "m51_config" to "Téléchargement",
        "m51_desc" to "Téléchargeur d'ISO avec sélecteur d'architecture, reprise, progression et SHA-256.",
        "m51_dest" to "Destination",
        "m51_name" to "Téléchargeur d'ISO ValiantCore",
        "m51_sha256" to "Calculer le SHA-256",
        "m51_verify" to "Vérification de hash",
        "m51_verify_hint" to "Comparez l'empreinte calculée avec la source de confiance.",
        "m52_config" to "Configuration du serveur",
        "m52_desc" to "Partagez n'importe quel dossier en HTTP sur le LAN avec un index stylisé.",
        "m52_dir" to "Dossier partagé",
        "m52_hint" to "Fonctionne comme service avant-plan de synchronisation ; prend en charge Range pour les médias.",
        "m52_log" to "Journal des requêtes",
        "m52_log_empty" to "Aucune requête pour l'instant",
        "m52_name" to "Serveur Local de Partage HTTP",
        "m52_port" to "Port",
        "m52_running" to "en marche",
        "m52_served" to "Requêtes servies",
        "m52_start" to "Démarrer le serveur",
        "m52_status" to "État",
        "m52_stopped" to "arrêté",
        "m53_all" to "Sauvegarde en masse",
        "m53_apps" to "Paquets installés",
        "m53_backup_user_apps" to "Sauvegarder toutes les apps utilisateur",
        "m53_desc" to "Copiez les APK installées vers le stockage — une à une ou toutes les apps utilisateur.",
        "m53_hint" to "Les sauvegardes vont dans /sdcard/MSI/APKBackups.",
        "m53_name" to "Sauvegarde et Extracteur d'APK",
        "m54_clean_own" to "Nettoyer mes caches",
        "m54_cleaning" to "Nettoyage…",
        "m54_deep_clean" to "Nettoyage profond des caches",
        "m54_desc" to "Nettoyez vos caches, purgez celles du système et nettoyez en profondeur (root).",
        "m54_freed" to "Libéré",
        "m54_name" to "Nettoyeur Profond de Stockage et Cache",
        "m54_own" to "Caches MSI",
        "m54_own_cache" to "Taille du cache propre",
        "m54_system" to "Système (root)",
        "m54_system_hint" to "pm trim-caches libère la cache de toutes les apps ; le nettoyage profond efface /data/data/*/cache.",
        "m54_trim_caches" to "Purger les caches (pm)",
        "m55_desc" to "Empreintes MD5 / SHA-1 / SHA-256 avec comparaison au hash attendu.",
        "m55_expected" to "Empreinte attendue",
        "m55_file" to "Fichier",
        "m55_hash" to "Calculer le hash",
        "m55_match" to "HASH CONFORME",
        "m55_mismatch" to "HASH NON CONFORME",
        "m55_name" to "Vérificateur de Hash ISO et Binaires",
        "m55_quick" to "Sélection rapide",
        "m55_verify" to "Vérifier",
        "m56_desc" to "Localisez les plus gros fichiers qui envahissent votre stockage.",
        "m56_files" to "fichiers",
        "m56_min_size" to "Taille min (Mo)",
        "m56_name" to "Chasseur de Fichiers Volumineux",
        "m56_none" to "Aucun fichier au-dessus du seuil",
        "m56_results" to "Plus gros fichiers",
        "m56_root" to "Racine du scan",
        "m56_scan" to "Chasser",
        "m56_total" to "Total",
        "m57_archive_path" to "Chemin de l'archive",
        "m57_create" to "Créer une archive",
        "m57_desc" to "Créez et extrayez des archives .zip et .tar.gz avec journal de progression.",
        "m57_extract" to "Extraire",
        "m57_name" to "Nom de l'archive",
        "m57_pack" to "Empaqueter",
        "m57_source_dir" to "Dossier source",
        "m57_unpack" to "Dépaqueter",
        "m57_working" to "Travail en cours…",
        "m58_active" to "Transferts actifs et récents",
        "m58_add" to "Ajouter un transfert",
        "m58_desc" to "Mettez des téléchargements en file avec progression en direct (2 simultanés).",
        "m58_enqueue" to "Mettre en file",
        "m58_hint" to "Les fichiers arrivent dans /sdcard/MSI/Downloads.",
        "m58_name" to "File de Téléchargements et Suivi des Transferts",
        "m58_none" to "Aucun transfert pour l'instant",
        "m59_clear" to "Vider l'historique",
        "m59_desc" to "Surveillez le presse-papiers, gardez l'historique et sauvegardez des snippets.",
        "m59_history" to "Historique du presse-papiers",
        "m59_name" to "Historique du Presse-papiers et Snippets",
        "m59_none" to "Rien de copié pour l'instant",
        "m59_paused" to "En pause",
        "m59_save_snippet" to "Enregistrer le snippet",
        "m59_snippets" to "Snippets",
        "m59_watching" to "Surveillance du presse-papiers",
        "m60_desc" to "Rapport diagnostic complet : matériel, mémoire, stockage, logcat et dmesg.",
        "m60_generate" to "Générer le rapport",
        "m60_name" to "Exportateur de Journaux et Diagnostic Système",
        "m60_preview" to "Aperçu",
        "m60_report" to "Rapport",
        "m60_save" to "Enregistrer dans Téléchargements",
        "m61_confirm" to "La partition système est remontée rw et Roboto-Regular est sauvegardée. Continuer ?",
        "m61_current" to "Polices actuelles (échantillon)",
        "m61_desc" to "Installez une TTF personnalisée dans /system/fonts avec sauvegarde et restauration.",
        "m61_font_path" to "Chemin TTF",
        "m61_hint" to "La police est copiée en /system/fonts/MSICustom-Regular.ttf (644).",
        "m61_install" to "Installer une police",
        "m61_install_btn" to "Installer en MSICustom",
        "m61_name" to "Personnalisateur de Polices Système (Root)",
        "m61_not_ttf" to "Le fichier choisi n'est pas un .ttf",
        "m61_restore" to "Restaurer",
        "m61_restore_btn" to "Supprimer la police personnalisée",
        "m62_confirm" to "La bootanimation actuelle est sauvegardée dans /sdcard/MSI. Continuer ?",
        "m62_current" to "Médias actuels",
        "m62_desc" to "Valide et installe bootanimation.zip dans /system/media.",
        "m62_hint" to "Un bootanimation.zip doit contenir desc.txt et des dossiers part.",
        "m62_install" to "Installer",
        "m62_install_btn" to "Installer la bootanimation",
        "m62_invalid_zip" to "Invalide : desc.txt manquant",
        "m62_name" to "Personnalisateur de Bootanimation (Root)",
        "m62_no_file" to "Fichier introuvable",
        "m62_restore" to "Restaurer",
        "m62_restore_btn" to "Restaurer la sauvegarde",
        "m62_valid_zip" to "Structure valide (desc.txt présent)",
        "m62_validate" to "Valider le zip",
        "m62_zip_path" to "Chemin de bootanimation.zip",
        "m63_action" to "Action de la tuile",
        "m63_action_desc" to "Ouvre la session terminal Alpine",
        "m63_added" to "ajoutée au volet",
        "m63_desc" to "Tuile QS qui ouvre le terminal MSI instantanément depuis le volet.",
        "m63_howto" to "Déroulez le volet, modifiez les tuiles et glissez « MSI Terminal » en place.",
        "m63_name" to "Intégration de Tuile dans les Réglages Rapides",
        "m63_not_added" to "pas encore ajoutée",
        "m63_notification" to "Notifications",
        "m63_open_terminal" to "Simuler l'appui sur la tuile",
        "m63_state" to "État de la tuile",
        "m63_test_notification" to "Envoyer une notification de test",
        "m63_tile" to "Tuile",
        "m64_clear" to "Effacer les crashs",
        "m64_crashes" to "Crashs enregistrés",
        "m64_desc" to "Collectez crashs, logcat et diagnostics dans un zip partageable.",
        "m64_hint" to "Le zip contient les journaux de crash, logcat, dmesg et le rapport diagnostic.",
        "m64_name" to "Support de Débogage et Packager de Crashs",
        "m64_none" to "Aucun crash enregistré",
        "m64_package" to "Pack de support",
        "m64_view" to "Voir le dernier",
        "m64_zip" to "Créer le zip de débogage",
        "m65_caches" to "Topologie des caches",
        "m65_cores" to "Cœurs",
        "m65_desc" to "SoC, topologie CPU, caches, GPU, mémoire et stockage en un seul panneau.",
        "m65_device" to "Appareil",
        "m65_freqs" to "Fréquences en direct",
        "m65_name" to "Profileur Matériel Avancé",
        "m65_no_caches" to "sysfs des caches non exposé",
        "m65_soc" to "SoC",
        "m66_available" to "Disponible",
        "m66_desc" to "Mémoire, swap et zram en direct avec graphique d'historique.",
        "m66_details" to "Détails",
        "m66_name" to "Moniteur RAM et Swap en Temps Réel",
        "m66_ram" to "RAM",
        "m66_total" to "Totale",
        "m66_used" to "Utilisée",
        "m67_all" to "Toutes",
        "m67_apps" to "Paquets",
        "m67_desc" to "Chaque paquet installé avec copie du nom en un geste.",
        "m67_installed_at" to "Installé le",
        "m67_name" to "Inspecteur de Paquets Installés",
        "m67_search" to "Rechercher des apps",
        "m67_system" to "Système seulement",
        "m68_desc" to "Table de processus en direct avec mémoire RSS et arrêt via root.",
        "m68_kill" to "Tuer",
        "m68_name" to "Gestionnaire de Processus en Arrière-plan",
        "m68_processes" to "Processus",
        "m69_desc" to "Logcat en direct avec filtres de niveau et de texte (root pour toutes les apps).",
        "m69_empty" to "Pas de flux",
        "m69_filter" to "Filtre",
        "m69_hint" to "le mode root lit le tampon global ; le mode utilisateur ne montre que les logs de MSI.",
        "m69_name" to "Flux Logcat Système en Direct",
        "m69_start" to "Démarrer le flux",
        "m70_desc" to "Table de montage complète avec types, indicateurs RO et barres d'utilisation.",
        "m70_mounts" to "Montages",
        "m70_name" to "Points de Montage et Utilisation Disque",
        "m70_none" to "df indisponible",
        "m71_battery" to "Batterie",
        "m71_desc" to "Zones thermiques, température de batterie et tendance de throttling.",
        "m71_hint" to "Les noms de zone viennent du noyau ; ≥ 60 °C signale un territory de throttling sévère.",
        "m71_name" to "Inspecteur Thermique CPU",
        "m71_zones" to "Zones thermiques",
        "m72_desc" to "Chronomètre de précision avec tours et minuteur à rebours avec alarme.",
        "m72_lap" to "Tour",
        "m72_name" to "Minuteur, Chronomètre et Compteur",
        "m72_stopwatch" to "Chronomètre",
        "m72_timer" to "Minuteur",
        "m73_desc" to "Basculez toute l'interface entre TR, EN, ES, FR et IT instantanément.",
        "m73_hint" to "Le changement est instantané — sans redémarrage ni rechargement.",
        "m73_name" to "Moteur Multi-Langue",
        "m73_status" to "État du moteur",
        "m74_active" to "actif",
        "m74_classic" to "Utilitaire Classique",
        "m74_desc" to "Trois thèmes en direct : Material 3, Hacker/Cyberpunk et Utilitaire Classique.",
        "m74_name" to "Moteur de Thème UI Dynamique",
        "m74_preview" to "Aperçu en direct",
        "m74_select" to "Thème",
        "m75_desc" to "Installez, mettez à jour, vérifiez ou supprimez le rootfs Alpine et surveillez le moteur.",
        "m75_hint" to "Le minirootfs est embarqué pour une installation hors ligne ; la mise à jour récupère la 3.21.x la plus récente.",
        "m75_install" to "Installer le rootfs",
        "m75_log" to "Journal du moteur",
        "m75_name" to "État du Bootstrap du Rootfs Alpine",
        "m75_not_ready" to "NON INSTALLÉ",
        "m75_path" to "Emplacement",
        "m75_ready" to "PRÊT",
        "m75_remove" to "Supprimer le rootfs",
        "m75_status" to "État du rootfs",
        "m75_update" to "Retélécharger et mettre à jour",
        "m75_verified" to "SHA-256 vérifié",
        "m76_check" to "Vérifier le binaire",
        "m76_desc" to "Comparez le type de machine ELF d'un binaire aux ABIs prises en charge.",
        "m76_device" to "ABIs de l'appareil",
        "m76_hint" to "Utile avant d'exécuter des binaires téléchargés sur des appareils et émulateurs exotiques.",
        "m76_match" to "Comparer",
        "m76_name" to "Comparateur d'Architecture ELF Native",
        "m76_will_run" to "Ce binaire fonctionnera sur cet appareil",
        "m76_wont_run" to "Architecture incompatible — ne fonctionnera PAS",
        "m77_app" to "App",
        "m77_available" to "mise à jour disponible",
        "m77_check" to "Vérification de mise à jour",
        "m77_checking" to "Vérification…",
        "m77_desc" to "Infos de version MSI, état du moteur et vérification du manifeste distant.",
        "m77_hint" to "Manifeste distant : github.com/finndev/msi-manifest (version.json).",
        "m77_module_versions" to "Modules du moteur",
        "m77_modules" to "Modules",
        "m77_name" to "Vérificateur de Mise à Jour et Version",
        "m77_offline" to "Pas de réseau ou manifeste indisponible",
        "m77_parse_error" to "Erreur de format du manifeste",
        "m77_up_to_date" to "À jour",
        "m78_desc" to "Le centre de contrôle MSI v4.0.0 : vue d'ensemble et porte d'accès aux 78 modules.",
        "m78_name" to "Tableau de Bord Maître du Système",
        "nav_home" to "Accueil",
        "nav_modules" to "Modules",
        "nav_settings" to "Réglages",
        "nav_terminal" to "Terminal",
        "no" to "Non",
        "ob_continue" to "Continuer",
        "ob_lang_desc" to "Toute l'interface — les 78 modules, menus et boutons — changera instantanément.",
        "ob_lang_note" to "Vous pourrez changer la langue plus tard dans le module 73.",
        "ob_lang_title" to "Veuillez sélectionner votre langue",
        "ob_perm_allfiles" to "Accès à tous les fichiers (Android 11+)",
        "ob_perm_desc" to "MSI a besoin de l'accès au stockage pour gérer fichiers, ISO, sauvegardes et journaux. Les permissions sont demandées maintenant, avant tout le reste.",
        "ob_perm_grant" to "Accorder les permissions",
        "ob_perm_granted" to "accordée",
        "ob_perm_missing" to "manquante",
        "ob_perm_read" to "Lire le stockage externe",
        "ob_perm_skip_warn" to "Certains modules seront limités sans accès au stockage",
        "ob_perm_write" to "Écrire le stockage externe",
        "ob_skip" to "Passer",
        "ob_start" to "Démarrer MSI",
        "ob_welcome" to "Bienvenue dans MSI",
        "open" to "Ouvrir",
        "open_module" to "Ouvrir le module",
        "output" to "Sortie",
        "refresh" to "Actualiser",
        "reset" to "Réinitialiser",
        "root_hint" to "accordez l'accès root (Magisk / KernelSU / APatch) pour activer ce module",
        "root_required" to "Root requis",
        "run" to "Exécuter",
        "save" to "Enregistrer",
        "scan" to "Analyser",
        "scanning" to "Analyse…",
        "search_modules" to "Rechercher parmi 78 modules…",
        "share" to "Partager",
        "size" to "Taille",
        "start" to "Démarrer",
        "stop" to "Arrêter",
        "version" to "Version",
        "yes" to "Oui",
    )
}
